### ISSUE TITLE
"Neovide requires version 0.4 or higher" of what exactly?

### ISSUE THREAD

**Issue by A1ex-N** [neovide/neovide#1031]
**Describe the bug**
When i run neovide --wsl the window opens then immediately closes. When i check the log it says `ERROR [neovide::bridge] Neovide requires version 0.4 or higher`. What does it need version 0.4 of exactly? I have the latest neovide, neovim and wsl kernel.

**Please run `neovide --log` and paste the contents of the `.log` file here:**
INFO [neovide::bridge] Close watcher started
ERROR [neovide::bridge] Neovide requires version 0.4 or higher

**Additional context**
I don't know how --wsl option is supposed to be used

**Comment by Kethku** [comment]
what version of neovim is installed inside of wsl?

**Comment by Kethku** [comment]
That message means it needs version 0.4 or higher of neovim

**Comment by shaunsingh** [comment]
https://github.com/neovide/neovide/blob/491973f64555704bace19daf4c23395318a4a222/src/bridge/mod.rs#L191

Looks like the message is more specific on newer versions. Try out the pre-release version of neovide, it has some important bug fixes. 

The `--wsl` option runs neovim from inside wsl rather than as a normal executable.

**Comment by A1ex-N** [comment]
> what version of neovim is installed inside of wsl?

I'm using neovim v0.5.0

**Comment by Kethku** [comment]
Yeah I would try building from main

**Comment by A1ex-N** [comment]
> Yeah I would try building from main

Building from source solved the problem. Thanks!

**Comment by PyGamer0** [comment]
Looks like this is resolved, closing.
