### ISSUE TITLE
Guifont setting help

### ISSUE THREAD

**Issue by Kethku** [neovide/neovide#1057]
Currently its not clear what name for a font should be used in the guifont setting. I believe we should be able to query skia for the list of available fonts and display it somehow.

I'm told nvim-qt does this, so maybe looking at their UI would be a good strategy

**Comment by LoipesMas** [comment]
In [goneovim](https://github.com/akiyosi/goneovim) doing `set guifont=*` launches a new window in which you can select a font. (However after that it's still `guifont=*`, which bothered me, because I couldn't see what did it set it to to set it in my config)

**Comment by dineshKumar777** [comment]
yes.. this would be great.
Any qt based GUI editor has this feature, because font selector will be handled by qt-widget. All you need to call qt widget with arguments.
So any font selector or minimalistic gui library available for rust?

For example in goneovim this is the implementation:
https://doc.qt.io/qt-5/qfontdialog.html
![image](https://user-images.githubusercontent.com/21097695/143148122-d998847e-2a20-4cc7-b2db-f076b306b7e6.png)

**Comment by Kethku** [comment]
Hrmmm. That would be a pretty big departure from the existing ui system which doesn't have any external UI.

One long term solution might be to implement multiple fonts in a windows and write a plugin which displays them. In the meantime a solution might be to just write out the names of the available fonts to ease getting the name formatting right. This wouldn't be as clean as the QT based solutions but would be a reasonable minimal stop gap until better font rendering flexibility is provided to the end user

**Comment by Kethku** [comment]
Fixed by https://github.com/neovide/neovide/pull/1090 and does it all inside of neovim. I think this is possibly the best we can do with what is available so far in neovide today.

**Comment by Kethku** [comment]
I'm interested in yall's thoughts regarding this approach. I think it may be good enough for now

**Comment by Kethku** [comment]
This has merged. Setting guifont to "*" will open up a buffer with a list of all the expected font names. This is fixed
