### ISSUE TITLE
Some of the parts of telescope.nvim popup window are blured

### ISSUE THREAD

**Issue by Uefair** [neovide/neovide#1071]
**Describe the bug**

**To Reproduce**
1. Ensure [telescope.nvim](https://github.com/nvim-telescope/telescope.nvim) is installed
2. Launch neovide with `--multigrid` option
3. Launch telescope picker(e.g. `Telescope find_files`)
4. See some blurred picker parts(sometimes non of them are blurred, sometimes all are)

**Expected behavior**
non of foreground parts of telescope.nvim popup gets blurred

**Screenshots**
how it looks in terminal
![2021-12-05_19-12-1638720369](https://user-images.githubusercontent.com/62612309/144754101-8307f655-d6eb-46f3-b6e6-22abc6cd89b0.png)
and in neovide
![2021-12-05_19-12-1638720352](https://user-images.githubusercontent.com/62612309/144754108-ec96f38f-a18c-43f6-aeaa-198463d281cf.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux with sway
 - Neovide Version 0.8.0
 - Neovim Version v0.7.0-dev+669-g76af219e3

**Please run `neovide --log` and paste the contents of the `.log` file here:**
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/7656332/neovide_rCURRENT.log)

**Additional context**

**Comment by LoipesMas** [comment]
It looks like telescope creates 4 windows, all with same ordering (`50`) so the actual rendering order is pretty much random.
Same thing happens with floaterm for me.
Not sure how to solve that, because I think we just don't get enough information from neovim.

**Comment by Kethku** [comment]
@LoipesMas this is more information than I've gotten in the past. I didn't realize that they were all rendered at the same order.

**Comment by bmulholland** [comment]
Yeah, nice find.

IMO that's something that should be discussed with Telescope - it feels like something they should fix. I would file it myself, but I don't know enough of what's happening to sound intelligent. Here's a draft for someone more knowledgeable to finish and submit:

Create new issue at Telescope: https://github.com/nvim-telescope/telescope.nvim/issues/new?assignees=&labels=bug&template=bug_report.yml

Title: Multiple windows with same ordering makes custom rendering hard/impossible
Description: To display its Telescope creates four windows, all with the same ordering (50). UIs like neovide may try to display Telescope with more advanced rendering, such as applying a transparent blur. Since all Telescope windows have the same order, how they stack ends up being a race condition, [causing blurred text at random](https://github.com/neovide/neovide/issues/1071). Without accurate ordering information, it is impossible to properly blur only text that the user perceives to be "behind" the Telescope window.
Operating system and version: all
checkhealth telescope: N/A
Steps to reproduce: Download, build, and reun neovide using its instructions: https://github.com/neovide/neovide#install. Then follow the steps at https://github.com/neovide/neovide/issues/1071
Expected behavior: See https://github.com/neovide/neovide/issues/1071
Actual behavior: See https://github.com/neovide/neovide/issues/1071
Minimal config: Any setup that opens telescope, when using neovide --multigrid

**Comment by DimitrisMilonopoulos** [comment]
https://github.com/nvim-telescope/telescope.nvim/issues/1564

Took the liberty of posting this

**Comment by rohit-px2** [comment]
I managed to solve this in nvui by ordering the floating windows by first comparing the zindex, and then by their x and y position where grids to the left and higher get rendered earlier (see [here](https://github.com/rohit-px2/nvui/blob/644e448fcef752d53e82d3dcfff569c4ee88dd0d/src/grid.cpp#L29) for grid ordering comparison and [here](https://github.com/rohit-px2/nvui/blob/644e448fcef752d53e82d3dcfff569c4ee88dd0d/src/grid.cpp#L8) for the float ordering comparison). The zindex, x, and y are taken from the `win_float_pos` message. It's fixed my issues with floating windows so far, hope that helps

**Comment by LoipesMas** [comment]
@rohit-px2 it looks like this solves it. Thanks!
Although it feels a bit hacky, but I guess it's a hack that people already use, so it's kinda a "standard".

Also, it looks like it's being fixed [upstream](https://github.com/nvim-lua/plenary.nvim/pull/280)?
So if other plugins (such as floaterm) also use those functions (which it looks like they do), this hack wouldn't be required.

**Comment by rohit-px2** [comment]
Well I'm the only one using it so depends on what you mean by people :). And yeah it is a hack but it works so far, and if it's fixed upstream like you said the hack shouldn't do anything since the first thing it compares is zindex. Ultimately the main problem is that overlapping floating windows can have the same zindex which will have to get fixed somewhere, since that makes the ordering completely random.

**Comment by Kethku** [comment]
This trick seems great!

I don't think it breaks compatibility and should fix other places which use a similar trick

**Comment by dineshKumar777** [comment]
#979 resolved this. Please take latest and give it a try.

**Comment by Uefair** [comment]
Yeah, it did a thing. Thanks everyone, closing the issue.
![2021-12-10_11-12-1639125843](https://user-images.githubusercontent.com/62612309/145544221-364bca64-04f3-4b37-a66c-61cf5673c4db.png)

**Comment by bmulholland** [comment]
Note that upstream closed the fixes, so if you're not satisfied with the hack it would be best to let them know.

**Comment by bmulholland** [comment]
Actually a bug report with this hacky implementation: the which key list appears below Telescope. To repro, open Telescope and press Ctrl+_
