### ISSUE TITLE
Neovide should send key strokes along with cursor position to the ime system

### ISSUE THREAD

**Issue by zmtq05** [neovide/neovide#1127]
After #1083 was merged, I tried neovide.

I am using [kime](https://github.com/Riey/kime)(korean ime) to type hangul on linux.
It supports xim. I have confirmed that neovide is connecting to the xim server.
but neovide don't send any keyboard input to IME.
So I couldn't even switch the language.

Is it intended or just bug?

**Comment by Kethku** [comment]
IME support is very early days. I know very little about how IME support should work so it may take a bit to get right. @vzex do you have some ideas?

**Comment by vzex** [comment]
> IME support is very early days. I know very little about how IME support should work so it may take a bit to get right. @vzex do you have some ideas?

Sorry, I've no ideas about this

**Comment by Kethku** [comment]
@zmtq05 can you give some more details? You may have to hold our hands a bit to figure this out because I at least know nothing about how IME should work and will need explicit descriptions of:
1. What happens now
2. What you expected to happen
3. Maybe some example program that gets it right

That will help me to understand what needs changed. I'm very suspicious that this will require upstream changes in winit to work properly but can't tell without some more info.

Another thing to try might be to test similar input in alacritty as they have been ahead of the curve in terms of input support for a while now (although I'm hopeful we are catching up)

**Comment by zmtq05** [comment]
> 1. What happens now

neovide doesn't send keyboard input to IME.

> 2. What you expected to happen

process keyboard input in IME then return result to neovide.
So I can type Hangul.

> 3. Maybe some example program that gets it right

`Alacritty`
![ime-alacritty](https://user-images.githubusercontent.com/72651387/148494052-321e07a2-8020-4f5f-af25-367109530de7.png)
alacritty sends keyboard input to IME then return result to alacritty.
same in neovim.

![image](https://user-images.githubusercontent.com/72651387/148494435-36424595-a180-4873-994b-6fb79e3f02b8.png)
_type Hangul in alacritty neovim_

`neovide`
![ime-neovide](https://user-images.githubusercontent.com/72651387/148490995-990d041a-9852-4f32-8d74-de9f50f167cd.png)
neovide doesn't send keyboard input to IME.

I don't know if this happens with other IMEs.(fcitx, ibus ...)

**Comment by Kethku** [comment]
I don't understand. Are the key codes sent to the ime system or just the cursor position?

I've made a branch based on alacritty's ime support which sends the cursor position any time it moves. I have no idea if thats what is expected, but maybe building from this: https://github.com/neovide/neovide/tree/ime-position

**Comment by zmtq05** [comment]
_google translated_
Sorry. I don't know exactly how the IME(xim) works. I apologize for the confusion. :cry: 

It seems that other information besides the cursor position should also be included.

This branch will pass the cursor position to the IME, but it will occasionally send the position information when you move the mouse instead of sending it immediately.

**Comment by Kethku** [comment]
Note: I don't know how to send keystrokes to the ime system and suspect this will require upstream support to get right

**Comment by Jhyub** [comment]
I am also a kime user, and can verify this on my end. Looks like other users with IMEs are also experiencing this. Isn't IME handling supposed to be done on winit? Are there any customizations in neovide?

**Comment by Jhyub** [comment]
It looks like this code doesn't get triggered on linux & xim at the first place.
https://github.com/neovide/neovide/blob/9c1481e1c5b00b4a1f6233665445dcb28cd740be/src/window/keyboard_manager.rs#L62-L68

**Comment by MultisampledNight** [comment]
Yeah, the documentation of `ReceivedImeText` lists

> The user commited an IME string for this window.
> 
> This is a temporary API until [#1497](https://github.com/rust-windowing/winit/issues/1497) gets completed.

That exact issue lists this has been implemented already for X11 and Wayland already, but on the branches `composition-event` and `composition-events` (don't ask me why they made two branches for that). Given that the first one seems to be active, we should consider merging these into our full-blown `new-keyboard-all` branch on our fork.

That may work as a solution for Linux, but not Windows and Mac OS. Hm. I'd be open to try out how this goes, but I don't know any language which needs/uses an IME (yet).

**Comment by Jhyub** [comment]
I would be very thankful if you could do that! If there are any concerns about breaking windows or macos, you could pull it to a seperate test branch and I could compile & test neovide against that.

**Comment by MultisampledNight** [comment]
Just forked winit and neovide, I'll try to rebase the changes from that branch onto our new-keyboard-all. But that'll take a while.

**Comment by MultisampledNight** [comment]
Seems like this won't work. The new keyboard API in our own fork conflicts with the IME at every occasion, which leads to merge conflicts I'm not able to resolve.

**Comment by Jhyub** [comment]
that is unfortunate...

**Comment by Jhyub** [comment]
I've looked in to some more code, and found that this line from alacritty makes it possible for both xim and normal latin characters to input:
https://github.com/alacritty/alacritty/blob/4734b2b85073c775145bce1dd7deefd064003bda/alacritty/src/event.rs#L1120
So, If I understand it correctly, is the fork in a situation where it can't go back to the old `WindowEvent::ReceivedCharacter` because of merge conflicts?

**Comment by fredizzimo** [comment]
We have now merged the new winit keyboard api in https://github.com/neovide/neovide/pull/1789. But I'm sure more work is needed on the Neovide side. But someone who knows how it's supposed to work could take a look at the current state.

**Comment by fredizzimo** [comment]
This is partially fixed by #1899. Unfortunately there's some overlapping at the bottom of the screen. But that will hopefully be fixed soon. There's also no pre-edit support at the moment.

**Comment by fredizzimo** [comment]
The overlapping issue has now been fixed in #1899, so it should be completely fixed there. But it would be nice if someone could try it out there. 

NOTE, IME support on X11, might be completely broken on X11 at the moment, see #1006. But on other platforms and on Wayland it should work. But if you do get it to work on X11, please report it there, so that we can track possible configuration issues.
