### ISSUE TITLE
Paste

### ISSUE THREAD

**Issue by EduardGol** [neovide/neovide#1138]
How to paste from buffer to neovide in insert mode, or in command line ?
![image](https://user-images.githubusercontent.com/45820611/148664009-0b03b651-dd61-4ff5-b293-b5b0105818ec.png)

**Comment by Kethku** [comment]
This is a neovim question rather than something specific to neovide. Please ask in the discord or other neovim/vim specific forums

**Comment by EduardGol** [comment]
This is happen only in neovide windows. I can paste commands in vim or neovim ( in terminal window).

**Comment by Uefair** [comment]
> This is happen only in neovide windows. I can paste commands in vim or neovim ( in terminal window).

`:h c_CTRL-R`

tho you can't paste buffer context in neovim's terminal cuz in shell it's usually a keybind for reverse search(e.g. in bash)

**Comment by EduardGol** [comment]
> > This is happen only in neovide windows. I can paste commands in vim or neovim ( in terminal window).
> 
> `:h c_CTRL-R`
> 
> tho you can't paste buffer context in neovim's terminal cuz in shells it's usually a keybind for reverse search(e.g. in bash, fish)

Thank you for reply, i have succed.
One question more, how i can open neovide in default terminal, without detaching.
Nofork flag same open app in neovide window.

**Comment by fredizzimo** [comment]
I think this is something that Neovide can potentially do better than standard terminal based Neovim. Especially selecting stuff on the command line to copy to somewhere else is a bit unintuitive, since as far as I know you have to open the command history window with `q:` or `q/` or `q?`. But it would be nice to be able to select by mouse and copy directly, and also right click to open a context menu and paste.

Especially the right click context menu is tricky though, since right clicks can be mapped.

Anyway there are already work in progress to add more user friendly copy paste behaviour https://github.com/neovide/neovide/pull/1139 and https://github.com/neovide/neovide/pull/1003
