### ISSUE TITLE
plese support japanese

### ISSUE THREAD

**Issue by eraser5th** [neovide/neovide#1152]
**Is your feature request related to a problem? Please describe.**

Japanese input does not work.

**Describe the solution you'd like**

Please support Japanese input.

**Describe alternatives you've considered**

**Additional context**

**Comment by fredizzimo** [comment]
Some support was added here in this pull request https://github.com/neovide/neovide/pull/1083. From the animation it looks like it’s working. 

But there has also been reports that it’s not working https://github.com/neovide/neovide/issues/1127 as it should.

A big problem is that we don’t really know how it’s supposed to work, since we don’t use IME ourselves, so it would be great if you can look at that issue, and give more information if you are able to.

**Comment by Kethku** [comment]
This is tracked here: https://github.com/neovide/neovide/issues/1127

CLosing in favor of that issue
