### ISSUE TITLE
init.lua not being loaded when launching from the .desktop file (Sway and i3)

### ISSUE THREAD

**Issue by itaranto** [neovide/neovide#1188]
**Describe the bug**
init.lua not being loaded when launching from the .desktop file.

I've tried 4 combinations: on **Sway** I used _pcmanfm-qt_ and _wofi_, on **i3** I used _pcmanfm-qt_ and _rofi_ to open Neovide.

**To Reproduce**
1. Open a launcher (for example wofi)
2. Launch Neovide
3. See Neovide's window
4. Notice that Neovide didn't load the user's init.lua

**Expected behavior**
init.lua gets loaded.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Neovide: 0.8.0 (commit 36200088a4b0da8ad7a36a644ebc2cb741ef3b0c)
 - Neovim: 0.6.1

**Please run `neovide --log` and paste the contents of the `.log` file here:**

[neovide_sway_pcmanfm-qt.log](https://github.com/neovide/neovide/files/7964803/neovide_sway_pcmanfm-qt.log)
[neovide_sway_wofi.log](https://github.com/neovide/neovide/files/7964804/neovide_sway_wofi.log)
[neovide_i3_pcmanfm-qt.log](https://github.com/neovide/neovide/files/7964805/neovide_i3_pcmanfm-qt.log)
[neovide_i3_rofi.log](https://github.com/neovide/neovide/files/7964806/neovide_i3_rofi.log)

**Additional context**
This **does not** happen when using _gtk-launch_ nor launching it directly from the terminal.

**Comment by Kethku** [comment]
Where is your init.lua located? I can't reproduce this on windows.

**Comment by itaranto** [comment]
> Where is your init.lua located? I can't reproduce this on windows.

It's on `~/.config/nvim/init.lua`.

By the way, I have setup `XDG_CONFIG_HOME` to `$HOME/.config` which is not strictly necessary in this case, but it shouldn't be a problem.

**Comment by itaranto** [comment]
Is there any way I can debug this? So far I cannot see anything in the log file.

What is even weirder is that running my launcher from the terminal *and then* selecting Neovide from there works just fine.

**Comment by MultisampledNight** [comment]
I'm using Arch Linux on Sway w/ fuzzel as launcher, and I can't reproduce the issue.

Everything which "inherits" from the terminal works, but doesn't work when running otherwise makes me think it's an issue with your environment variables, in specific `XDG_CONFIG_HOME` and `XDG_CONFIG_DIRS` are suspicious (yeah, I said it, lol) here. Could you run

```vim
:!echo $XDG_CONFIG_HOME
:!echo $XDG_CONFIG_DIRS
```

both in a correctly loaded session and in a non-loaded session, and see whether the outputs truly match (just type the commands character for character in a normal Neovide)? My guess is that some expansion isn't done as it should, `~` is not expanded, you set one of those options in your shell startup file but not in your profile file/didn't tell `systemctl set-environment` about it, or the like. But those are just guesses.

**Comment by itaranto** [comment]
> `XDG_CONFIG_DIRS`

In both cases `:!echo $XDG_CONFIG_HOME` print `/home/ignacio/.config` which is correct since I myself set the `XDG_CONFIG_HOME` variable.

I haven't defined the `XDG_CONFIG_DIRS` variable, so it prints nothing in both cases.

BTW, I set the XDG vars in `/etc/profile`.

**Comment by itaranto** [comment]
Also, running Neovim through my launcher (wofi/rofi) works just fine.

**Comment by itaranto** [comment]
Now that think of, it *is* loading my `init.lua` file, which is in `$XDG_CONFIG_HOME/nvim`.

The problem seems to be that Neovide cannot load my plugins, which are in `$XDG_DATA_HOME/nvim/...`.

But, Neovide reports `$XDG_DATA_HOME` to be `/home/ignacio/.local/share`, which is again, correct.

**Comment by itaranto** [comment]
OK, this is even weirder, plugins seems to be loaded, they just don't work trough my mappings.

For example, I can execute nvim-telescope by doing `:Telescope keymaps`.

I am completely lost on this one.

**Comment by itaranto** [comment]
OK, I found the root cause :smile: 

This is my `init.lua` file:

```lua
require('common')

-- Detect if running from a TTY
if vim.env.TERM == 'linux' then
  vim.cmd 'colorscheme pablo'
else
  require('plugins')
  require('lsp')
  require('completion')

  if vim.g.neovide then
    vim.g['neovide_cursor_animation_length'] = 0.04
  end
end
```

The problem seems to be this check: `if vim.env.TERM == 'linux' then`, it seems to be entering to the "if" branch and not the "else" one.

**Comment by MultisampledNight** [comment]
Yep, that's it. Since you're running from no real terminal emulator and just directly "inherit" from the TTY which your display manager (if at all) started on, you get `linux` as `$TERM` in Neovide even though you're on a GUI. You could introduce an extra check for the nonexistence of `g:neovide` if you want to.

**Comment by itaranto** [comment]
Alright, thanks for the help! I'm gonna close this now.
