### ISSUE TITLE
pixelated text in floating windows with multigrid

### ISSUE THREAD

**Issue by emmanueltouzery** [neovide/neovide#1198]
**Describe the bug**
I'm seeing pixelated text in https://github.com/akinsho/toggleterm.nvim floating windows. The issue does not occur if multigrid is not enabled.

**To Reproduce**
1. install https://github.com/akinsho/toggleterm.nvim
2. run `:ToggleTerm direction=float` with multigrid enabled
3. type some text in the terminal, be especially careful at the bottom-right of the floating window

**Expected behavior**
Same non-pixelated rendering with and without multigrid enabled.

**Screenshots**
without multigrid:
![image](https://user-images.githubusercontent.com/339433/152641164-f1a2aa7e-8338-4006-89f7-4238bc41c401.png)
with multigrid:
![image](https://user-images.githubusercontent.com/339433/152641185-7f0ac97e-24de-406c-bd92-2e4291d2f112.png)

**Desktop (please complete the following information):**
* OS: linux, fedora 35
* Neovide 92bc1725f1733547eb0ae25b740425f03f358c2a
* I'm using nerdfonts JetBrains Mono Nerd Fonts 2.2.0-rc from their github page

**Please run `neovide --log` and paste the contents of the `.log` file here:**

The log was empty

**Comment by fredizzimo** [comment]
I don't know what the cause is, but I'll add an observation here, since at first I didn't see any problem

The problem seems to get worse the further down the screen you go, the top part of the multigrid screenshot looks very close to correct, but it's quite bad at the bottom. it should not be a font caching issue either, since the same text is shown many times.

But there are some text that looks bad even in the upper part, for example `target/release/hotwire`. Aslo in some cases it goes worse when going right, like you can see in the string of a`as` at the bottom.

One explanation could be that the grid somehow have a fractional size, and the text is not rendering at pixel perfect coordinates. This will look very bad, since the font cache is rendered into a fixed integer sized box, and is already anti-aliased inside that. If that is then rendered at a non-pixel coordinates, it could be sampled wrong, and perhaps even anti-aliased twice. Although in theory that should not really happen, since point sampling should be used for drawing the actual glyphs.

**Comment by emmanueltouzery** [comment]
this might not be about floating windows in general. i don't see this with telescope floating windows for instance. Maybe it's specific to terminal floating windows? I've seen it only in that case so far.

**Comment by emmanueltouzery** [comment]
one more very strange thing. i realized now that I can see the issue on a fullhd screen, but NOT on my work screen which has a higher resolution (but is still 100dpi, no DPI scaling). I see the issue on my laptop screen, but not on my work external monitor. When moving neovide on the other screen, I must close & reopen the terminal for the issue to appear to disappear.

**Comment by emmanueltouzery** [comment]
I reproduce it also on the bigger screen if I reduce the neovide window's size

**Comment by sboesebeck** [comment]
I can reproduce the Issue here on MacOS also - using LazyGit. When run in the LazyGit floating term it is rendered pixelated, but when started in a floated terminal window it looks good!
![image](https://user-images.githubusercontent.com/1639447/213299868-f89f742d-73da-4754-9495-5d850ade83a3.jpeg)
![image](https://user-images.githubusercontent.com/1639447/213299958-a275a700-fb59-4783-96ba-096d48329547.jpeg)
![image](https://user-images.githubusercontent.com/1639447/213300002-dc401900-d688-4fb8-a1e8-6b18825bc155.jpeg)

**Comment by emmanueltouzery** [comment]
I cannot reproduce this issue anymore with 0.10.4 for now. It's possible it's still present and I just haven't seen it yet with the new version.. I'll close it for now, and reopen if I'll see it again.
