### ISSUE TITLE
Neovide isn't sourcing the neovim config files when installing from Snap-Store.

### ISSUE THREAD

**Issue by nishu-murmu** [neovide/neovide#1208]
**Describe the bug**
I tried to install Neovide from snap cause it looked very simple but when running neovide it isn't sourcing the Neovim config that i use.

**Expected behavior**
Neovide should source the neovim config files.

**Screen Shots**
It's showing standard startup instead of the customized configured one.
Shown in this screenshot below

![neovide](https://github.com/nishu-murmu/dotfiles/blob/main/assets/neovide.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux .16.4
 - Neovide Version -  0.8.0
 - Neovim Version - 0.6.1

**Comment by ccl1115** [comment]
I got the same situation

**Comment by nishu-murmu** [comment]
> I got the same situation

There are alternative methods to download it, for example manually.
We need to tell the maintainers about this situation.

**Comment by MultisampledNight** [comment]
You've already done that by opening an issue, no worries. Still, thanks for reporting!

Reading about snap for the first time seriously, it seems like snap runs Neovide in a sandbox which prevents it from accessing anything on the system. From looking at https://snapcraft.io/docs/interface-management, I think we have to configure some kind of interface (the `home` one, as I see) to tell snap that we need to access files on the system in order to function correctly. But apparently, that'd require a... manual review process? I'm not sure whether that's worth the hassle.

**Comment by MultisampledNight** [comment]
Also, an easy way to install latest Neovide directly from git is, with Rust being installed, `cargo install --git https://github.com/neovide/neovide`, which compiles from source and puts a binary into `~/.cargo/bin`.

**Comment by nishu-murmu** [comment]
> Also, an easy way to install latest Neovide directly from git is, with Rust being installed, `cargo install --git https://github.com/neovide/neovide`, which compiles from source and puts a binary into `~/.cargo/bin`.

Yeah I actually did that as an alternate to Snap.

**Comment by nishu-murmu** [comment]
Is this because some of the build packages/dependencies are missing in `snapcraft.yaml` file.
I looked up packages names in `snapcraft.yaml` file and the command from (**From source**)
```
sudo apt install -y curl \
    gnupg ca-certificates git \
    gcc-multilib g++-multilib cmake libssl-dev pkg-config \
    libfreetype6-dev libasound2-dev libexpat1-dev libxcb-composite0-dev \
    libbz2-dev libsndio-dev freeglut3-dev libxmu-dev libxi-dev libfontconfig1-dev
```
I saw some of the files are missing like gcc-multilib, g++-multilib are missing in `snapcraft.yaml` file

Is this might be it or am I wrong?

**Comment by MultisampledNight** [comment]
No, to sum up my first message from above: I think https://github.com/neovide/neovide/blob/9c1481e1c5b00b4a1f6233665445dcb28cd740be/snap/snapcraft.yaml#L114-L119 does not include the `home` plug which would be needed in order to access files in your home directory.

I believe gcc-multilib and friends are so often used in snapcraft that they are included by default, else Neovide wouldn't even compile.

**Comment by nishu-murmu** [comment]
Thanks for clearing that.

**Comment by j4qfrost** [comment]
I have updated manually. I'd like to find other volunteers to help manage the snap. In case my life gets busy again. Reach out if you are interested. j4qfrost@gmail.com, frosty#1337
