### ISSUE TITLE
Font renders brighter and slightly thicker

### ISSUE THREAD

**Issue by gmr458** [neovide/neovide#1231]
**Describe the bug**
Neovide makes fonts look bold when they are actually regular or light.

**To Reproduce**
Use a regular or light font in a terminal emulator and Neovide and see the difference.

**Expected behavior**
That the font I use looks the same weight as it does in the terminal emulator.

**Screenshots**
Terminal emulator:
![alacritty](https://user-images.githubusercontent.com/53343401/155860117-306b57e7-ec28-4944-8bc4-2728b12c5b23.png)

Neovide:
![neovide](https://user-images.githubusercontent.com/53343401/155860125-b1ec65de-3960-4595-98ee-2f7a4969b600.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.4 LTS
 - Neovide Version 0.8.0
 - Neovim Version 0.6.1

**Please run `neovide --log` and paste the contents of the `.log` file here:**
https://0bin.net/paste/9jSydr9u#-wgXMfCZAPBxXYI7XC6EZ7I1GFYbS2mXW4HFb+Em1RY

**Comment by PyGamer0** [comment]
To me the font looks brighter in neovide (it doesn't look like the weight of the font has changed). This is probably due to the way neovide handles fonts.

**Comment by kabouzeid** [comment]
The font is definitely more bold too. I'm also experiencing this issue.

**Comment by Kethku** [comment]
Its possible this is a font selection issue on linux. Though, like @PyGamer0, I'm not convinced this isn't just a subtle change in the way the font is rendered. As such I'm going to change the name of this issue unless someone can show a side by side comparison which shows the bold variant of a font which matches the font rendered in neovide.

**Comment by kabouzeid** [comment]
The font is only rendered more bold, it's not actually a different font. For example my icon font is rendered considerably more bold and it certainly doesn't have a bold font variant.

**Comment by phdpe** [comment]
> The font is only rendered more bold, it's not actually a different font. For example my icon font is rendered considerably more bold and it certainly doesn't have a bold font variant.

Yes, I just installed Neovide on Windows and noticed the difference too. I tried to set `guifont` with `w` or `l` but neither works...

**Comment by rmccord7** [comment]
I just installed neovide on windows as well and I see the same thing.

**Comment by gmr458** [comment]
For some reason Neovide renders fonts in a way that makes them look thicker than they are, here's a comparison:
*open each image in different tabs to clearly see the difference

Alacritty:
![alacritty](https://user-images.githubusercontent.com/53343401/216789791-9ceea476-40c8-401d-8aa7-626cd451bfb9.png)

Neovide:
![neovide](https://user-images.githubusercontent.com/53343401/216789796-a2da776e-9879-4538-b882-04b11bc63d44.png)

**Comment by gmr458** [comment]
I tried all the available edging and hinting combinations and none of them achieves a result similar to Alacritty or Kitty.

**Comment by gmr458** [comment]
font renders correctly when using light theme as someone says in this issue https://github.com/neovide/neovide/issues/1635

**Comment by oredaze** [comment]
I have been trying for some tie (again) to get neovide to render fonts properly, but to no avail.
You can see that it's bolder and even wider/stretched vs terminal neovim.
![2023-02-13-184752_1440x900_scrot](https://user-images.githubusercontent.com/51076873/218493742-1e41ddb7-c393-4af7-a23d-710f474aecf2.gif)

**Comment by gmr458** [comment]
@avegancafe Could you give me links to those threads please?

**Comment by fredizzimo** [comment]
@oredaze

That issue is slightly different than the one reported here, although you do see too thick glyphs as well

But your main issue is that the font size is rendered wrong.

An IBM Plex Mono font with a size of 12 has the pixel dimensions of 16.0 x 9.6.  Neoivde uses an integer sized grid, so something has to be done to render the font properly. There are a few different approaches:
1. Automatically resize the font so that the width is an integer. Neovide takes this approach by default if you specify the font size as an integer. So, the actual font size becomes 12.48 with a pixel size of 16.67 x 10.0 pixels. With this approach the line spacing becomes slightly wrong, since that can't be fractions either. But since that is typically less critical, this is the default.
2. Don't resize the font, and adjust the letter spacing instead. This is what happens when you specify a font size as a fraction, for example 12.0. In that case the rendered font size is still 16.0 x 9.6, but the letter spacing will be 10 pixels, so it renders too wide. 
3. Use a fractional sized grid and render with supixel positioning. This way the font size and all spacings will be correct. But it requires support for positioning the glyphs using subpixels. I'm pretty sure that the Skia libary we use do support that, so we should probably add support for it at some point. The fonts might appear slightly blurrier this way, since now neither the width nor height matches exact pixels anymore. But it looks like this is the approach your "terminal" (you didn't specify which) takes.

* NOTE: During the testing of this, I noticed that https://github.com/neovide/neovide/pull/1977 calculates the linespacing wrong.

**Comment by fredizzimo** [comment]
As for the original problem that can be fixed by
```patch
diff --git a/src/renderer/fonts/font_loader.rs b/src/renderer/fonts/font_loader.rs
index 0a36a9a8..0d9328e2 100644
--- a/src/renderer/fonts/font_loader.rs
+++ b/src/renderer/fonts/font_loader.rs
@@ -3,8 +3,9 @@ use std::sync::Arc;
 use log::trace;
 use lru::LruCache;
 use skia_safe::{
-    font::Edging as SkiaEdging, Data, Font, FontHinting as SkiaHinting, FontMgr, FontStyle,
-    Typeface,
+    font::Edging as SkiaEdging,
+    font_style::{Slant, Weight, Width},
+    Data, Font, FontHinting as SkiaHinting, FontMgr, FontStyle, Typeface,
 };
 
 use crate::renderer::fonts::font_options::{FontEdging, FontHinting};
@@ -163,7 +164,7 @@ fn font_style(bold: bool, italic: bool) -> FontStyle {
         (true, true) => FontStyle::bold_italic(),
         (false, true) => FontStyle::italic(),
         (true, false) => FontStyle::bold(),
-        (false, false) => FontStyle::normal(),
+        (false, false) => FontStyle::new(Weight::LIGHT, Width::NORMAL, Slant::Upright),
     }
 }
```
I don't know why Skia renders considers weight normal (400) with thicker than it should. Or maybe the CSS font weights means something different than regular UI font weights. 

Also note that we should make both weight and width configurable, once we have figured out the proper configuration format for the fonts.

**Comment by fredizzimo** [comment]
Actually, after more investigation I'm not convinced that we render the thickness wrong. 

I compared the size rendered by chrome Windows (note that the colors are not quite matching, because chrome renders sRGB colors)

![image](https://github.com/neovide/neovide/assets/9946255/f8b7e393-b51f-401c-be67-f86aff421429)

![image](https://github.com/neovide/neovide/assets/9946255/38e504ee-cc0b-4993-ad65-6c09da79138d)

So, if we are rendering it wrong, then Chrome is doing it too. But depending on the background and font color some fons might appear slightly bolder.

**Comment by fredizzimo** [comment]
It would be great if someone could do a similar comparison on other platforms as well. For the web browser images I used https://fonts.google.com/, and edited the website style with the fonts and backgrounds. 

Since the font sizes are not exact as explained in https://github.com/neovide/neovide/issues/1231#issuecomment-1729305203, I also adjusted them slightly for roughly matching sizes.

But at least based on the above images, I would close the issue and say that Alacritty renders it wrong. Note that Noevide renders this too wide, because I use floating point sizes here to make the actual glyph size the same

One more comparison, Chrome, Neovide, WezTerm, Alacrity, Windows Terminal, and Notepad. Alacritty stands out the most, it also renders the font width completely wrong. Note that Neovide also renders the width wrong, because I use floating point sizes to match the size of the others.
![image](https://github.com/neovide/neovide/assets/9946255/c00c0961-9436-442b-aa09-8caf293ad69f)

**Comment by gmr458** [comment]
@fredizzimo Did you see my second post in this thread? You can see the difference easier if you zoom in on the screenshots, I'm going to do the same, but with other terminals. I also want to point out that this happens when the background is dark and the font is light.

Something I want to say that might be helpful:
While I was installing other terminals to make the comparison, I arrived at Kitty, it had been a while since I had used it and when I configured it with the same font and font size as the other terminals I noticed that it looked thicker than I remembered, it seems that Kitty has a new option called `text_composition_strategy`, it has two options, `platform` and `legacy`, the legacy option makes the font in Kitty look like I remembered it and according to the documentation "A value of legacy uses the old (pre kitty 0.28) strategy for how glyphs are composited. **This will make dark text on light backgrounds look thicker and light text on dark backgrounds thinner**.", this caught my attention, is it possible that Neovide is doing something similar and that is why the font looks thicker?

[More information about Kitty's option text_composition_strategy](https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.text_composition_strategy)

Here comes the comparison, to appreciate the difference I recommend opening each image in a tab of your browser on your laptop or desktop PC and switch between tabs.

Alacritty:
![alacritty](https://github.com/neovide/neovide/assets/53343401/ed95a047-289b-4278-80d5-641e697ae5cf)

Foot:
![foot](https://github.com/neovide/neovide/assets/53343401/96a250fd-179b-42c4-82d6-ba31d5c70cdc)

Kitty (`text_composition_strategy = legacy`):
![kitty_legacy](https://github.com/neovide/neovide/assets/53343401/8b3eb4d3-f0af-4769-b35d-52eeb5b71ed4)

WezTerm:
![wezterm](https://github.com/neovide/neovide/assets/53343401/9a76696c-299e-4f39-a514-3d16ebaac7f1)

Kitty (`text_composition_strategy = platform`):
![kitty_platform](https://github.com/neovide/neovide/assets/53343401/cecac227-8a2f-4455-becd-7c4e8892f834)

Neovide:
![neovide](https://github.com/neovide/neovide/assets/53343401/5cf8c309-672f-4cb3-9f4a-512c73510228)

Alacritty, Foot and Kitty with the `legacy` option look almost the same, Wezterm looks different, Kitty with the `platform` option makes the font look thicker, I prefer how it looks with the `legacy` option, Neovide looks thicker than Alacritty, Foot and Kitty with The `legacy` option, you can see how it has extra pixels around the characters, Kitty with the `platform` option although it looks thicker, does not do this.

It's possible that there is a "legacy" option in Neovide like there is in Kitty?

**Comment by fredizzimo** [comment]
Do you have the images in their original sizes? It's impossible to do a proper comparison with zoomed in images like that. That's not how you look at the fonts in real life.

But other than comparing different, programs to each other there's very little we can do. We use the same font rendering engine as all Chromium based browsers, so unless you can prove that we do something wrong and those browsers render the text differently, I think this bug will stay as a won't fix.

The only thing we can do is to allow a configurable weight, which can be numeric typically between 0 and 1000 and 400 as the default.  By modifying the code, you can already test it out as I explained here https://github.com/neovide/neovide/issues/1231#issuecomment-1729314544. 

It's also very subjective. at least on Windows I find the Neovide and Edge font rendering to be the most readable. But other people probably have different opinions.

**Comment by gmr458** [comment]
> It's impossible to do a proper comparison with zoomed in images like that. That's not how you look at the fonts in real life.

You are right, I just thought this was the best way to see the difference, those little pixels make the difference.

> you can already test it out as I explained here https://github.com/neovide/neovide/issues/1231#issuecomment-1729314544

I will try

Here are the images in their original size:

Alacritty:
![alacritty_full](https://github.com/neovide/neovide/assets/53343401/0602e12e-e522-443b-9e48-51ee7fb9dcab)

Foot:
![foot_full](https://github.com/neovide/neovide/assets/53343401/b09de97c-0278-489e-80fe-b8d475580fff)

Kitty (`text_composition_strategy = legacy`):
![kitty_full_legacy](https://github.com/neovide/neovide/assets/53343401/13fea377-1b05-4ce7-822a-2e2ae8b0b992)

Kitty (`text_composition_strategy = platform`):
![kitty_full_platform](https://github.com/neovide/neovide/assets/53343401/991c561d-d29e-45e2-a0e4-1810616fd25d)

WezTerm:
![wezterm_full](https://github.com/neovide/neovide/assets/53343401/d8d4ba97-01ae-4c97-b7e9-678169b87d7a)

Neovide:
![neovide_full](https://github.com/neovide/neovide/assets/53343401/b09d05cc-af1d-498e-b619-694df69caa3e)

**Comment by fredizzimo** [comment]
To me there doesn't seem to be a huge difference, other than for the really bright colors. But admittedly that inconsistency looks pretty bad. I have not noticed that on Linux myself since my color scheme (everforest) does not suffer from that. 

Which color scheme and font is that, so I can replicate it exactly? I'm guessing `vim-code-dark`, which looks like this on Windows for me. I don't have LSP and treesitter enabled in this test config so some of the highlights are missing. But generally, it looks like the rendering is much more consistent on Windows.  I will try on Linux at some point, are you on X11 or Wayland?

![image](https://github.com/neovide/neovide/assets/9946255/1cd47514-ea71-4cb7-a3cf-b62ad131151f)

**Comment by gmr458** [comment]
> Which color scheme and font is that, so I can replicate it exactly?

The font is Roboto Mono, font size 10.5, color scheme is [dark_modern.nvim](https://github.com/gmr458/dark_modern.nvim) with transparent background and the background of my terminal is black.

> are you on X11 or Wayland?

Wayland

**Comment by fredizzimo** [comment]
Strange The color scheme does not seem to match, it should be `dark_modern` as printed at the bottom. The `vim_code_dark`, looked much closer. Anyway, on windows the font width looks consistent for all colors. But the dark mode sharpness suffers a bit from the transparency, compared to the regular background.

![image](https://github.com/neovide/neovide/assets/9946255/4f285f33-5d11-4ce3-8c91-194e4812d0b9)

And there are not much difference between dark and white backgrounds (both transparent)

![image](https://github.com/neovide/neovide/assets/9946255/28e088aa-811b-4be8-b827-e2d76f86a38e)

**Comment by fredizzimo** [comment]
I switched to my regular configuration with lua LSP.

And no overly bright colors or mismatching widths. So, I guess this is mostly a Linux specific problem. The font might be slightly thicker than some of your examples, but compared to other Windows terminals and programs it seems to be comparable at least.
![image](https://github.com/neovide/neovide/assets/9946255/88b38c02-586a-4062-8fb6-9b1d7f9eaccc)

**Comment by gmr458** [comment]
I did the comparison on Windows and the font in Neovide looks thicker than Alacritty:

Here I am using the builtin colorscheme industry (execute `:colorscheme industry`), this colorscheme shows keywords and the current line number in bold, so I used these commands to make sure there were no bold characters in the screenshot.

```
hi CursorLineNr cterm=NONE gui=NONE
hi Statement cterm=NONE gui=NONE
hi Type cterm=NONE gui=NONE
```

Alacritty:
![alacritty_final](https://github.com/neovide/neovide/assets/53343401/1c1b794e-fe07-4863-bf59-62f0292eb251)

Neovide:
![neovide_final_final](https://github.com/neovide/neovide/assets/53343401/bd12c20d-45c5-4c00-9068-7b8cdd247796)

**Comment by fredizzimo** [comment]
I believe this added as much customization as we can allow through skia

* https://github.com/neovide/neovide/pull/2259

Note that the color is mostly a function of the weight for small font sizes, thinner fonts on dark backgrounds will get darker, and lighter on light backgrounds. All terminals and Neovide renders the fonts too dark on dark backgrounds, so none of it is correct, and therefore the correctness is subjective.

The correct weight is also subjective, since it's not possible to render correctly unless you have a very high dpi display.

To fully compare the colors you should use a big font that with lines that are several pixels wide.

I'm closing this, but will open when someone can give a clear non-subjective reason why we are rendering wrong.

NOTE: some macOS systems render the colors wrong compared to terminals due to lack of srgb support
* https://github.com/neovide/neovide/issues/2044

**Comment by tghosgor** [comment]
I have this issue as well. I have used neovim-qt before but I wanted to get rid of qt5 so I have been using neovim on `foot` terminal for a while now. I have tried out neovide but while neovim-qt & foot exactly match the font rendering, neovide does some weird thing where fonts are thicker and fuzzier. Extents of certain letters are shorter and icons are smaller. I use the plain DejaVu Sans Mono. Unfortunately, I see that the sole maintainer is reluctant to acknowledge the many issues that have been created about font rendering so I am not going to bother creating a new one.

**Comment by fredizzimo** [comment]
A recent Skia update now made this configurable, so here you go:
* #2510

**Comment by tghosgor** [comment]
Now that I've investigated specific cases more, I'll agree. But I am bummed because overall the things are better but the font fuzziness becomes a real problem when the font is set to a small value. I can barely differentiate between `{` and `(` in neovide (because of the _boldness_ and the `{` is somehow shorter) whilst it is different enough in foot. `;` is even worse.

Foot:
![image](https://github.com/neovide/neovide/assets/4239032/bc2db157-ca38-4538-ae6a-7535e0b8e09f)
![image](https://github.com/neovide/neovide/assets/4239032/2d45f2e5-0d5e-47ff-9d87-0abb936d5e2e)

Neovide:
![image](https://github.com/neovide/neovide/assets/4239032/72c40962-b529-44be-b113-cd6f5971fce4)
![image](https://github.com/neovide/neovide/assets/4239032/cb63da03-eefb-4002-8f41-8ddb5d4fdcf8)

Neovide aliased:
![image](https://github.com/neovide/neovide/assets/4239032/7ca488cc-d63a-4fac-8ca5-ea4f13623bb3)
![image](https://github.com/neovide/neovide/assets/4239032/f39873fb-755e-401d-816e-433444619b86)

`#e-alias` can make things even better in certain cases (i.e. above) but then it is too aliased overall. I think the issue I and probably other people are complaining about might be the antialiasing. Maybe the way antialiasing happens in neovide somehow makes things bolder/rounder?

Anyway, I wish I knew how the font stuff worked so I could prepare a solution proposal for this but I have no idea.

**Comment by gmr458** [comment]
@tghosgor Please read the comment before yours, there is a PR opened by the creator of Neovide that adds a couple of configurations that can help you solve your problem, I actually cloned the branch of the PR and was able to emulate the font rendering from Alacritty.

**Comment by fredizzimo** [comment]
@tghosgor, I wonder if you have your monitor setup wrong, because all of your screenshots are very clear to me, with Neovide being the clearest. 

But in any case, I think you should get it close to foot and alacritty by setting `neovide_gamma=0.8` and `neovide_contrast=0.2`.

For the Deformation of the font, you can try setting the hinting to none `#h-none`, that reduces the font quality for some sizes, but the text shape stays truer to what it should be.

**Comment by Terseus** [comment]
I've tried the gamma and contrast trick without noticing any change at all:
```lua
    vim.g.neovide_text_gamma = 0.8
    vim.g.neovide_text_contrast = 0.2
```

I'm sorry but while the rendering differences might seem small, the extra thickness rendered by Neovide makes the text less readable; it's a shame because this issue has been preventing me from using Neovide for about 2 years now.

Neovide may technically do it better or worse but the rendering is very different from all the other tools I've used (terminals, other Neovim GUIs, other GUI editors, web browsers) and the result is worse from an user experience POV, it's very unfortunate that this doesn't match the maintainer taste or experience.

I'm going to give up on Neovide until this gets fixed, if ever.

**Comment by fredizzimo** [comment]
@Terseus 
Can you open a bug report with all your system information and logs for text and contrast not working, because it should definitely have an effect on all systems. Note that it does not update until you restart Neovide.

There should be a wide range of adjustability, so it would be very surprising if nothing suits you.
0.1 Gamma, and 0 contrast should look like this
![image](https://github.com/neovide/neovide/assets/9946255/57e2d0a3-1803-4162-85a4-73d5c718fa9c)
And 3.0 Gamma 1.0 contrast
![image](https://github.com/neovide/neovide/assets/9946255/ddb04913-0fef-4cda-b618-b5297ac098ae)

It's also strange that you see thicker fonts in Neovide compared to web browsers, it has always been very similar for all Comparisions I have done with the same font and same colors (yes the background and font color matters very much). In fact we have got reports that we render the text too thin:
* https://github.com/neovide/neovide/issues/2398

Both Wezterm and Kitty also renders a slightly thicker font on a dark background by default, at least on my system, check the comparisons taken here (you need to download the images and view them as the actual pixel size)
* https://github.com/neovide/neovide/pull/2510

**Comment by Terseus** [comment]
@fredizzimo Sorry, my bad, I was in Neovide 0.12.2, updating to 0.13.1 made `neovide_text_gamma` and `neovide_text_contrast` work, thanks.

> It's also strange that you see thicker fonts in Neovide compared to web browsers, it has always been very similar for all Comparisions I have done with the same font and same colors

I understand and respects your opinion, still Neovide renders the text less readable for me; as I stated before, maybe it's technically worse but Alacritty's font rendering creates a more pleasant experience, and when coding for +8h/day every small improvement matters.

> (yes the background and font color matters very much)

I'm indeed using a dark background, if I switch to a light background the effect is not that pronounced, the font _looks_ thinner even though there isn't really any change in how the font is rendered; it's hard to explain.

Maybe the problem lies in antialiasing?
I would like to compare it with subpixelantialias but unfortunately I can't due to https://github.com/neovide/neovide/issues/2415.
