### ISSUE TITLE
Can't seem to use neovide as the editor for jrnl.

### ISSUE THREAD

**Issue by rikiwarren** [neovide/neovide#1286]
**Describe the bug**
I'm trying to set neovide as the editor for the jrnl command line tool.

If I set `editor: neovide` in `~/.config/jrnl/jrnl.yamal` then trying to edit an existing entry (e.g.` jrnl home --edit`) opens neovide, but it shows me an empty file.

If I use nvim or bbedit, it opens the jrnl content as expected.

 - OS: macOS 12.3.1
 - Neovide 0.9.0

**Please run `neovide --log` and paste the contents of the `.log` file here:**

`neovide --log` also just opens an empty file.

**Comment by MultisampledNight** [comment]
...we should probably adjust the template to mention the actual log.

`neovide --log` should create a `neovide_rCURRENT.log` & another `.log` file in the current directory. We need the one with the most entries (one of them is just one line long). However, in this case it would be probably useful if you __set `neovide --log` as editor, and then submit the `.log`s in the current directory here.__

Please do not enter any sensitive information into Neovide in the meantime, it may be recorded in the log otherwise.

**Comment by rikiwarren** [comment]
Thanks.

Turns out the problem is that neovide wasn't blocking--and that was causing it to have trouble with the temporary files. I switched the command to `neovide --nofork --multigrid` and it works beautifully.

**Comment by MultisampledNight** [comment]
Aha, good to know. @rikiwarren would you mind if I add this information to the wiki?

**Comment by rikiwarren** [comment]
No. Feel free.
