### ISSUE TITLE
Cargo build fails on O.S. FreeBSD 13.0-RELEASE-p11 ,  error compiling winit

### ISSUE THREAD

**Issue by devosalain** [neovide/neovide#1294]
cargo build --release produces :
```
Compiling skia-bindings v0.42.1
   Compiling winit v0.24.0 (https://github.com/neovide/winit?branch=new-keyboard-all#59eb01c1)
error: failed to run custom build command for `skia-bindings v0.42.1`

Caused by:
  process didn't exit successfully: `/usr/home/x/neovide/target/release/build/skia-bindings-f6b014a58c9543af/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=SKIA_DEBUG

  --- stderr
  thread 'main' panicked at 'unsupported target: Target { architecture: "x86_64", vendor: "unknown", system: "freebsd", abi: None }', /home/x/.cargo/registry/src/github.com-1ecc6299db9ec823/skia-bindings-0.42.1/build_support/binaries_config.rs:113:18
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
```
freebsd version 13.0-RELEASE-p11
cargo version : 1.59.0
python version: 3.9.12

**Comment by MultisampledNight** [comment]
`skia-bindings` doesn't seem to support any BSD, unfortunately. We can't do anything about that.

**Comment by luiz00martins** [comment]
@MultisampledNight Same problem, but with windows:
```
error: failed to run custom build command for `skia-bindings v0.52.0`

Caused by:
  process didn't exit successfully: `C:\Users\luizh\AppData\Local\Temp\cargo-installODLfUB\release\build\skia-bindings-79a85edcaa274d34\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=SKIA_DEBUG

  --- stderr
  thread 'main' panicked at 'unsupported target: Target { architecture: "x86_64", vendor: "pc", system: "windows", abi: Some("gnu") }', C:\Users\luizh\.cargo\registry\src\github.com-1ecc6299db9ec823\skia-bindings-0.52.0\build_support\binaries_config.rs:118:18
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `neovide v0.10.3 (https://github.com/neovide/neovide.git#225a5f5d)`, intermediate artifacts can be found at `C:\Users\luizh\AppData\Local\Temp\cargo-installODLfUB`
```

**Comment by MultisampledNight** [comment]
@luiz00martins `skia-bindings` doesn't support the `-gnu` target on Windows: https://github.com/rust-skia/rust-skia/issues/345. Consider downloading the C++ build tools and using the `-msvc` toolchain instead.

**Comment by luiz00martins** [comment]
@MultisampledNight How do I do that?

I already have the MSVC toolchain installed, the compiler just isn't using them (I assume).

**Comment by MultisampledNight** [comment]
@luiz00martins Assuming you're using `rustup` to install and manage Rust, that would be `rustup default stable-x86_64-pc-windows-msvc`, as documented [in the rustup book](https://rust-lang.github.io/rustup/concepts/toolchains.html).

**Comment by luiz00martins** [comment]
> `rustup default stable-x86_64-pc-windows-msvc`

Yep, that solved the issue for me. Thanks!

**Comment by Kethku** [comment]
This is fixed.

**Comment by nowave7** [comment]
Sorry to resurrect this old thread, but how exactly is this fixed? Skia bindings still do not support BSD?

**Comment by fredizzimo** [comment]
Yes, this was wrongly closed as fixed. But I think it we will keep the bug closed unless someone wants to create a fork of skia and `skia-rs` that supports it. Google doesn't want to do it. For more information see https://github.com/neovide/neovide/issues/2096#issuecomment-1789750182

**Comment by xorander00** [comment]
I'm making some headway on this. Got skia building on FreeBSD, now working on the rust-skia crate to get it to use the built artifacts.  
  
Though I just now noticed that rust-skia has an in-tree copy of the skia source tree and I was patching up an upstream copy of the source. It looks like the cargo build script for skia-bindings is expecting the native platform artifacts under the in-tree source, even though it allows setting SKIA_SOURCE_DIR to the root of the source tree. Not sure yet why the source tree path is being ignored, but that's where the build script is currently failing on my side. It's looking for skia/obj/skia.ninja, (which I have in my local skia source tree; generated as part of the build process) to extract a list of features so that it can subsequently generate the library definitions to be used during bindings generation.  
  
I'm calling it a night for now, but figured I'd drop a ping here in case anyone is interested. I'd like to see this working on FreeBSD. Not only because it's my daily driver, but also out of spite since it shouldn't be this difficult to get this going heh.

**Comment by fredizzimo** [comment]
`rust-skia` includes Skia as a submodule, so you should be able to update that and point it to your fork of Skia, and even a local path to a repository temporarily.

**Comment by xorander00** [comment]
@fredizzimo Ah, that does make things a bit easier. Thanks for that! Hopefully that satisfies it, otherwise I'll have to patch up build.rs + build_support.rs in the bindings crate for it to work.
