### ISSUE TITLE
Font rendering issues

### ISSUE THREAD

**Issue by oredaze** [neovide/neovide#1325]
**Describe the bug**

EDIT: After playing with neovide for a while I have stopped using it because it has weird font rendering in general.

In the screenshot below you can see neovide (top) vs terminal nvim (bottom). First the capital letters can't seem to render with a consistent height. Second, see the period, comma and semicolons? They are all squashed and small. It's hard to see them sometimes. Other such small glyphs have similar problems. There are other things that are not supposed to look like they do (for example "t"), but that is not as important.
It is important to note that one of the the issues is produced due to this font (capital height), not others. It is a modified by me ubuntu mono (with fontforge). Obviously I haven't done a perfect job at generating it or something, HOWEVER, neovide is the only program that has issues rendering it. Things that don't have issue include: Alacritty, urxvt, firefox, dmenu, polybar, openbox.
I really want to use that font, and I really like neovide..., but this is hard to work with. Also other fonts are also not cleanly rendered like they should.

**Expected behavior**
Font looks like the bottom example.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/51076873/169873016-5e39c004-c9e5-4fda-be9c-c113b1c3d411.png)

**Desktop (please complete the following information):**
 - OS: Slackware (happens on my other one - gentoo as well)
 - Neovide Version 0.8.0 binary from github
 - Neovim Version 0.7.0

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/8756956/neovide_rCURRENT.log)

If anyone wants me to send them the font to examine it and give me advice on how to generate it properly (to work with neovide) I would appreciate it.

**Comment by M1cha** [comment]
neovides rendering also seems to be too bright or bold:
alacritty:
![image](https://user-images.githubusercontent.com/878458/173221930-b1c8e186-c1d6-4999-b103-222161458c0c.png)

neovide:
![image](https://user-images.githubusercontent.com/878458/173221909-e395c0d1-e35f-40d4-acac-6efa782fcb74.png)

**Comment by oredaze** [comment]
Your case is even better than usual. I get many other problems even when using a different font.
- 1 pixed added horizontal spacing between every character
- certain characters are blurry as compared to the rest of them or as compared to same character in every other program
- stretched font overall, but only with certain fonts (?)
- the font size in pixels doesn't correspond to the number you set in other places (like alacritty). You have to add floating points to _approximate_ it, but it's still not quite it...

I think the font boldness is because neovide doesn't use the standard weight by default. It first uses the heavier weights, so you have to set it manually and that is not very well documented. It's something like:
`Font Name:h12:w57` where w57 is the weight (not Bold or whatever). But that doesn't fix the other problems.

**Comment by MightyPrinny** [comment]
Same problem here, ideally the text should look like in the rest of the system, terminals on linux use the system's settings for hinting, antialiasing ,etc. 
I really liked this gui otherwise, it feels more responsive than the terminal, it'd be great if text looked better and wasn't so wobbly and inconsistent.

**Comment by luisiacc** [comment]
@MultisampledNight is it possible to do something [like `wezterm`](https://wezfurlong.org/wezterm/config/fonts.html), where all the font rendering capabilities are exposed as settings, some fonts work better with hinting, some without, and it's the same for other options of the rasterizer, maybe it would be wise to expose the font rendering options and default them to something sane?

**Comment by MultisampledNight** [comment]
That'd be possible, though mean a rewind of a lot inside of `src/renderer/fonts`. Also Neovide doesn't use harfbuzz + freetype like wezterm seems to, but rather swash which probably provides way less configuration options than you'd hope to.

**Comment by luisiacc** [comment]
Yeah there is not much options, although I think with the ability to change only this 3 options, it could go a long way:
```rust
...
        skia_font.set_subpixel(true);
        skia_font.set_hinting(FontHinting::Full);
        skia_font.set_edging(Edging::AntiAlias);
...
```

I've improved a lot the rendering of some fonts on wezterm just by setting the font hinting to `None`

**Comment by luisiacc** [comment]
I just changed `FontHinting::Full` to `FontHinting::None` and built from source, and my font (SF Mono) looks much better, but this does not apply to all fonts, therefore the need for it to be a setting.

**Comment by luisiacc** [comment]
To any visiting this thread, try building from source with this change on `src/renderer/fonts/font_loader.rs#21`:
from 
```rust
        skia_font.set_hinting(FontHinting::Full);
        skia_font.set_edging(Edging::AntiAlias);
```

to
```rust
        skia_font.set_hinting(FontHinting::None);
        skia_font.set_edging(Edging::SubpixelAntiAlias);
```

Again, this doesn't look good on all fonts.

**Comment by Tmpod** [comment]
Tried that and it had no effect, at least on JetBrains Mono. Font still looks somewhat bold-like, and some characters are misaligned (like the Unicode Braille ones).

Here's some screenshots of LunarVim's dashboard:

kitty:  
![image](https://user-images.githubusercontent.com/35771816/192139423-7d6b44c0-6de6-48db-ad91-b80936e7c4b4.png)

neovide:  
![image](https://user-images.githubusercontent.com/35771816/192139438-37c903e2-397b-4e31-a610-1507ce71b620.png)

**Comment by fredizzimo** [comment]
Which version of jetbrains mono are you using? There has been multiple bug reports for that particular font, mainly since for a long time Nerd fonts included the very first release of the font v1.0.1, while there has been many bugfixes since. The latest releases of Nerd fonts should include a newer of Jetbrains Mono with the issues fixed.

For example version 2.0 of the font fixed these hinting issues, which look very similar to what you are showing in yoru screenshots https://github.com/JetBrains/JetBrainsMono/issues/218 or this one https://github.com/JetBrains/JetBrainsMono/issues/239.

But there has been a lot of other fixes as well https://github.com/JetBrains/JetBrainsMono/releases?page=1

**Comment by fredizzimo** [comment]
That said, there are multiple issues here, and it's possible that other font shaping engines deal with those bugs better

1. We should load the options from FontConfig, where available, for an example see, the alacritty source https://github.com/alacritty/alacritty/commit/b78f3d133960dad38ad21e808723e51661b59881
2. At least the hinting and antialias settings should be exposed, because FontConfig is not available everywhere, some fonts need tuning for the best look
3. We probably should replace Swash with something else. [harfbuzz](https://github.com/harfbuzz/harfbuzz) is pretty much the industry standard. We might be able to copy [Wezterm's bindings]( https://github.com/wez/wezterm/tree/c4d19afa75ef52f65483af2d392f3ac270d57448/deps/harfbuzz) or ask him to publish it as a standalone crate that we can use. Or maybe some [rustybuzz](https://github.com/RazrFalcon/rustybuzz) a pure Rust implementation. In any case we should be able to keep Skia, so the change would not be too big.
4. I can see that Wezterm embeds certain popular fonts. Maybe we should also embed more to ensure that we prefer a more up to date version of Jetbrains mono for example.

**Comment by Tmpod** [comment]
> Which version of jetbrains mono are you using? 

I'm using 2.242 from the Arch `ttf-jetbrains-mono` package, which is the latest one.
I'd assume the issue is not with the font, since it's rendering fine on kitty
(though it also doesn't on konsole nor alacritty).

**Comment by fredizzimo** [comment]
Yes, that version should definitely be good enough. It's strange though, since almost all the buggy fonts reports has been related to jetbrains mono. They are probably still doing something strange, that most other fonts don't.

**Comment by Tmpod** [comment]
> Yes, that version should definitely be good enough. It's strange though,
> since almost all the buggy fonts reports has been related to jetbrains mono.
> They are probably still doing something strange, that most other fonts don't.

mmm, I see. I haven't used neovide with any other font, so can't say if they're
good or not, but I will try some and report back.

**Comment by bfulop** [comment]
What worked me the best, on my _retina, hidpi_ screen was completely removing the line:

```rust
 skia_font.set_edging(Edging::AntiAlias);  
```

and setting (following @luisiacc's recommendation)

```rust
skia_font.set_hinting(FontHinting::None);
```

This gives me nice, thin fonts. Again, this would probably only work on hi-dpi screens.

**Comment by Tmpod** [comment]
Yeah, that helped a bit, but it's still stronger and more misaligned, compared
to what I get with kitty.

**Comment by Nawy** [comment]
I have the same issue.
Device: Mac OS with retina display.
Font: Hack Nerd Font Mono
Kitty renders properly.
Neovide renders too vivid and fonts are fat for sure. It feels wrong.

**Comment by Doerge** [comment]
Piling on with another font that renders too fat. Didn't notice the misalignments.
Font: Meslo LG M DZ for Powerline.
Device: Mac OS w. external monitor 27" @ 3840 x 2160
Top is iTerm, bottom is Neovide:
![image](https://user-images.githubusercontent.com/3216279/195709567-90cfd24b-97fb-4748-8f27-53e9dc3e4f67.png)

**Comment by Nawy** [comment]
The problem with a fat font and vivid colors is solved by setting proper values to font edging and hinting. 
For macOS, I did:
```rust
skia_font.set_hinting(FontHinting::None);
skia_font.set_edging(Edging::SubpixelAntiAlias);
```
Also, I implemented settings with a normal vim config, like this:
```vim
let g:neovide_font_hinting = 'Full'
let g:neovide_font_edging = 'AntiAlias'
```

You can build from here:
https://github.com/neovide/neovide/pull/1603
