### ISSUE TITLE
Release cadence?

### ISSUE THREAD

**Issue by bmulholland** [neovide/neovide#1361]
What's the plan for a release cadence now? How often will those come out?

I'm on the Homebrew version, so while I not longer have to manually upgrade neovide, I'm at the mercy of the release process. I'd like to know if I should switch back to manually pulling and building in order to get regular fixes/updates.

**Comment by MultisampledNight** [comment]
Actually a release now would be possible. But nothing really interesting has changed, except for

- A few bugfixes. Finally no deadlocking at start of Neovide just because that one mutex has been told to unlock though it had no locks.
- Dependency bumps.
- Switch to `arboard` for clipboard support, which also requires Xwayland (in most cases) for clipboard to work on Wayland at the moment.
- Open files in tabs by default.
- Configurable blur.

...hm, if I now look over that, a release could be worth it indeed. @Kethku, would you be open to do that? And anyone else who might look in here, what are your thoughts?

**Comment by LoipesMas** [comment]
Yeah, I think we should release versions more often.

**Comment by MultisampledNight** [comment]
> IMHO point releases for bugfixes are always helpful -- and those are exactly for when nothing really interesting has changed. 

Yeah, right now we're in a bit of an unfortunate situation though, as I've already bumped the version to 0.9 _after_ 0.8 has been released.
