### ISSUE TITLE
[Feature Request] inner-padding around nvim

### ISSUE THREAD

**Issue by kiuKisas** [neovide/neovide#140]
It can be nice to be able to set padding aroud nvim instance.
Here is an exemple with vim on my terminal on the right.
![](https://files.gitter.im/neovide/community/oEZR/2020-02-17-144058_1920x1080_scrot.png)

**Comment by Kethku** [comment]
Correct me if I'm wrong, but this feels like a feature that should be enabled in your window manager, not the app

**Comment by Kethku** [comment]
I don't think it should be the prerogative of the gui to add padding around windows when all other situations that is undesirable.

**Comment by kiuKisas** [comment]
Hum.. I'm talking about inner-padding, but my WM is pretty minimalist, maybe you'll see my point with more decoration:
![2020-02-18-192452_1920x1080_scrot](https://user-images.githubusercontent.com/12698940/74766171-24380300-5285-11ea-80d1-1e37b7b156b2.png)

**Comment by Kethku** [comment]
This is what I'm talking about. I don't see other apps really adding options for inner padding, and I'm concerned about the added complexity for such a niche feature.

**Comment by kiuKisas** [comment]
Ho ok, sorry about that, I though you think about window borders. Well, most of the terminal I used have this options (vte-based, urxvt.. ) so I'm used to it. But you probably right, not a lot of people will need it. I'll see if I can trick my vm. Thank's for your time ! :)

**Comment by Kethku** [comment]
Window border handling is currently all managed by the windowing system which is currently managed by winit, but moving to sdl2 since winit appears to be buggy in a few crucial ways. I'm actually going to reopen this as a future enhancement, but at the moment it is going to be very low priority :( If done in an unobtrusive way I would be happy to take a pull request, but I'd probably be pretty picky about much added complexity since its just a few of us managing the project :)

**Comment by jonvaldes** [comment]
I did a quick experiment, and submitted my WIP to this branch: https://github.com/Kethku/neovide/tree/window-margin-experiment
It is *very* broken right now, but it shows a few issues we'd have to solve to fully implement this.

This is how it looks right now on Linux (Sway window manager), with a huge margin:
![Screenshot_2020-03-01_16-03-1583077228](https://user-images.githubusercontent.com/48644/75628688-ab696d00-5bdb-11ea-820a-1e3f1fc5bd7c.png)

Issues I've found:
- Right now nvim tells us to what color clear the background of each cell. But does it tell us what color to use for areas that have no cell attached? Right now we're not clearing that, and it just accumulates garbage over time
- Changing the margin in runtime can result in horrible visual artifacts, as some parts realize there's been a margin change and others don't. Not sure exactly where that's coming from right now.
- Sometimes the previous issue happens on startup too. My guess is the settings sometimes load after the window is created, and then it behaves like a runtime change.
- The cursor misaligns when adding the margin. I tried just offsetting the cursor by the margin, but it seems to have also made each cursor cell bigger than the actual text cells. No idea why.

**Comment by Kethku** [comment]
I'm going to close this as out of scope. I think this adds too much complexity for a niche use case

**Comment by zezic** [comment]
@jonvaldes I tried to do the same based on your fork with the little changes and got pretty nice results. No glitches, margin have proper background color, pointer positioning is absolutely OK, mouse position is handled correctly and it feels like complexity of the code is almost not increased. I'm new to Rust, I will refactor my code a bit later and try to prepare a good PR for review.

This is how it looks at the moment on Linux:
![Neovid-margins](https://user-images.githubusercontent.com/1945127/95364183-2e247a00-08d9-11eb-8b89-c935d5f64252.png)

**Comment by shaunsingh** [comment]
Gui's on macOS (and I assume windows) can't take advantage of padding through the WM/compositor, since yabai etc. doesn't support it. I understand its outside the scope of neovim, but could you kindly reconsider opening the issue?

**Comment by Kethku** [comment]
Done. However I think its pretty low priority unless somebody wants to take it on.

**Comment by shaunsingh** [comment]
@zezic do you mind sharing your WIP code?

**Comment by zezic** [comment]
@shaunsingh It seems like I deleted it from my disk. It was mostly based on this commit: https://github.com/Kethku/neovide/commit/c376629b17a089c77bcff0ba405a5af96123e7ee
If I remember correctly, there were much additions in the main repo after that, many of them included various changes related to multigrid feature. Probably, this is why I decided that it will be easier to rewrite the feature from scratch.

**Comment by shaunsingh** [comment]
No problem. Alacritty has a similar option so I'll take a look at both.

**Comment by seanstrom** [comment]
@Kethku Could you help guide an implementation of this feature? At the moment I've written some code that changes the size of the rendered image on the canvas, instead of changing the grid width/height. Is that the right approach?

My intention is to allow for pixel values to represent window padding, but I'm not sure what else needs to be adjusted with those padding values. I have attempted to configure the CursorRender with the padding values, but I'm wondering if it would be better to adjust the GridRenderer instead?

Any thoughts?

**Comment by MultisampledNight** [comment]
In the end, padding is "just" shrinking the character grid. So the cursor renderer has nothing to do with that.

Changing the actual rendered size though sounds... a bit interesting. Do you scale down from the original image or do you just provide whole other sizes from the start on?

**Comment by Kethku** [comment]
Will read this sometime today and respond with thoughts. Thanks for the ping!

**Comment by seanstrom** [comment]
Okay I have an update:
I think I was able to adjust the CursorRenderer and the MouseManager to work properly, but now I'm noticing that something with the scrolling logic causes the new adjustments to miscalculate the CursorRenderer position. I'm not certain if it's the scrolling logic, but I'm thinking that it might be because I haven't adjusted anything with scrolling and I'm only noticing miscalculations for the y-axis of the CursorRenderer.

For more context here's a working version of the code pushed up to a branch:
https://github.com/neovide/neovide/compare/main...seanstrom:feature-window-padding

Maybe somebody who understands the scrolling logic and the changes I made can help point me in the right direction. Let me know what ya'll think when you have a chance. Thank you!

**Comment by seanstrom** [comment]
Okay I took a step back to solve this without squishing the image. I was noticing too many glitches that would result from too much padding. So I went through the code again and found a simpler solution by finding the best location to reduce the size of the character grid. This results in no truncating of content and no weird re-calculations of the CursorRenderer & stuff. Here's a new commit with the basics of what I have:
https://github.com/neovide/neovide/compare/main...seanstrom:feature-window-padding-V2

@MultisampledNight I can see now what you meant about not needing to tweak the CursorRenderer, this approach fits much better with all the existing pieces. Thanks for your input! 🙏

**Comment by seanstrom** [comment]
Here's a GIF of what I have working in the latest version:
![Neovide-Window-Padding](https://user-images.githubusercontent.com/2845768/170864326-c989142b-f207-403c-8644-1a15e5007ce3.gif)

**Comment by i-am-the-slime** [comment]
@seanstrom So? It looks very nice, how do we get it?

**Comment by seanstrom** [comment]
@i-am-the-slime at the moment it’s here: https://github.com/seanstrom/neovide/tree/feature-window-padding-V2

If you pull down my fork of neovide with that branch you can build it from source. Though it should likely be updated with the latest commits from the official main branch. Happy to put together a PR if the maintainers are interested too.

**Comment by MultisampledNight** [comment]
Please do! This is _great_.

**Comment by seanstrom** [comment]
Thanks @MultisampledNight 😸 

Here’s a link to the pull request for anyone interested: #1632

**Comment by nmfirdausw** [comment]
How to set window padding? through neovim cofig? any guide?

**Comment by MultisampledNight** [comment]
...I seriously still haven't managed to do the docs on this. You need to be running on git main, and you can set the variables `g:neovide_padding_{top,right,bottom,left}` (with the `{}` to be interpreted as in shell syntax) to control the padding.

**Comment by seanstrom** [comment]
I have mine configured with VimScript like this:
```
let g:neovide_padding_top=35
let g:neovide_padding_left=28
let g:neovide_padding_right=28
let g:neovide_padding_bottom=10
```
Which I think in Lua would be this:
```
vim.g.neovide_padding_top=35
vim.g.neovide_padding_left=28
vim.g.neovide_padding_right=28
vim.g.neovide_padding_bottom=10
```

**Comment by nmfirdausw** [comment]
> I have mine configured with VimScript like this:
> 
> ```
> let g:neovide_padding_top=35
> let g:neovide_padding_left=28
> let g:neovide_padding_right=28
> let g:neovide_padding_bottom=10
> ```
> 
> Which I think in Lua would be this:
> 
> ```
> vim.g.neovide_padding_top=35
> vim.g.neovide_padding_left=28
> vim.g.neovide_padding_right=28
> vim.g.neovide_padding_bottom=10
> ```

Thanks.

**Comment by seanstrom** [comment]
Are you saying that the tabline is not padded? Or that the color of the padding is incorrect?

my assumption was that the padding was transparent, but maybe it uses the background color of the theme 🤔

**Comment by seanstrom** [comment]
I’m trying to understand the screenshots related to the color. In your example are you saying the padding is colored black or gray?

For the second issue related to the bottom padding glitch, are you saying that happens when you set the `cmdline=0` and the window needs to be resized manually before the padding is visible again?

And in general are you configuring the padding and cmdline settings dynamically by typing it in the command line or by setting the values in a config file?

**Comment by seanstrom** [comment]
Okay I’ll try understanding how the color is assigned for the padding and think about how to change that. Not sure how that works at the moment, so that might take a while before I come up with a solution. Hope that’s okay 🙏

About the extra spacing at the bottom, I’m not sure what that is, but it could be related to how Neovim is being resized into the window. It seems Neovide is allowing up to one block of padding to be appended at the bottom. The block of padding is sized from 0 to your font height. You can test this out by increasing the font in Neovide and noticing the extra padding correlates to the font size.

I think that extra padding issue is related to how Neovim is being sized and rendered inside the window. I’ll try taking a look but I’m not sure how to solve that either. I know it has something to do with character grids and stuff, and it seems we have extra space unused by the character grid.
