### ISSUE TITLE
Possible transition to mdbook for documentation

### ISSUE THREAD

**Issue by MultisampledNight** [neovide/neovide#1417]
There have been a number of documentation requests, such as about `guifont`, `g:neovide` and the like. While it's possible for a team member to look at every single one of those, I think it's sensible to open the wiki to everyone as long as someone keeps an eye over it (which will probably be me). What do you all think? cc @dineshKumar777, @shaunsingh

**Comment by sgoudham** [comment]
Coming at this from a different angle... is this a good time to potentially think about hosting documentation elsewhere out with GitHub Wiki? Hosting docs through the wiki is troublesome for this exact situation as there's no pull request mechanism to update the documentation, leaving the wiki to only be updated by maintainers or as this issue is suggesting, making the wiki public and editable by anyone. 

As for other potential documentation solutions... As a rust project, a [mdbook](https://rust-lang.github.io/mdBook/) is a gold standard that many rust users will be aware of. Many notable projects (including the Rust Programming Book) themselves include documentation through mdbook. I would say that this is the closest viable alternative as the wiki is already in markdown and could be easily ported over and hosted through Github Pages. However, there are a few pro's and cons _as with anything and everything_ to consider. 

**Pros:**
- ✅ Contributors can easily update documentation through forking -> pull requests (this might also act as a force multiplier effect to allow for increased quality of documentation)
- ✅ More visually appealing
- ✅ More functionality (runnable code snippets, plugins to improve visual quality etc)

**Cons:**
- ❌ More complex (ideally a build pipeline to automatically build and update docs based on commits/pull requests)
- ❌ Unanswered questions (would it live as a separate repository under the neovide organisation or be part of the neovide repository itself?)
- ❌ Users already know where the current documentation is and are used to it living in the Github wiki, can we be sure that new users will even use the new mdbook? (this in theory could be solved by providing a redirect but again, it is more effort)

I'm curious to know what others think. Is this a viable option or is it too much-unneeded complexity for something that realistically already works?

# Previous Art:
- [The Rust Programming Language](https://doc.rust-lang.org/book/)
- [Wezterm](https://wezfurlong.org/wezterm/)

**Comment by shaunsingh** [comment]
I quite like the idea of using mdbook, but I feel like its a bit overkill for our needs. Ideally we would need a build pipeline, and as sgoudham mentioned you would need to put it under a separate repository. People unfamiliar with rust will also likely be new to mdbook and may get lost, I feel like the GitHub wiki is much easier to manage

I think opening the wiki up to everyone is a good solution for the time being. If we run into issues down the line then we can always easily transition to mdbook. 

Sidenote: This is a gripe which has been brought up in some of the other projects I've worked on before as well. Would be great if the wiki just lived under the `.github/` folder and users could send pull requests for it :(

**Comment by sgoudham** [comment]
Yeah, I just wanted to throw the idea out there, agree with everything you've said!

**Comment by MultisampledNight** [comment]
Great idea! This could also allow usage of https://neovide.dev/ for the documentation, a `neovide/docs` repository would be a good choice imo (though I don't know how this would really look when deployed). This would also allow for someone to stop by and actually clone the repo for offline use, instead of relying on the well-hidden `https://github.com/neovide/neovide.wiki.git` repo, whose git history is somehow using the real name on the GitHub profile anyways.

**Comment by dineshKumar777** [comment]
shaun pretty much covered everything. And if we can able to use neovide.dev thats a plus.
@MultisampledNight  let us know how we can help with documentation.

**Comment by MultisampledNight** [comment]
Alright, then I'll open the wiki now and repurpose this issue for a possible mdbook transition. Thank you!

**Comment by sgoudham** [comment]
I don't mind putting together a small repository/workflow that showcases the deployment of an mdbook to GitHub Pages? There's already established [GitHub action](https://github.com/peaceiris/actions-mdbook) that simplifies the workflow file so the mdbook doesn't necessarily _need_ to live under another repository and can take advantage of the current `gh_pages` branch that already exists.

Of course, this is all hinging on the idea that we even want to do this transition. I wouldn't say the build pipeline or needing to have a separate repository are big blockers but rather the impact on all the end users of Neovide.

**Comment by sgoudham** [comment]
I've been working on a new repo in the neovide organisation (neovide/docs) that is an experiment for using mdbook. I've attached a gif down below of what the website looks like. It's a combination of the existing README and the GitHub Wiki all together in place, the intent would be for it to replace the current [neovide.dev](https://neovide.dev)

Do we want to go ahead with this? You can also find it currently hosted at my test repo here: https://sgoudham.github.io/gh-pages-test if you're wanting to actually click around.

cc: @shaunsingh @MultisampledNight @dineshKumar777 

Website:
![neovide-mdbook](https://user-images.githubusercontent.com/58985301/180886293-ac5dbc01-b8e9-446d-a622-3643264e164a.gif)
