### ISSUE TITLE
Minimize on ctrl+z

### ISSUE THREAD

**Issue by W4RH4WK** [neovide/neovide#1496]
Is it possible to minimize the window on ctrl+z. I quickly checked and it seems like ctrl+z doesn't do anything.

**Comment by MultisampledNight** [comment]
Thanks for reporting! No, that's not possible yet.

But it would be easy to implement, namely an implementing person would need to look at `src/window/mod.rs`, introduce a new function akin to the existing one for the fullscreen, call it appropriately and introduce a new setting in `src/window/settings.rs`.

Using the new setting then (which would be probably called `g:neovide_minimized`), you could bind it yourself using `nnoremap` (it's documented at `:h key-mapping`, which takes a key combination to map and the commands to execute. Neovide refrains from adding new keybindings which existing/switching users might expect to behave otherwise.

**Comment by W4RH4WK** [comment]
I see. Do you think it would be possible to hook into the existing keybinding? I've tried nvim-qt, which ships with the Windows distribution of Neovim, and nvim-qt supports minimize on ctrl+z directly without the need to set a keybinding.

**Comment by MultisampledNight** [comment]
If by "hooking into" you mean "executing on pressed" on your side, yeah, that's possible with the already mentioned `map` family. Though the functionality just isn't there inside of Neovide yet.

**Comment by W4RH4WK** [comment]
I had a quick look at neovim-qt and I think I found the corresponding code. It's an autocmd that executes a vim function that triggers the corresponding UI method:

https://github.com/equalsraf/neovim-qt/blob/7b230767dd04d921ca5c2c31ad46ffd00111aed2/src/gui/runtime/plugin/nvim_gui_shim.vim#L29-L33
