### ISSUE TITLE
macOS: pyright does not launch with the correct python version

### ISSUE THREAD

**Issue by HansMartinJ** [neovide/neovide#1505]
pyright is launched with the following python path: /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/...
which is not the correct python version specified in my PATH

- Download pyright (I used mason.nvim for this)
- Launch neovide and start pyright on a file
- import a library downloaded on the PATH-version of python
- pyright should complain the module does not exist

- This is not a problem when running neovim on my terminal, kitty
- When running :checkhealth, mason.nvim tells me that it uses the wrong python version described above.

 - OS: macOS 12.5.1
 - Neovide Version 0.10.1
 - Neovim Version 0.7.2

**Comment by MultisampledNight** [comment]
Thanks for reporting! Though I think you might be interested into this section in the website: https://neovide.dev/faq.html#neovide-is-not-picking-up-some-shell-configured-information. In effect, you probably have set your `$PATH` in your `.zshrc`, which won't be sourced by Neovide. Since you're on macOS, you might be able to globally modify your `$PATH` through `launchctl config`.

**Comment by HansMartinJ** [comment]
Ah i see, thank you! However, this is quite problematic when dealing with conda environments that one can change dynamically. Any idea how to deal with this?

**Comment by MultisampledNight** [comment]
I suppose you could launch Neovide from the actual environment by running the binary rather than from the .app bundle. Oh wait, is it possible that the macOS specific logic is messing up here again?

**Comment by HansMartinJ** [comment]
Yeah its still messing up when running the binary which is located in /opt/homebrew/Cellar/neovide/0.10.1/Neovide.app/Contents/MacOS

**Comment by HansMartinJ** [comment]
Adding the correct version to the start of the PATH in .zprofile and rebooting didn't work either.

**Comment by rosingrind** [comment]
Can confirm that the issue still persist on `pyenv` with `global` = 3.10.12, checking python with `:checkhealth`.

Open `.app` installed with `brew --cask`:

> Python 3 provider (optional) ~
> - WARNING No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
> - WARNING Could not load Python 3:
>   /usr/bin/python3 does not have the "neovim" module.
>   python3.10 not found in search path or not executable.
>   python3.9 not found in search path or not executable.
>   python3.8 not found in search path or not executable.
>   python3.7 not found in search path or not executable.
>   python not found in search path or not executable.
>   - ADVICE:
>     - See :help |provider-python| for more information.
>     - You may disable this provider (and warning) by adding `let g:loaded_python3_provider = 0` to your init.vim
> - Executable: Not found

Open `neovide` from macOS terminal:

> Python 3 provider (optional) ~
> - pyenv: Path: /opt/homebrew/Cellar/pyenv/2.3.23/libexec/pyenv
> - pyenv: $PYENV_ROOT is not set. Infer from `pyenv root`.
> - pyenv: Root: /Users/beno/.pyenv
> - `g:python3_host_prog` is not set.  Searching for python3 in the environment.
> - Executable: /Users/beno/.pyenv/versions/3.10.12/bin/python3
> - Python version: 3.10.12
> - pynvim version: 0.4.3
> - OK Latest pynvim is installed.

**Comment by rosingrind** [comment]
Just found https://github.com/neovide/neovide/issues/950#issuecomment-1257047594 which solves the issue for me and makes `pyenv` and executables available for nvim's `checkhealth` 👍

**Comment by fredizzimo** [comment]
@rosingrind, I think the original issue is slightly different, also @HansMartinJ said he modified `.zprofile`. But there must have been some mistake there, because that should have worked.

For the original issue, you have two options:
1. Use the global pyright, but make it uses the virtual environment. In order to do this you need to configure pyright using `pyrightconfig.json`. It does not seem to be fully configurable by the `lspconfig`, and there's this issue for example https://github.com/neovim/nvim-lspconfig/issues/717
2. Configure `lspconfig` to start pyright from within your virtual environment `https://github.com/neovim/nvim-lspconfig` I think you can use paths relative to the root for the `executable`, but I haven't tested. I have a very specialized lsp setup myself that allows project specific configuration.

**Comment by fredizzimo** [comment]
Closing this, since it's a pyright configuration issue, not a Neovide issue.
