### ISSUE TITLE
Expose caps lock key to vim

### ISSUE THREAD

**Issue by j0lol** [neovide/neovide#1538]
**Is your feature request related to a problem? Please describe.**
Caps lock is a key with prime "real estate" on the home row. Often users of vim will end up swapping caps lock with escape system-wide, which makes the rest of their system harder to use.

**Describe the solution you'd like**
A GUI application is the perfect scenario for exposing caps lock to neovim. As you have a GUI, you should be able to hook into the raw inputs of the keyboard and see the key is being pressed, unlike vim running within a terminal emulator. 

**Describe alternatives you've considered**
- Swapping caps lock with escape system-wide is counter intuitive for other applications
- Using `Ctrl`-`[` is much more work
- Using `j` `k`/`k` `j` interrupts typing in insert mode

**Comment by MultisampledNight** [comment]
Thanks for the suggestion!

Not sure how this could be meaningfully exposed to Neovim. Everything Neovim has are the "modifiers" `S`, `C`, `M`/`A` and `D`, Neovide cannot randomly add new ones at will. Therefore in order to truly get this implemented, it might be better to open an issue on Neovim's side first instead.

And to be honest, I'm not sure if that's a great idea. Some keyboard layouts use caps lock as an actual flip-flop lock for shift (see Qwerty and Qwertz), some keyboard layouts use caps lock for reaching another layer (see Neo2, Mine, Bone). And they all modify the following keymap in a way that's unpredictable by Neovide.

Therefore I think it might be more reasonable to use a custom keyboard layout and make your compositor/window manager use that keymap only for Neovide, depending on what OS you're on and situation you're in.

**Comment by j0lol** [comment]
Looks like there's something in works on the neovim side: https://github.com/neovim/neovim/pull/8187, https://github.com/neovim/neovim/issues/1480

**Comment by MultisampledNight** [comment]
That seems to be about exposing a function for determining whether caps lock is enabled at the moment to plugins and the like, not about detecting newly pressed caps lock.

**Comment by fredizzimo** [comment]
I'm not sure if it's even possible, since even if we could detect caps lock being pressed, we only get the release when it's pressed again.

But if someone is able to implement the support in winit, we can reconsider it. Closing the issue for now.
