### ISSUE TITLE
Multigrid: cursor not moved for input()

### ISSUE THREAD

**Issue by jamesb6626** [neovide/neovide#1544]
**Describe the bug**
Multigrid doesn't move the cursor for the input() function initially.

**To Reproduce**
1. `map jj <Cmd>echo input('Prompt: ')<CR>`
2. `jj`

**Expected behavior**
Should move cursor immediately, to show where text is being entered.
Particularly bad when there is initial text, e.g. `input('Prompt: ', 'initial')`.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.5
 - Neovide Version edc4cc9 (0.9.0), d453921 (main, after 0.10.1)
 - Neovim Version 0.7.2

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

[neovide_r2022-09-16_20-53-43.log](https://github.com/neovide/neovide/files/9586841/neovide_r2022-09-16_20-53-43.log)
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/9586842/neovide_rCURRENT.log)

**Additional context**
Neovide built from source: `$ cargo install --path .`
This behaviour appears in some plugins.

**Comment by musjj** [comment]
There seem to be some issues with cursor tracking in the command bar in general, when multigrid is on.
For example using [which-key](https://github.com/folke/which-key.nvim)'s `<C-r>` register preview to paste a text into the command bar (when there is pre-existing text in it) will cause neovide to lose track of where the cursor actually is.
![2022-09-19_03-00-28](https://user-images.githubusercontent.com/72612857/190926154-99559fe8-a208-40e5-b65f-e6d126b1dfe5.gif)
I need to move the (now invisible) cursor all the way to the left, in order to get them to sync up.
There are also other cases where it'll lose track of it, but I'm not quite sure of the cause.

**Comment by Kethku** [comment]
Does this still happen? I've personally not encountered this issue for a long time. Please reopen if problems persist
