### ISSUE TITLE
Pywal Theme not working

### ISSUE THREAD

**Issue by kshitijaucharmal** [neovide/neovide#1549]
**Is your feature request related to a problem? Please describe.**
Pywal colors don't work in neovide, the colors are just the default after setting the pywal colorscheme for neovim

**Describe the solution you'd like**
I would like for the pywal colors to work, cause they might be the only thing i dislike about neovide, is that I have to use the gruvbox theme, which i like a lot, but it dosen't match my wallpaper

**Describe alternatives you've considered**
It works in nvim, so i don't understand in neovide

**Additional context**
love neovide otherwise, using it for a month now :)

**Comment by MultisampledNight** [comment]
Thanks for reporting! Do you have any resources on where to read up about pywal and how it "applies" colorschemes?

Also, your NeoVim configuration file also dictates the colorscheme Neovide is using. Probably you're using `colorscheme gruvbox` somewhere in your config.

**Comment by kshitijaucharmal** [comment]
https://github.com/dylanaraps/wal.vim
I'm using this plugin to set the colors, 
and what i know how to set colorschemes, I set gruvbox cause i like it myself, but would like to use the pywal theme
which is based on the wallpaper and looks much better (in my opinion) in vanilla neovim
I know that neovide use the same config as nvim,
so i use `if exists('g:neovide')` to get info specifcally neovide

**Comment by fredizzimo** [comment]
I just did a quick check, so I might be wrong, but that color scheme is totally based on your currrent terminal color scheme, which `pywal` sets. 

This unfortunately means that there's no way to get it to work with Neovide, since neovide is not a terminal application, and therefore does not respect any terminal color configuration. In fact Neovide automatically calls `set termguicolor`, which is explictly forbidden in the readme there.

That said, I don't think it would be too hard to extend Pywal to generete some kind of config file that defines the gui colors, which `wal.vim` could then include. I suggest that you open an issue on those repositories, to see if the maintainers are willing to implement something like that.

**Comment by kshitijaucharmal** [comment]
Okay Thanks!!
