### ISSUE TITLE
Fonts too bold on dark background

### ISSUE THREAD

**Issue by bodograumann** [neovide/neovide#1635]
**Describe the bug**
Text is rendered far too bold when `&background` is `"dark"`.

**To Reproduce**
1. Run `neovide -- -u NONE`
2. Choose font. Among others, I tried `:set guifont=Fantasque\ Sans\ Mono:h10` and `:set guifont=FiraCode\ Nerd\ Font\ Mono:h10` (arch linx, otf-fantasque-sans-mono 1.8.0-2 and aur/nerd-fonts-complete 2.2.2-1)
3. Font looks too bold
4. Switch to `let &background="light"`
5. Font looks too thin.

**Expected behavior**
The font rendering in light and dark mode should yield similar boldness

**Screenshots**
Font: FiraCode
Top: neovim-qt
Bottom: neovide
![Screenshot_20221110-143756](https://user-images.githubusercontent.com/1223583/201106200-b45f797d-fbdc-45c5-96b3-50040d6217e2.png)

And here a comparison with the default configs (neovide left, neovim-qt right)
The effect is not as large anymore here, probably because of the paler colors.
![Screenshot_20221110-150304](https://user-images.githubusercontent.com/1223583/201111971-c53a4949-d439-4cb6-a8cb-1631da578238.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux 6.0.7-arch1-1 x86_64
 - Neovide Version: 0.10.3
 - Neovim Version: 0.8.0

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/9981101/neovide_rCURRENT.log)

**Additional context**
Using the `#e-X` and `#h-X`  does not affect the problem.

This is under wayland / qtile

While neovim-qt can render FiraCode properly (as seen in the screenshot), when choosing Fantastique it also renders too bold and reports: `Warning: Font "Fantastique Sans Mono" reports bad fixed pitch metrics`.

**Comment by oredaze** [comment]
I have the same problem and more:
Font is bolder than it should. It also stretches horizontally for some reason. Compared with terminal neovim.
![218493742-1e41ddb7-c393-4af7-a23d-710f474aecf2](https://user-images.githubusercontent.com/51076873/218530996-8d26a1fd-347e-4c8f-8f8e-10ad5dcadfc2.gif)
terminal uses size of 12, but I have to put 11.3 to get close on neovide. The other options don't do much. (I have been through all of them. Done so in the past too)

**Comment by fredizzimo** [comment]
I'm closing this, since this has more information
* #1231

But looking at the original screenshot I would say that Neovim-qt renders the text on dark background slightly too thin, and neovide slightly too thick, while the situation is reversed with the light theme. Neovim-qt also uses subpixel anti-aliasing which will support thinner font depending on how you have it configured. That's not enabled by default in Neovide, since people reported that some colors get rendered too bright.

In any case, there's no right or wrong, unless you have a very high dpi screen that can render each pixel and doesn't have to compromise. But if you look it from a color perspective then Noevide does it correctly, since the font looks white as it should instead of gray.
