### ISSUE TITLE
lag when resizing buffers

### ISSUE THREAD

**Issue by Masber** [neovide/neovide#1666]
**Describe the bug**
when I have multiple buffer and try to resize them using `<ctrl> + <right arrow key>` or `<ctrl> + <left arrow key>` the animation lags. However, the same animation seems smooth when running nvim from directly from terminal emulator.

**To Reproduce**
1. open lunarvim
2. open a new file
3. open file explorer
4. press ctrl + letf or right keys

**Expected behavior**
I would expext a smooth 60fps animation

**Screenshots**
![Recording 2022-12-05 at 19 01 24](https://user-images.githubusercontent.com/722064/205709186-428ffa0c-d31f-4614-8c12-1a9cabf0d6dc.gif)

**Desktop (please complete the following information):**

 - OS: Ubuntu 20.04.4 LTS
 - Neovide neovide 0.10.3
 - Neovim neovide 0.10.3

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
no output

**Additional context**
I run neovide through lunarvim like the following
```
neovide --neovim-bin $(which lvim)
```

**Comment by siduck** [comment]
https://github.com/neovide/neovide/assets/59060246/c738be0c-38a5-481e-a64c-b377ed8cc5e2


Can confirm that I face this issue too

**Comment by fredizzimo** [comment]
This https://github.com/neovide/neovide/pull/1790 removes the surface creation, and this https://github.com/neovide/neovide/pull/1870 makes everything more smooth.

It does not however, fix the issue completely, the resizing lags a far bit behind the mouse cursor. I think I know what's causing it, we are for some reason sending almost all the input events synchronously to neovim, which means that we have to wait for the previous event to be processed before sending the next one. This should not be needed, we could send both keystrokes and mouse events asynchronously as long as they are sent and received in the correct order. 

For resize events like this, it could further be optimized by not sending the events as often as we do, in order to avoid queuing them up.
