### ISSUE TITLE
Rounded selection border similar to VSCode?

### ISSUE THREAD

**Issue by ChrisMGeo** [neovide/neovide#1686]
**Is your feature request related to a problem? Please describe.**
This is purely an aesthetic problem, so nothing too important.

**Describe the solution you'd like**
Rounded border for visual selections and similar items, similar to VSCode.

**Additional context**
Screenshot of rounded selection in VSCode:
![image](https://user-images.githubusercontent.com/44679968/208808198-fc0fcffd-0b91-461d-9065-a8751083ef47.png)

**Comment by Kethku** [comment]
This is unlikely to happen because we receive the selection border as background highlights from nvim. Its not clear which highlights should have the rounded effect or not.

One possible solution is to have a manual list of highlight rules which should get rounded in this way... Maybe it could be implemented with https://neovim.io/doc/user/ui.html#ui-hlstate? But then its not obvious what the background color should be behind the rounded radius. I dont think this is possible with current information handed to nvim guis
