### ISSUE TITLE
Remove all blank space to the left when pressing CMD + Backspace (Mac at least)

### ISSUE THREAD

**Issue by alexventuraio** [neovide/neovide#1725]
**Is your feature request related to a problem? Please describe.**
I feel odd when I'm on a line that has some tabs or spaces as indentation to the left and I want to merge that line with the one above. I need to press the backspace until the end one by one.

**Describe the solution you'd like**
While in other editor like VSCode or Sublime it is easier to remove all the blank spaces by pressing <kbd>CMD</kbd> + <kbd>Backspace</kbd> (in Mac) keys in one shot as shown in the gif.

![delete-indentation](https://user-images.githubusercontent.com/13169164/210900943-bd268876-12a8-4a73-b1e9-00aaa7d2f098.gif)

**Describe alternatives you've considered**
I do not know of any other

**Additional context**

![delete-indentation-2](https://user-images.githubusercontent.com/13169164/210901426-792b4329-c9c9-45fd-afdf-4aceb663eca3.gif)

**Comment by MultisampledNight** [comment]
Hi, thanks for reporting! This sounds like something you'd want to configure yourself in your `init.vim`/`init.lua`. The command you're looking for in the VimScript variant is `imap`, see `:help imap` for a description.

But I think there are two things you might want to take a look at:

- For actually joining (merging) multiple lines, there is the Normal mode command `J`. So you could select all those lines you want to merge using `<S-v>` (<kbd>Shift</kbd> + <kbd>v</kbd>) and then hit `J` (<kbd>Shift</kbd> + <kbd>j</kbd>) to merge your selection.
- `^` moves to the first character of the line which is not whitespace, `0` moves to the first character of the line regardless of whitespace. So deleting the part inbetween could be accomplished by `^d0` (as in Normal mode commands).

Otherwise, this is not something solvable in Neovide. Neovide is purely a GUI for Neovim, likely you want to open an issue on the Neovim repository instead if you really want to get <kbd>Cmd</kbd>/<kbd>Ctrl</kbd> + <kbd>Backspace</kbd> into Neovim _itself_.

**Comment by alexventuraio** [comment]
@MultisampledNight thanks for answering to this issue and sorry for not clarifying my idea.
- Merging lines into one line is not exactly the main point here, but thanks for sharing those key combination, they definitely will do my life easier.
- `^d0` combination to remove the space also works fine and I think remapping it will be easier to use but not what I meant to share here.

What I really wanted is to be able to just press <kbd>CMD</kbd> + <kbd>Backspace</kbd> (at least in Mac) and get all the indentation space to the left removed as in most of other text editors.

No sure if this is something related to **Neovim** itself because check this out, I'm now using the exact same config in the terminal (iTerm 2) instead of **Neovide** gui and it works there the same way as in **VScode** or **Sublime**.

![delete-indentation-3](https://user-images.githubusercontent.com/13169164/212560014-5d788810-0f51-40e7-a668-6f52c8dce9f3.gif)

**Comment by alexventuraio** [comment]
@MultisampledNight thanks for answering to this issue and sorry for not clarifying my idea.
- Merging lines into one line is not exactly the main point here, but thanks for sharing those key combination, they definitely will do my life easier.
- `^d0` combination to remove the space also works fine and I think remapping it will be easier to use but not what I meant to share here.
---
What I was wondering is to be able to just press <kbd>CMD</kbd> + <kbd>Backspace</kbd> (at least in Mac) and get all the indentation blank space to the left of the line removed as in most of other text editors.

No sure if this is something related to **Neovim** itself, because check this out, I'm now using the exact same config in the terminal (iTerm 2) instead of **Neovide** gui and it works there the same way as in **VScode** or **Sublime**.

![delete-indentation-3](https://user-images.githubusercontent.com/13169164/212560014-5d788810-0f51-40e7-a668-6f52c8dce9f3.gif)

I'm not sure how connecting the UI with Nvim works but I just wanted to ask if theres any possibility for Neovide to mimic the same behavior without any remapping in my nvim config just out of the box.

**Comment by fredizzimo** [comment]
This is not a Neovide bug, to delete the blank space at the start of the line in insert mode use `ctrl-w`, you can remap it if you want. 

To join the lines, just like @MultisampledNight, said.
1. Press `V` to enter Visual line mode and select the lines you want to join
2. Press `J` it will join those lines, remove all the whitespace and add a comma between each line, so there's no need to do anything manually.

**Comment by alexventuraio** [comment]
Again nothing related to joining multiple lines in one.
It's only about the ability to press <kbd>CMD</kbd> + <kbd>Backspace</kbd> and get ride of any extra spaces to the left of the line, as in any other text editor, that's it. Apologize for the confusion here!

The <kbd>CTRL+w</kbd> trick works too and I think I can remap it, thanks a lot for sharing and taking a look at this one @fredizzimo .
