### ISSUE TITLE
Enable smooth scroll without `--multigrid`

### ISSUE THREAD

**Issue by xbladesub** [neovide/neovide#1765]
Is it possible to enable smooth scrolling without enabling `--multigrid`? Some UI staff doesn't work as expected with multigrid enabled (i.e floats transparency, which-key rendering...)

**Comment by tobealive** [comment]
If you don't mind using third party:

one of these would do:
https://github.com/karb94/neoscroll.nvim
https://github.com/echasnovski/mini.nvim/blob/main/readmes/mini-animate.md

Actually, this is what I use also with multigrid enabled (and then `neovide_scroll_animation_length = 0` set). The reason is that there is more work that needs to be done upstream to allow proper evaluation of visible viewport ranges. Which would then allow to fix some glitches with multigrid smooth scrolling. There is an open PR, although the related issue is somewhere in neovim's backlog.

**Comment by xbladesub** [comment]
neoscroll is not a good alternative, but maybe I didn't configure it properly, it doesn't have this kind of "debouncing" effect or "fade out" idk

**Comment by fredizzimo** [comment]
We will most likely get rid of the non multigrid option completely, or at least make multigrid the deafault after this is merged https://github.com/neovide/neovide/pull/1870, and the macOS transparency issues are fixed. On other platforms the transparency should work correctly there.

**Comment by ekungurov** [comment]
In neovim they fixed neovim#12667 and neovim#15075, but we still have #720. 

Does that mean that multigrid could be turned on by default, just don't use transparency features?

Or we still have serious issues with multigrid as #1746 and #1584?

**Comment by fredizzimo** [comment]
@ekungurov all of those issues are fixed in https://github.com/neovide/neovide/pull/1977. which replaced #1870.

**Comment by Kethku** [comment]
Closing as the original issue wont be fix and the other discussion has been superseded by the improved render pr
