### ISSUE TITLE
Startup error: thread 'tokio-runtime-worker' panicked

### ISSUE THREAD

**Issue by LeiTi34** [neovide/neovide#1798]
**Describe the bug**

I just updated my System and now, when I start Neovide, a blank, non responsive window with only the cursor visible appears.

**To Reproduce**

Start Neovide:
```{bash}
$ neovide
```

**Expected behavior**

Neovide starts normally

**Screenshots**
![image](https://user-images.githubusercontent.com/12941627/224660096-878ca18b-bbb5-4fed-b5d8-e4b3a22a7207.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Neovide: 0.10.3
   Package community/neovide
 - Neovim: v0.9.0-dev-1219+g773febc460
   Package: aur/neovim-git

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
[neovide_rCURRENT.log](https://gist.github.com/LeiTi34/e39abf46f9505e63d05b6c3d86db3609)

**Additional context**

Console output:
```{bash}
$ RUST_BACKTRACE=full neovide --log --neovim-bin '/usr/bin/nvim -u NONE' --nofork
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 1 but the index is 1', src/bridge/events.rs:321:17
stack backtrace:
   0:     0x55ddac014d96 - <unknown>
   1:     0x55ddabf27aac - <unknown>
   2:     0x55ddabfe7cf4 - <unknown>
   3:     0x55ddac015d51 - <unknown>
   4:     0x55ddac016c90 - <unknown>
   5:     0x55ddac016852 - <unknown>
   6:     0x55ddac0167c6 - <unknown>
   7:     0x55ddac0167b0 - <unknown>
   8:     0x55ddabddcd82 - <unknown>
   9:     0x55ddabddce01 - <unknown>
  10:     0x55ddac0717c7 - <unknown>
  11:     0x55ddac064af4 - <unknown>
  12:     0x55ddabdf4ed1 - <unknown>
  13:     0x55ddabec78cb - <unknown>
  14:     0x55ddabe29e15 - <unknown>
  15:     0x55ddabe0e265 - <unknown>
  16:     0x55ddac047bca - <unknown>
  17:     0x55ddac050430 - <unknown>
  18:     0x55ddac03d8f5 - <unknown>
  19:     0x55ddac04d5ea - <unknown>
  20:     0x55ddac018335 - <unknown>
  21:     0x7feac71b6bb5 - <unknown>
  22:     0x7feac7238d90 - <unknown>
  23:                0x0 - <unknown>
```

**Comment by fredizzimo** [comment]
This https://github.com/neovim/neovim/pull/19270, broke it, we need to at least parse the additional parameter, that should be an easy fix if someone has time.

It's a bit unfortunate that it got merged now, sine my PR https://github.com/neovide/neovide/pull/1790, does the same without needing that feature. And that feature was made by our initiative by @MDeiml. 

I haven't checked the feature in detail yet. but my first impression is that it only makes the smooth scrolling harder to implement compared to my solution, without any advantages, since we now need to both track the viewport and the physical screen, while my solution only needs the physical screen. And I don't see how it could deal with scrolls bigger than the screen either, since the data to be displayed is not available to us, at least not without additonal API calls.

But I will do a proper analysis, maybe later today, or later this week and write my thoughts in the discussion of my PR. @MDeiml, you can add your tought there too if you have a chance before I do. In any case it will take a long time until we can rely on Neovim 0.9, so I think my solution has to stay at least until then.

**Comment by fredizzimo** [comment]
@LeiTi34, I suggest that you switch to the non-git version of Neovim, or create your custom pkgbuild with a working version. Unless you are a Neovim plugin developer that needs to ensure compatibility with the next version of Neovim, or have a serious but that needs to be fixed, there's no reason to run the git version of Neovim, especially when compatibility between Neovim and Neovide has to be ensured at all times.

**Comment by LeiTi34** [comment]
> @LeiTi34, I suggest that you switch to the non-git version of Neovim, or create your custom pkgbuild with a working version. Unless you are a Neovim plugin developer that needs to ensure compatibility with the next version of Neovim, or have a serious but that needs to be fixed, there's no reason to run the git version of Neovim, especially when compatibility between Neovim and Neovide has to be ensured at all times.

Thank you! I will do that.

**Comment by MDeiml** [comment]
I'm sorry if I broke anything. I'm not to deep in the topic at the moment, just wrote the neovim PR as it seemed to be the easiest fix to me at that time. Recently there was pressure to get it merged, so I finished up my work.

It shouldn't be too much of an issue though. The only change was to add an additional field to the event, so just ignoring that event should be fine.

**Comment by fredizzimo** [comment]
@MDeiml, Sorry, I was not trying to blame you. To be honest I did not believe that my solution would work before I tried it out, and I also had a lot of similar ideas as you, so I can see why you went there.

It's just the timing that was a bit unfortunate, since compared to my PR, there might not be any real advantages of your solution, and in that case it was perhaps a bit premature to merge it. 

I'm not ruling anything out though, your solution might be perfect, or at least there might be some cases that it handles better, and in those cases we should of course use your solution. Right now it's a bit unclear to me if there's anything that it solves better and at least currently it appears to me like it would make things harder to implement. But as I said I have to look at the exact details, and we also need a better understanding of what problems and limitations my solution has. 

So far there has been any practical problems related to the scrolling reported for it, but more testing by more users is obviously needed.

I'm not sure why the push was there, since as far as I know we don't have a prototype implementation on the Neovide side that would take advantage of this, which I think should be the case before pushing new features upstream.

**Comment by MDeiml** [comment]
Can't reconstruct who asked for the feature, but the neovim core team seemed to agree and asked me to complete everything so it could be merged for the next release. It could well be from someone working on a different GUI.

I mean that's the idea: implementing smooth scrolling for a neovim should not be hard. Neovim should do the heavy lifting, i.e. come up with the information needed. That at least was my idea with the `scroll_delta` thing.

What API changes would be necessary to make your implementation easier? Or is it perfectly implementable with the current API? I don't know the process for neovim, but maybe the changes could be replaced by your suggestions before the next release. If not it might be nice for other if your suggestions still get merged.
