### ISSUE TITLE
How to config to download prebuilt skia

### ISSUE THREAD

**Issue by luozhiya** [neovide/neovide#1801]
Hi,
I'am trying to build neovide, but it always built skia from source.
How to config to download prebuilt skia-binaries

* https://github.com/rust-skia/skia-binaries

Thanks

**Comment by fredizzimo** [comment]
I guess you are on Linux, since as far as I know the other platforms should already build with binaries.

Only certain comibnations of features are available and you can check from the releases one the repository you linked. On Linux we use the `gl` and `egl` features, which is not a combination that has binaries. I'm not sure why we include `egl` since that is as far as I know only used for context creation and we use `glutin` for that. So you can try removing `egl` from the `Cargo.toml` file.

**Comment by luozhiya** [comment]
I have removed `egl` from the `Cargo.toml` file, but `cargo` still build without binaries on ArchLinux.

**Comment by Turbid** [comment]
I confirm. It is not clear how to build a package in an isolated environment.

**Comment by fredizzimo** [comment]
I think the Skia update included here https://github.com/neovide/neovide/pull/1870 should built with pre-built binaries, at least it seems to do that for me.

**Comment by fredizzimo** [comment]
This should be fixed in Neovide 0.11.0

**Comment by luozhiya** [comment]
@fredizzimo Awesome,  I compiled neovide 0.11.0 and found that the problem was resolved.
