### ISSUE TITLE
Command+args with --neovim-bin

### ISSUE THREAD

**Issue by AstraLuma** [neovide/neovide#1810]
**Is your feature request related to a problem? Please describe.**
Neovide currently requires `--neovim-bin` to be a real path, with no options for additional arguments. This limits options for creatively wiring neovide to nvim.

**Describe the solution you'd like**
Allow `--neovim-bin` to be a shell command, or at least some kind of simple space-split, or maybe a second flag for the args.

**Describe alternatives you've considered**
I'm currently using TCP-based forwarding, which is annoying (finding ports and setting up each hop).

**Additional context**
I'm doing shenanigans with docker and neovim, and it would improve my work if I could pass arbitrary commands to `--neovim-bin` and use an stdio transport  instead of having to set up TCP forwards all the way through.

Specifically, I'd like to be able to call neovide like `neovide --neovim-bin "docker attach project-nvim"` instead of needing to forward ports.

I expect this will also improve simple SSH cases (ie, running nvim on a remote host with a local neovide).

**Comment by last-partizan** [comment]
AFAIK, additional options after `--` is forwarded to binary, so it's possible to use

```
neovide --neovim-bin /usr/bin/docker -- attach project-nvim
```

Does this work for you?

**Comment by AstraLuma** [comment]
Does it? My code splunking suggests the code assumes that the whole string is a path to the binary.

https://github.com/neovide/neovide/blob/f0d51f2bd3dd3e49b62d7e6d6e979cee554a0761/src/bridge/command.rs#L35-L41

**Comment by fredizzimo** [comment]
Adding `--embed` at the end of the command line might fix this use case, but it probably breaks many other usages. So I don't think Neovide should support it. The binary passed should work as an exact replacement for Neovim, without exceptions. At some point we might also rely on `neovide-bin --version` giving the correct version number.

One easy example where adding it to the end breaks would be when you use `--` . For example `neovide --neovim-bin nvim -- -- file.txt` which is expanded to `nvim -- file.txt --embed` by neovide and instead open a file called `--embed`

I'm not even sure if neovide would work over an SSH connection like you are suggesting due to buffering issues. The preferred way is to use tcp or unix domain socket tunnelling and the `--server` argument https://neovide.dev/features.html#tcp-example.

But if you really want do try stdio forwarding, then you can easily create a wrapper shell script that rearranges and adds parameters the way you want before calling nvim.

**Comment by fredizzimo** [comment]
I'm closing this, creating a wrapper shell script that calls neovim with the arguments you want is the way to go.
