### ISSUE TITLE
Weird  font on macOS arm64

### ISSUE THREAD

**Issue by ColinZou** [neovide/neovide#1872]
No matter using the github binary, or compiling it from scratch. The font display on my mac is just NOT correct.

**To Reproduce**
1. Darwin Colins-Mac-mini.local 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:41 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T8103 arm64
2. Download neovide latest version 0.10.4
3. Run it, the font is rendering like my screenshot. The text seemed to be scaled in horizontal direction.

**Expected behavior**
Displaying font properly.

**Screenshots**
![font-issue](https://github.com/neovide/neovide/assets/6029079/f512c40a-0494-4349-9f5b-c5caaec99301)

**Desktop (please complete the following information):**
 - OS: macOS 13.3.1
 - Neovide Version 0.10.4
 - Neovim Version 0.9.0

**Additional context**

**Comment by jakucermak** [comment]
It's look like you are trying to access non installed font. Did you check?

**Comment by fredizzimo** [comment]
I don’t think the fontname to `guifont` should have underscores like `CaskaydiaCove_Nerd_Font`. Check for supported fonts using `set guifont= *`

**Comment by ColinZou** [comment]
Thanks guys. I switched to pure console version, without any GUI. The console's font setting rocks.

**Comment by fredizzimo** [comment]
We can't help you if you don't provide any information. Did you check that the font you are using is supported by running `:set guifont=*` first? 

Also, the logs you provided and the screenshot does not match, which makes the problem very hard to diagnose. And the screenshot seem to indicate that you have selected a non-monospace, which can't be rendered properly on the a grid. The actual screen in the log seems to only contain a nerd tree display with some asian characters. BTW, I deleted the log files from your post, since they might contain some sensitive data, and there was at least one e-mail address there.

Also in the log, you appear to set the font two times in your init file, that's not recommended, try setting it just once,
You are setting and then
* `CaskaydiaCove_Nerd_Font:h10`
* `IBM Plex Mono:h14,Hack:h14,Source Code Pro:h15,Menlo:h15` , that's the wrong format, the height can only be specified once at the end for all fonts.

See https://neovide.dev/configuration.html#font for the format.

**Comment by Kethku** [comment]
Closing for lack of response
