### ISSUE TITLE
Memory leak when built with profiling support

### ISSUE THREAD

**Issue by AThePeanut4** [neovide/neovide#1892]
**Describe the bug**
When built with the new profiling support, Neovide seems to have a memory leak, allocating about 10-20MB per second while the window is in focus. When the window is out of focus, it allocates around 1MB per second.

**To Reproduce**
1. Build Neovide with `cargo build --release --features profiling` or `cargo build --release --features gpu_profiling`
2. Open something like htop to monitor memory usage
3. Open Neovide alongside htop and keep Neovide in focus
4. Observe RES memory increasing by 10-20MB per second (might need to move the mouse around or type to get this to happen)
5. Minimize/unfocus Neovide and observe memory usage increasing at a lower rate, around 1MB/s

**Desktop (please complete the following information):**
 - OS: Hyprland on Arch Linux, using XWayland
 - Neovide Version: latest commit on main, 13f6f8fbe867453f11dec8c89e4d0f58957026f3
 - Neovim Version: v0.9.1

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/11708797/neovide_rCURRENT.log)

**Additional context**
I'm running XWayland because trying to run natively on Wayland just crashes immediately. `new-keyboard-v3` does fix this, but it doesn't have the profiling support so the issue doesn't show up there.

Running Neovide the same way on my MacBook running macOS 13.4 also has this issue, but it is much less pronounced (idle increase of 100-200KB per second, and 1-2MB per second when typing or moving the mouse around).

**Comment by fredizzimo** [comment]
I think this is expected, Neovide will buffer all the profiling events until you connect the tracy profiler client https://github.com/wolfpld/tracy. And there's a lot of data to be captured, on Linux the full call stack is captured at each context switch, on Mac that might not be the case (on Windows you have to run Neovide in Administrator mode for that), which explains the difference.

**Comment by AThePeanut4** [comment]
Alright that makes sense, I had a feeling that was the cause. The `neovide-git` AUR package has `--all-features` specified in the PKGBUILD so when I updated I noticed the issue. I'll add a comment there.

**Comment by alerque** [comment]
Shouldn't this be gated behind the profiling build profile and not part of anything in the release profile even with `--all-features`?

**Comment by fredizzimo** [comment]
I don't think som but I'm rather new to rust so I might get it wrong.

Profiles are as far as I know meant for specifying build options like optimisation levels and so on https://doc.rust-lang.org/cargo/reference/profiles.html.

The features description matches much better what we are doing https://doc.rust-lang.org/cargo/reference/features.html. We want to conditionally add profiling functionality to Neovide, which is compiled and used only when profiling. Even the name makes more sense, to say for example: "enable the profiling features of Neovide", make much more sense than "enable the profiling build profile of Neovide"

Technically it does not seem to even be possible to use profiles for this. For example it's not possible to add additional dependencies like `tracy-client-sys` for example, which is only needed when profiling is enabled. I don't see anything regarding conditional compilation either, and a quick search returns this https://users.rust-lang.org/t/conditional-compilation-for-debug-release/1098, which would be limited to only detecting debug builds and nothing else.

Furthermore IMO profiling feature is orthogonal to the build profile. You might want to profile debug builds for example. Or maybe include the debug symbols, and profile the `profile` build profile, which was also added in the same MR. That build profile is basically release with debug symbols.  Since tracy captures the call stacks at each context switch, those debug symbols might come handy.
