### ISSUE TITLE
Incorrect multigrid colors with telescope.

### ISSUE THREAD

**Issue by A-Lamia** [neovide/neovide#1937]
@fredizzimo 
can you confirm or not if this is an issue with neovide ?
sorry if this was not the best way to get confirmation.

https://github.com/nvim-telescope/telescope.nvim/issues/2603

**Comment by fredizzimo** [comment]
I should get a notification if you mention me in another issue, even in different repositories, so that's probably a better way of contacting me, providing I see the GitHub notification of course. 

Anyway, I'm closing this, since at least for now it looks like it's not a Neovide issue. We can re-open if more information comes up that change things.
