### ISSUE TITLE
Auto fit content size when resizing the window

### ISSUE THREAD

**Issue by starwing** [neovide/neovide#1956]
I'm using gVim on Windows for years, now in Windows I have switched to neovim only in shell. Because *ALL* gui of neovim doesn't follow gVim's behaviour when I resize the window. 

When I use gVim, the resize behavior likes below:
![gVim](https://github.com/neovide/neovide/assets/114483/6fae28c5-f5dd-4083-8b86-8d74a6e421e5)

But all NeoVim GUI's behavior just like this:
![Neovide](https://github.com/neovide/neovide/assets/114483/69a1d10b-0e6f-4df6-a358-5e97a7183772)

So, is it possible to makes Neovide matches gVim's behavior? In that way, the window is exactly fitting its content, no extra blank edges.

**Comment by MultisampledNight** [comment]
Hi, thanks for the request! I think it'd be cool to have, too.

Looking at the documentation of the windowing library we use, winit, [it's only supported on macOS for now](https://docs.rs/winit/0.29.0-beta.0/winit/window/struct.Window.html#method.set_resize_increments). So while we could implement this immediately, it wouldn't have any effect on any other platforms than macOS, for which we'd need to open an issue/directly send a PR to winit.

Implementing this should be relatively easy, I believe. Since the grid size changes only on change of the `guifont` setting, it'd make sense to call [`Window::set_resize_increments`](https://docs.rs/winit/0.29.0-beta.0/winit/window/struct.Window.html#method.set_resize_increments) after changing and loading the font, and [`WindowBuilder::with_resize_increments`](https://docs.rs/winit/0.29.0-beta.0/winit/window/struct.WindowBuilder.html#method.with_resize_increments) on startup while building the window.

**Comment by Kethku** [comment]
I'm inclined to say that we wont implement this. Even if we add the auto resize increments, it plays extremely poorly with window managers by adding a strange gap between windows when it doesn't perfectly line up. As mentioned in #620 there are multiple reasons not to do this. So I'm marking this as wont fix
