### ISSUE TITLE
fallback to neovim in a tty

### ISSUE THREAD

**Issue by theotheroracle** [neovide/neovide#1963]
**Is your feature request related to a problem? Please describe.**
i would like to be able to set neovide as my default $VISUAL eiditor, but some console applications, such as sudoedit, some fish functions, git commit, will try to use the visual editor even if not in a graphical environment, which causes them to fail .

**Describe the solution you'd like**
if neovide detects it's not in a visual environment, one way to test might be $XDG_SESSION_TYPE != tty, then it would fallback to neovim as a console application, perhaps with a warning or something .

**Describe alternatives you've considered**
setting some script that tries to do this as the default editor, but i'd imagine this would conflict quite a bit with some applications that are expecting an executable file

**Comment by fredizzimo** [comment]
I suggest that you create a simple shell script that does the check and launches the correct application. Alternatively set `$VISUAL` conditionally in your `.profile`

**Comment by MultisampledNight** [comment]
Fwiw, (simplified) Linux doesn't really care about what a file really is to execute it, as long as a loader exists for it and its `x` permission bit is set (respectively for the user executing the file). In the case of scripts, the interpreter can be set using a [shebang](https://en.wikipedia.org/wiki/Shebang_(Unix)), which already suffices for it being executable just like a real binary (in most cases).

For example, this was the script I used to use a while ago to conditionally run Neovide or NeoVim in a TUI depending on terminal and battery status (which isn't your usecase, since you'd need to check if the argument is something like `COMMIT_EDITMSG` instead, but it might help as orientation):

```python
#!/usr/bin/env python
import os
import shlex
import subprocess
import sys


FORCE_IGNORE_DISCHARGING = False


def edit(args: list[str]):
    if os.environ["TERM"] == "linux":
        subprocess.run(["nvim"] + args)
    elif (
        not FORCE_IGNORE_DISCHARGING
        and "discharging"
        in subprocess.run(
            ["/usr/bin/env", "acpi"], stdout=subprocess.PIPE, text=True
        ).stdout.lower()
    ):
        subprocess.run(["term", "--command", "nvim"] + args)
    else:
        # either charging or system has no battery
        subprocess.run(["zsh", "-lic", shlex.join(["neovide"] + args)])


if __name__ == "__main__":
    edit(sys.argv[1:])
```

Closing as most likely Neovide itself cannot offer a solution satisfying all cases where Neovim in TUI mode could be preferred instead. As for taking input on stdin which is also a common usage for `$VISUAL`, that'd be in https://github.com/neovide/neovide/issues/1865.
