### ISSUE TITLE
Not loading when opened on arch

### ISSUE THREAD

**Issue by SchlexanderOlz** [neovide/neovide#2007]
**Describe the bug**
I tried running neovide on arch linux, directly after downloading it with pacman, but it wouldn't start. After running it with --log and --nofork it printed `Neovide panicked with the message 'Library libxkbcommon-x11.so could not be loaded.'. (File: /build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/xkbcommon-dl-0.4.1/src/x11.rs; Line: 59, Column: 28)`. Fixed by installing libxkbcommon-x11 with `pacman -S libxkbcommon-x11`

**To Reproduce**
1. Install neovide with `pacman -S neovide`
2. Run neovide

**Expected behavior**
The application should start normally

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Neovide Version 0.11.1
 - Neovim Version 0.9.1

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
TRACE [neovide] Neovide version: 0.11.1

**Additional context**
Fixed

**Comment by MultisampledNight** [comment]
Hi, thanks for reporting! I'll add it to the installation section on the website, but I believe it could also be useful to list `libxkbcommon-x11` as an optional dependency required for running on X11 directly in the package.

@alerque could you possibly add that to the `neovide` package? Are you fine with being pinged from an issue like this? I'm not exactly sure how much sense that makes from a packaging perspective, so your input would be greatly appreciated.

**Comment by fredizzimo** [comment]
@alerque. If you are not reading this, I will open an issue in the Arch issue tracker. But since it's already discussed here, I will continue here for now. 

I also noticed that the make dependencies are wrong. we don't use gtk3 and SDL, and I don't think Python is a build dependency either. I don't have time to do it now, but I can check the actual dependencies with a chroot build.

Also note that the aur git version needs the same changes, once we have figured out what to do.

**Comment by alerque** [comment]
Pinging here is fine, I just happen to be on the road.

I'll add the optdepends for X11 and check out makedepends as well.

**Comment by alerque** [comment]
Done. A bit weak sauce on the commit message but the new build is in the repos.

**Comment by fredizzimo** [comment]
Thank you. I think we can close this issue now.
