### ISSUE TITLE
Missing features that would be awesome

### ISSUE THREAD

**Issue by Swanncastel** [neovide/neovide#2043]
Hi folks,

**Is your feature request related to a problem? Please describe.**
I don't really have a problem using Neovide, I think its a very good GUI but I missed some features and I still use Terminal for my day to day work.

For example :
- Notification, I'm using nvim-notify but this kind of feature would be much better implemented by a GUI as a GUI is responsible for style and animation.
- Command prompt and popupmenu, noice.nvim is trying to implement it with neovim and floating window but a GUI would be nicer
- Markdown preview because I would love to have a markdown preview without opening a browser
- MiniMap, there are many minimap nvim plugins out there but a GUI implementation would be nice, goneovim is doing it but last time I tried, it was buggy.

**Describe the solution you'd like**
Of course I don't expect those features to be implemented with this issue, I'm just wondering if there is any roadmap about neovide evolution, If so it would be cool to add those features.

**Comment by Swanncastel** [comment]
Hi there, I just want to know if my question is relevant or is this feature request out of neovide scope.
Thanks

**Comment by fredizzimo** [comment]
For the first two, I'm not sure if we can do better than noice without a quite big effort. Except for maybe system notification integration, but I feel that even that could just be a simple RPC call that plugins like noice could implement. 

I'm not opposed to the idea, but we need either a very clear design that is suitable for everyone and can be implemented easily, or to just provide the very basics(an API), that some some external plugin uses and allows customisation). Noice is a quite huge plugin, and we would need a comparable amount of code to make something as flexible, and I don't thin including something like that would be good for the codebase and the maintainability.

There's also the problem that if we try to do something, we need to make sure we can turn it off, since otherwise it conflicts with noice.

Markdown preview, rendering pictures and variable size fonts are all things that we have been discussing, and probably will implement in some form or another in the future. But I don't think we can expect it to happen very soon. We don't have a huge development team, and there are still many core features that needs to be fixed. 

That said, I will probably rather soon experiment with integrating the servo web engine, if everything goes well (which probably won't happen), then we might have a very simple way of displaying basic webpages. This could then be coupled with a lua/external plugin for the actual markdown rendering. But that's still far away even if it can render webpages, since we probably need some api, and more control before it's usable.

For the minimap, unfortunately I don't think we can do much better than the various minimap plugins out there. Neovim does not really expose all the information we need to do that, so we need to work with them first to define what we need. I don't think it's out of scope for Neovide, but it's also not something someone is working actively on at the moment. 

As for the roadmap, the development is mostly relying on what individual contributors want, so if someone wants to implement for example a minimap now, then we won't stop it (unless it makes the code way harder to maintain), like if we were going to attempt to make a copy/paste version of noice.

**Comment by Swanncastel** [comment]
Hi @fredizzimo, thanks for the answer, very clear, I hope the neovide team will grow because It is a very nice GUI for neovim 👌

**Comment by fredizzimo** [comment]
I will close this since it's a meta issue that is hard to track. For most of the requests we already have existing issues, but otherwise, feel free to open a new issue for each feature separately.
