### ISSUE TITLE
ERROR: NEOVIM_BIN was not found.

### ISSUE THREAD

**Issue by LamprosPitsillos** [neovide/neovide#2060]
**Describe the bug**
Neovide reports an error that NEOVIM_BIN has not been found , but the path shown
is valid.
```
ERROR: NEOVIM_BIN='/usr/bin/env nvim' was not found.
```
```
$ /usr/bin/env nvim    
Successfully launches nvim
```

**To Reproduce**
Start neovide as normal `$ neovide`

**Expected behavior**
Neovide to start

**Desktop (please complete the following information):**
 - OS: NixOS 23.11.20230925.6500b45 (Tapir) x86_64
 - neovide 0.11.2
 - Neovim Version
    ```    
    NVIM v0.10.0-dev-e46f5aa
    Build type: Release
    LuaJIT 2.1.1693350652
    Run "nvim -V1 -v" for more info
    ```

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
```
❯ neovide --log
ERROR: NEOVIM_BIN='/usr/bin/env nvim' was not found.
```

**Comment by MultisampledNight** [comment]
Hi, thanks for reporting!

The issue here is that `NEOVIM_BIN` is treated _in full_ like a path, and since paths can contain spaces, it's part of it, too. There's no shell splitting performed. However, since we have `shlex` in the dep tree already, this would be easy to fix.

By the way, for this specific case of finding `nvim` on `$PATH`: That's the default behavior if `NEOVIM_BIN` is unset. So `env -u NEOVIM_BIN neovide` or plain `neovide` with `NEOVIM_BIN` not set should work.

**Comment by rhysd** [comment]
I'll try to fix this.
