### ISSUE TITLE
Not respecting existing line break types

### ISSUE THREAD

**Issue by rytc** [neovide/neovide#2065]
**Describe the bug**
On Windows: when after editing a file and then viewing the diff in Git, new lines or edited lines will get have clrf line endings when the rest of the file is lf (`^M` is visible in git diff). I have `set ff=unix` in my init.vim and I haven't seen this happen when using neovim-qt. I end up having to do `setlocal ff=unix` which updates all the line endings and ruins the diff because every line is modified. My git config is also set to replace clrf to lf

This doesn't seem to happen consistently 

**To Reproduce**
On windows, edit a file then view changes with git diff. It doesn't happen consistently so it might require trying with different files.

**Expected behavior**
Shouldn't insert `^M` line endings when the rest of the file is LF

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Neovide Version 0.11.2
 - Neovim Version 0.9.1

**Comment by fredizzimo** [comment]
I don't think this is a Neovide bug, it's more likely that the neovim line ending detection that fails.  Can you try to reproduce this in the neovim terminal? 

The autodetection process is described here https://neovim.io/doc/user/options.html#'fileformats' Based on that and the symptoms you see, the cause is probably that your file is stored in Git with Windows line endings, even if you have linux endings locally. Perhaps some leftover before you added the `crlf` conversion option?

**Comment by Kethku** [comment]
I agree this is very unlikely to be a nvim bug. Closing for lack of response
