### ISSUE TITLE
Did 0.11.2 release get re-tagged?

### ISSUE THREAD

**Issue by chenrui333** [neovide/neovide#2139]
👋 while regression testing rust 1.74.0, we found the checksum got changed, raise this issue to confirm if there was any re-tagging happened. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/154804

**Comment by fredizzimo** [comment]
No, it did not. It’s still pointing  to the same commit as it was when it was released as can be seen by the ci run https://github.com/neovide/neovide/actions/runs/6123376830 and the tag https://github.com/neovide/neovide/releases/tag/0.11.2

Note that the has might change in the future though https://github.blog/2023-02-21-update-on-the-future-stability-of-source-code-archives-and-hashes/

**Comment by ZhongRuoyu** [comment]
Thanks @fredizzimo. Yes, we're aware of the instability of GitHub's source code archives; it brought us much trouble at that time.

We recently went through a change in Homebrew/homebrew-core#152092 to change all the GitHub source code archive URLs to the form of `archive/refs/tags/<tag-name>.tar.gz`, for better clarity. Most of the URLs before the change were in the form of `archive/<tag-name>.tar.gz` (so the contents in the tarball would be identical after the change). But for `neovide`, it was actually `archive/tags/0.11.2.tar.gz` (with a `/tags` component in between), and as it turned out, the checksum of the following tarballs are different:
- https://github.com/neovide/neovide/archive/tags/0.11.2.tar.gz
- https://github.com/neovide/neovide/archive/refs/tags/0.11.2.tar.gz

The contents of the first tarball are in the `neovide-tags-0.11.2/` directory, while those of the latter are in `neovide-0.11.2/`.

Thanks for confirming this quickly; we'll proceed to correct the checksum.

**Comment by fredizzimo** [comment]
Thanks for the explanation.
