### ISSUE TITLE
Neovide pollutes filesystem with `neovide_backtraces.log` files

### ISSUE THREAD

**Issue by baltermia** [neovide/neovide#2145]
**Describe the bug**
As described in the title, opening Neovide anywhere on my M1 MBP creates a neovide_backtraces.log file.

**To Reproduce**
1. Open any file in neovide
2. Close it again `:qa!`

**Expected behavior**
I thought this should only be generated with `--log` enabled.

**Screenshots**

**Desktop (please complete the following information):**
 - MacBook M1 Pro
 - OS: macOS 14.0
 - Neovide Version 0.11.2
 - Neovim Version v0.9.4

**I'll leave the contents of the `neovide_backtraces.log` file:**

> 2023-11-25 10:35:49 - Neovide panicked with the message 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }'. (File: src/settings/window_size.rs; Line: 92, Column: 41)
>    0: __mh_execute_header
>    1: __mh_execute_header
>    2: __mh_execute_header
>    3: __mh_execute_header
>    4: __mh_execute_header
>    5: __mh_execute_header
>    6: __mh_execute_header
>    7: __mh_execute_header
>    8: __mh_execute_header
>    9: __mh_execute_header
>   10: __mh_execute_header
>   11: __mh_execute_header
>   12: __mh_execute_header
>   13: __mh_execute_header
>   14: <unknown>
>   15: <unknown>
>   16: <unknown>
>   17: <unknown>
>   18: <unknown>
>   19: <unknown>
>   20: <unknown>
>   21: <unknown>
>   22: <unknown>
>   23: <unknown>
>   24: __mh_execute_header
>   25: __mh_execute_header
>   26: __mh_execute_header
>   27: __mh_execute_header
>   28: __mh_execute_header
>   29: __mh_execute_header
>

**Comment by fredizzimo** [comment]
It looks like you have launched Neovide as root at some point and the file `~/.local/share/nvim/neovide-settings.json` is read-only. So you need to either delete that file or change the permissions using sudo.

That's said, I'm leaving the issue open, because we need to fix two things.
1. The backtraces log should be written to a single location, probably `~/.local/share/neovide/neovide_bracktraces.log` instead of in the current working directory.
2. We should not change any file permissions when launched as root.

**Comment by baltermia** [comment]
Hi @fredizzimo, thank you so much, this resolved the issue.
