### ISSUE TITLE
Random freezes with toggleterm

### ISSUE THREAD

**Issue by Maneren** [neovide/neovide#2166]
**Describe the bug**
Neovide randomly freezes, when toggleterm is open. The only way to close it is to terminate it or the nvim process. 

The task manager shows neovide using 60-100% of the CPU core, zsh from toggleterm using 100% (either no program running inside or one that isn't currently interacting with the shell), and nvim process also around 100% and also continuously eating more and more RAM. (see the attached screenshot)

**To Reproduce**
This is the worst about it, it happens quite randomly. The only common denominators in all the cases it happened were: 

- neovide (no issue in plain nvim)
- using it for an hour or more
- toggleterm open in floating mode with more than one screen of output
- either keypress or mouseclick anywhere in the neovide window, after having another program in focus, but could have been already frozen before that, hard to tell

And it's like once in day (multiple hours of use) and on one PC and not on another one with the same lua config (but not the same versions of stuff).

**Expected behavior**
No freezes :)

**Screenshots**
![image](https://github.com/neovide/neovide/assets/49210777/3148383a-9fdf-46a5-abdd-a8ccc8d7b5eb)

**Desktop:**
- Neovide 0.11.2
- OS: 6.6.4-2-MANJARO  x86_64 GNU/Linux

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
`neovide-backtrace.log` that appears in the directory after the neovide process (or the nvim inside) is terminated
```txt
2023-12-04 18:48:57 - Neovide panicked with the message 'Mouse Input Failed: DecodeError(ReaderError(Custom { kind: UnexpectedEof, error: "EOF" }), "nvim_input_mouse")'. (File: src/bridge/ui_commands.rs; Line: 71, Column: 18)
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
```
I am not sure, but the timestamp feels like it was some time before the freeze (the shell shows I opened the btop to kill it at 19:03), but I hadn't noticed any other issue before it happened and it is quite consistent among all the freezes, so it's probably related.

Yeah, I know it's not a lot of info and I'd be happy to provide more or help in any other way with debugging. (I will try running it always with --log from now on to catch the next freeze). I really enjoy neovide but this is kinda annoying.

**Comment by fredizzimo** [comment]
This will be very hard to track down, I'm personally using the built in terminal constantly, but not through toggleterm, I use vim-floaterm. But I have never seen any freezes like that.

I also think the stacktrace is a secondary symptom, Neovim crashed or was killed which causes the mouse input events to not go through.

Are you using Neovim nightly or 0.9.4? It's possible that there's some recent regression in the nightly version, I'm not testing that very much.

**Comment by Maneren** [comment]
I am using 0.9.4.

And damn, this time it happened again much much faster than usual, it must have known I submitted this! :)

Also this time I got a slightly different backtrace, but this time the timestamp is an hour ago, so looks like it's unrelated.

```txt
2023-12-04 21:11:35 - Neovide panicked with the message 'Focus Gained Failed: DecodeError(ReaderError(Custom { kind: UnexpectedEof, error: "EOF" }), "nvim_command")'. (File: src/bridge/ui_commands.rs; Line: 153, Column: 18)
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>

2023-12-04 21:11:35 - Neovide panicked with the message 'Focus Lost Failed: DecodeError(ReaderError(Custom { kind: UnexpectedEof, error: "EOF" }), "nvim_command")'. (File: src/bridge/ui_commands.rs; Line: 149, Column: 18)
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
```

One more thing I noticed is that when I kill just the zsh process, neovide stops using the CPU, but nvim continues. No idea if that is of any help, but it's interesting.

Where do I find the log file from `--log`?

**Comment by fredizzimo** [comment]
The log file should be in the working directory where you started neovide from.

I have a strong suspicion that the underlying cause is the same as
* https://github.com/neovide/neovide/issues/2003. 

Not necessary anything to do with the clipboard, but how Neovim handles the pipes after https://github.com/neovim/neovim/commit/1d16bba4d8b8b648d2dabd610924bcf3051a0f29. I don't fully understand that commit, especially
```c
dup2(STDERR_FILENO, STDOUT_FILENO);
dup2(STDERR_FILENO, STDIN_FILENO);
```
Which will make both stdout and stdin go to stderr, especially the stdin part feels very strange. I think the intent would be to close the original STDOUT and STDIN instead, at least the STDIN. But I don't think that's necessarily the problem

I think that the commit also makes any errors from internal processes that  are started to by nvim to be forwarded to STDERR
```c
uvproc->uvstdio[2].data.fd = STDERR_FILENO;
```

And because we, through `nvim-rs` might not be reading from stderr, which would explain why it hangs after a while when the buffers get full. 

Actually I think that might also explain the hangs @sid-6581  saw here, since if the stderr is not empty, the process will most likely not completely exit.
* https://github.com/neovide/neovide/pull/2130

Would it be possible for you to test with a commit earlier than that, or perhaps Neovim 0.9.3?

**Comment by fredizzimo** [comment]
I'm not sure if the points are relevant. For the first, I think the stderr channel is used only for internal nvim processes like various clipboards, or stuff you launch from the neovim commandline. The second point might be relevant though. 

Which got me thinking, there's also another clipboard bug, that could have show the same symptoms. But I think the bug is fixed in KDE Plasma, and there should also be a fix on the Neovim side. It involves copying from XWayland applications and closing them.
* https://github.com/neovim/neovim/issues/24470

**Comment by sid-6581** [comment]
I also use the terminal constantly, with toggleterm, but I can't remember ever noticing any freezes on Windows 11. I don't use the system clipboard as my default clipboard, but maybe this is a platform specific issue.

I'd suggest that if you can, make a debug build of neovide and either run it in the debugger or attach the debugger when it freezes. The logs may not be enough to go on in cases like this.

**Comment by sid-6581** [comment]
FWIW, with the latest neovide and the latest neovim nightly, I haven't had a single hang in a while even without my patch from the PR above (that I closed.)

**Comment by Maneren** [comment]
I tried using nvim 0.9.3 and neovide built from main (b637426) for the last week and so far I haven't encountered any issues (similar or any other) whatsoever. So I think I can quite surely rule out the randomness and say, that it indeed works just fine.

**Comment by sid-6581** [comment]
> The log file should be in the working directory where you started neovide from.
> 
> I have a strong suspicion that the underlying cause is the same as
> 
> * [Neovide doesn't close until after clipboard has been changed externally #2003](https://github.com/neovide/neovide/issues/2003).
> 
> Not necessary anything to do with the clipboard, but how Neovim handles the pipes after [neovim/neovim@1d16bba](https://github.com/neovim/neovim/commit/1d16bba4d8b8b648d2dabd610924bcf3051a0f29). I don't fully understand that commit, especially
> 
> ```c
> dup2(STDERR_FILENO, STDOUT_FILENO);
> dup2(STDERR_FILENO, STDIN_FILENO);
> ```
> 
> Which will make both stdout and stdin go to stderr, especially the stdin part feels very strange. I think the intent would be to close the original STDOUT and STDIN instead, at least the STDIN. But I don't think that's necessarily the problem
> 
> I think that the commit also makes any errors from internal processes that are started to by nvim to be forwarded to STDERR
> 
> ```c
> uvproc->uvstdio[2].data.fd = STDERR_FILENO;
> ```
> 
> And because we, through `nvim-rs` might not be reading from stderr, which would explain why it hangs after a while when the buffers get full.
> 
> Actually I think that might also explain the hangs @sid-6581 saw here, since if the stderr is not empty, the process will most likely not completely exit.
> 
> * [fix: don't wait forever for missing nvim process #2130](https://github.com/neovide/neovide/pull/2130)
> 
> Would it be possible for you to test with a commit earlier than that, or perhaps Neovim 0.9.3?

I tried `.stderr(Stdio::null())` to try to prevent not reading stderr from hanging anything, just in case that would solve my hanging issue when quitting, but that ended up not making a difference for that particular hang.

**Comment by Maneren** [comment]
Small update: It was fine with Neovim 0.9.3, but since I switched to 0.10 nightly to try out the native inlay hints and stuff, it came back, together with the freeze-on-exit issue. The only new observation is that it appears that it isn't tied strictly to toggleterm - it usually happens when using/closing it, but not always. Also, it doesn't happen as often as earlier but that may be just a random measurement variation.

I also tried running the debugger, but I couldn't find anything obvious. It looks like it still runs the event/draw loop and such, but the GUI just doesn't actually respond to anything. There may be something more to look for but idk the codebase.

**Comment by fredizzimo** [comment]
@Maneren, how fresh is your nightly build? If it's older than 3 days, it might be worth updating, because I made one fix to Neovim itself, that could explain some of these problems.
* https://github.com/neovim/neovim/pull/27348

**Comment by Maneren** [comment]
Oh, great. Around a week old. I'll try to update it and see if it helps.

**Comment by Maneren** [comment]
Well, it definitely helped, I haven't seen a freeze since I updated. Whatever it was, it probably fixed both this and the freeze-on-exit issue for me, so great job. Thank you

Re @sid-6581: (sorry, I missed your comment)
Yes, the nvim process was still present, when it froze with toggleterm. I also encountered the same exit freeze as you mentioned and in those cases, the process was indeed already gone. So it was a different issue, although apparently solved by the same fix.

**Comment by axelhj** [comment]
I just downloaded and built Neovim from scratch in search for a fix for this problem. Until today I was on 0.9.5 stable. I run ToggleTerm with three open terminals side-by-side in splits and this causes Neovide to freeze roughly once per day. It never happened in Nvy so it must be something related to GUI interactions but somehow specific to Neovide.

CPU runs high for nvim.exe when it is frozen and I cannot close Neovide from Alt+F4 or by closing the window. It occupies more or less a full CPU-core even on `v0.10.0-dev-41fb98d` (latest master on Windows 11, I build with GCC/Mingw) during the freeze. Strangely it starts eating memory, growing at a rate of something like 30 MB each second. After a few minutes it has occupied something like 40GB or virtual memory. So the issue is still around. I would attach logs but I didn't figure out how to enable those yet. I will try at some point attaching a debugger and see if that would give something.

**Comment by Maneren** [comment]
Since the original issue is fixed for me and I haven't run into the freeze for a month, I‌ am closing this. Thanks again

**Comment by axelhj** [comment]
I didn't see it either after turning off most Treesitter features
