### ISSUE TITLE
If dragging, there should be a window details recorded

### ISSUE THREAD

**Issue by 9mm** [neovide/neovide#2175]
**Describe the bug**

I'm not quite sure what the bug is, as I got this crash report while opening a large file (may have hit another key on accident). I have no idea what I did to cause it.

Another comment had some ideas on how to reproduce but I don't know any windows that involve mouse interactions, or even "hidden windows", but I'm open to try and reproduce with some actual commands, if someone wants to put exact steps

https://github.com/neovide/neovide/pull/2167#issuecomment-1851578744

**Desktop (please complete the following information):**
 - OS: 14.1.2 (23B92)
 - Neovide Version NVIM v0.9.4
 - Neovim Version Main
 - 
[neovide_backtraces.log](https://github.com/neovide/neovide/files/13648723/neovide_backtraces.log)

**Comment by AThePeanut4** [comment]
I've just run into the same crash, and I've (eventually) managed to figure out consistent reproduction steps (on Linux). This might not be exactly be what happened to cause your crash, but it's giving me the same "If dragging, there should be a window details recorded" panic message.

1. Most importantly, do not move the mouse _at all_ during the entire procedure. It's probably easiest to open Neovide using a keyboard shortcut directly or through something like `drun`, or from a terminal. The cursor does need to be positioned where the Neovide window will actually appear though.
2. Open Neovide.
3. Click and hold the right mouse button, and then move the mouse.
4. Neovide should then crash immediately, and a "If dragging, there should be a window details recorded" panic message should be added to `neovide_backtraces.log`.

I should also note that after this crash, the `neovide --no-fork` process and its child `nvim` process remain running, even though the window disappears. If I run it from a terminal with `neovide --no-fork` and cause the panic, I get the panic message printed, but the process doesn't actually exit.

I've also come across a different, but likely related, crash. This one doesn't add a backtrace at all, but if you run it through a terminal with `--no-fork` then it prints a stack overflow error message before `SIGABRT`ing.
1. Run Neovide from a terminal using `neovide --no-fork`.
2. Move the mouse (otherwise the next step won't show a context menu at all, presumably related to the above issue).
3. Right click somewhere (not hold) to show the Paste/Select All/etc context menu.
4. Move the mouse to inside the context menu, then click and hold the right mouse button.
6. At this point, the context menu should "teleport" to the top left corner of the screen.
7. While still holding the right mouse button, move the mouse.
8. It should now crash, and print a stack overflow error message. I get `thread '<unknown>' has overflowed its stack` and `fatal runtime error: stack overflow`.

I'm able to cause both these crashes on the latest main (b637426) and on #2167 as well.

**Comment by 9mm** [comment]
Ahhhhh now that you mention it, i do feel like i recall it freezing with the [paste] right click menu open. Good thinking

**Comment by fredizzimo** [comment]
I'm busy with trying to make the rendering even smoother, so I won't look into this for a while.

But if someone wants to fix this one, then I think just ignoring the error should be enough. The second one might need more investigation though, and there might even be some Neovim bug involved since the context menu teleports to another location.

**Comment by fredizzimo** [comment]
Edit, I forgot to say, that ignoring the errors should be enough, since it seems to be totally normal situation that the window can disappear when holding the mouse.

**Comment by Kethku** [comment]
I've been digging into this and although we can ignore the missing drag info, for some reason we appear to get into a state where the anchor grid id for the context window is set to the context window itself which results in the stack overflow. I'm still investigating why we get into that weird state though so its gonna be a bit longer

**Comment by Kethku** [comment]
Sure enough. Trying to open a context menu inside the context menu causes nvim to set the anchor for the context menu grid to itself which causes us problems
```
TRACE [neovide::channel_utils] neovim_handler WindowFloatPosition { grid: 6, anchor: NorthWest, anchor_grid: 6, anchor_row: 2.0, anchor_column: 2.0, focusable: false, sort_order: Some(250) }
```

**Comment by fredizzimo** [comment]
Strange, I guess that should be reported to Neovim.

But maybe just ignoring the anchor, if it points to itself works as a workaround.

**Comment by Kethku** [comment]
Weirdly we still stack overflow after ignoring the anchor. Still investigating

**Comment by Kethku** [comment]
Created an upstream issue here: https://github.com/neovim/neovim/issues/26973

**Comment by fredizzimo** [comment]
I think theree are two different issues here as reported in the second message and the fix is just for the second one (the stack overflow), at least I can't see how it would fix the first issue, but I might be wrong.

**Comment by fredizzimo** [comment]
This was not fully fixed yet, so re-opening. 

The other part of the fix, for the first  crash with the "If dragging, there should be a window details recorded" message is here:
* #2311
