### ISSUE TITLE
neovide --version creates a window instead of just returning

### ISSUE THREAD

**Issue by edi9999** [neovide/neovide#2204]
```
#!/usr/bin/env bash

set -euo pipefail

source /usr/bin/env_parallel.bash

install_one() {
	vim --version
	neovide --version
}
env_parallel install_one <<<"foo"
```

With following script, 

vim --version responds with its version (9.0 on my computer), but neovide --version does'nt respond in the terminal, instead, it opens up a new window.

It does that only when run inside "env_parallel", it works ok if I just run install_one.

**Comment by fredizzimo** [comment]
In order to ensure that errors and output is always displayed we now always display a GUI windows if a terminal is not detected.

We didn't consider scripting usage, but maybe we should, and also detect piped output.

**Comment by edi9999** [comment]
How can I tell neovide that it is indeed in a terminal ?

Maybe simply setting an environment variable ??

Setting TERM=something should probably be a good way ??

**Comment by edi9999** [comment]
In my term , I have TERM=screen-256color

**Comment by fredizzimo** [comment]
On the Neovide side, we use this https://github.com/neovide/neovide/blob/af9869bd6d8d3434b187e29f85032ee74e40b536/src/error_handling.rs#L104

I  think checking for `TERM`, instead of that would indeed be a good fix in this case, at least on Linux, since that would handle all the cases where it's started from a terminal, even when the stdout is piped. And probably still show the GUI when launched in other ways. 

But there might still be some edge cases that works wrong.

**Comment by edi9999** [comment]
Would people really run `neovide --version` from outside of a terminal ??

How would they run it ?
