### ISSUE TITLE
Output of system("tmux -V") replace tmux word with neovide.Appimage

### ISSUE THREAD

**Issue by einhander** [neovide/neovide#2209]
**Describe the bug**
Output of `system("tmux -V")` gives `neovide.Appimage <tmux version>` e.g.
```
neovide.Appimage 3.3a
```
nvim 
```
tmux 3.3a
```

**To Reproduce**
1. `echo system("tmux -V")`

**Expected behavior**`
Output should be:
```
tmux 3.3a
```

**Screenshots**

**Desktop (please complete the following information):**
 - Debian testing
 - neovide.appimage 0.11.2

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

```
TRACE [neovide] Neovide version: 0.11.2
DEBUG [neovide::bridge::command] Starting neovim with: Command { std: "/usr/bin/nvim" "--embed" "-p", kill_on_drop: false }
```

**Comment by fredizzimo** [comment]
I’m pretty sure this is a tmux bug that was fixed by https://github.com/tmux/tmux/commit/9f605178c375b3722408c241a93f6d18090eead1

But the fix seems to be unreleased.

There’s probably another bug involved too, how `getprogname` gets resolved. Either some appimage bug, or something in their implementation https://github.com/tmux/tmux/blob/master/compat/getprogname.c

I doubt we can do anything inside Neovide to fix it.

I’ll leave the bug open for a while, in case someone has another idea.

**Comment by fredizzimo** [comment]
Closing this, since it's not really a Neovide bug
