### ISSUE TITLE
Seg fault when exiting with --no-fork (not really critical)

### ISSUE THREAD

**Issue by DADA30000** [neovide/neovide#2223]
**Describe the bug**
When exiting with --no-fork, there is seg fault message

**To Reproduce**
1. Open neovide with --no-fork
2. Exit
**Expected behavior**
No seg fault message
**Screenshots**

https://github.com/neovide/neovide/assets/73874445/1bc4536c-acd7-41bb-ad4b-b9af247dfd1a

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Neovide Version: 0.12.0
 - Neovim Version: 0.9.4

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/13798057/neovide_rCURRENT.log)

**Additional context**
I think it happened after some update, because I don't remember that happening before

**Comment by fredizzimo** [comment]
Yes, there`s a known exit crash when using some wlroots based compositors.

Alacritty had the same issue https://github.com/alacritty/alacritty/issues/7146

And the fix is also known, we need to do something similar to this https://github.com/alacritty/alacritty/pull/7220/files#diff-c32f38542d52895124f53e3425f4243a05391d1d2bd8640f371ac6e427be5d70R1594-R1610
