### ISSUE TITLE
Crash on Windows 11 with WSL2 and Ubuntu 22.04 when using Neovide with --wsl flag

### ISSUE THREAD

**Issue by SuzumiyaAsahi** [neovide/neovide#2229]
Environment:

Operating System: Windows 11
Subsystem: WSL2
Distro: Ubuntu 22.04
Neovim Version: 0.9.4
Neovide Version: 0.12.0
Issue Description:
I am experiencing a consistent crash when trying to run Neovide on Windows 11 with the --wsl flag to connect to Neovim running on Ubuntu 22.04 via WSL2.

Steps to Reproduce:

Start WSL2 running Ubuntu 22.04.
Ensure Neovim is installed and running within WSL2.
On Windows 11, attempt to start Neovide with the command neovide --wsl.
Expected Behavior:
Neovide should connect to the Neovim instance running in WSL2 and operate normally without crashing.

Actual Behavior:
Upon running the neovide --wsl command, Neovide crashes after a few time with the following error message:

cargo run -- --wsl
    Finished dev [unoptimized + debuginfo] target(s) in 0.46s
     Running `target\debug\neovide.exe --wsl`
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
fatal runtime error: I/O error: operation failed to complete synchronously
error: process didn't exit successfully: `target\debug\neovide.exe --wsl` (exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)

Additional Tests Performed:
I have also followed the recommendations in the documentation regarding the sRGB support flags (--no-srgb, --srgb, and the NEOVIDE_SRGB environment variable). However, these attempts did not resolve the issue, and the error persists.

sRGB Flag Tests:

With --srgb Flag:
Command: cargo run -- --srgb --wsl
Result:

Finished dev [unoptimized + debuginfo] target(s) in 0.45s
Running `target\debug\neovide.exe --srgb --wsl`
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
fatal runtime error: I/O error: operation failed to complete synchronously
error: process didn't exit successfully: `target\debug\neovide.exe --srgb --wsl` (exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)
With --no-srgb Flag:
Command: cargo run -- --no-srgb --wsl
Result:

Finished dev [unoptimized + debuginfo] target(s) in 0.44s
Running `target\debug\neovide.exe --no-srgb --wsl`
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
fatal runtime error: I/O error: operation failed to complete synchronously
error: process didn't exit successfully: `target\debug\neovide.exe --no-srgb --wsl` (exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)
Despite trying both the --srgb and --no-srgb flags, the application crashes with the same error message in each case. This suggests that the issue may not be related to the sRGB settings.

**Comment by SuzumiyaAsahi** [comment]
```lua
if vim.g.neovide then
  vim.g.neovide_padding_top = 0
  vim.g.neovide_padding_bottom = 0
  vim.g.neovide_padding_right = 0
  vim.g.neovide_padding_left = 0

  vim.g.neovide_transparency = 0.9
  vim.o.background = "light"
  vim.g.neovide_cursor_vfx_mode = "sonicboom"
  vim.g.neovide_scale_factor = 1.0
  vim.g.neovide_hide_mouse_when_typing = true
  vim.g.neovide_remember_window_size = true
  local change_scale_factor = function(delta)
    vim.g.neovide_scale_factor = vim.g.neovide_scale_factor * delta
  end
  vim.keymap.set("n", "<C-=>", function()
    change_scale_factor(1.1)
  end)
  vim.keymap.set("n", "<C-->", function()
    change_scale_factor(1 / 1.1)
  end)
end
```

This is my nvim configuration

**Comment by fredizzimo** [comment]
The only place we are using png is for reading the icon, which should be embedded in the executable.

It looks like you are building the executable yourself, since you are running a debug build instead of release, I which I assume is just for debugging the problem. Have you tried the exe from our releases download? I think the most likely reason for this problem is an issue with your build environment, maybe you could try updating Visual Studio, since the rust compiler is dependent on that.

**Comment by SuzumiyaAsahi** [comment]
I downloaded the source code for testing because the exe file I downloaded directly crashed during the connection with WSL, but I couldn't see the reason for the crash. My Rust level is very poor, please forgive me.
I am using Virtual Studio Installer, which has been updated to the latest version
Visual Studio Community 2022 Preview has been upgraded to 17.9.0 Preview 2.0, but it still experiences flickering after running for a period of time (or it can be said that the screen scrolls for a period of time).
After updating Virtual Studio, I still experienced a crash when using the downloaded exe, and then I started compiling the source code and executing it, but the crash still occurred.

```bash
cargo run --release -- --wsl
    Finished release [optimized] target(s) in 0.46s
     Running `target\release\neovide.exe --wsl`
error: process didn't exit successfully: `target\release\neovide.exe --wsl` (exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)
```

**Comment by fredizzimo** [comment]
Hm ok, then it’s probably not the development environment. Although I’m not sure that it has been tested with the 17.9 preview yet.

I’m not sure what the problem is, but could you try commenting out these two line

https://github.com/neovide/neovide/blob/af9869bd6d8d3434b187e29f85032ee74e40b536/src/window/mod.rs#L122

https://github.com/neovide/neovide/blob/af9869bd6d8d3434b187e29f85032ee74e40b536/src/window/mod.rs#L144

Since, I think it’s the icon loading that fails for some reason.

**Comment by SuzumiyaAsahi** [comment]
Unfortunately, when I commented out the code you asked me to comment on, I ran the code again, but still encountered an error message. The error message was the same as before, maybe I didn't have the luck to enjoy Neovid (laughs). The nimble cursor jump of Neovid reminded me of the joy of buying iPhone 5 back then.
I guess it's probably an error in the source code that caused the stack overflow issue, but of course, this is just my guess. I didn't read the source code (laughs)

```bash
   Compiling csscolorparser v0.6.2
   Compiling copypasta v0.8.2
   Compiling dirs v5.0.1
   Compiling itertools v0.10.5
   Compiling spin_sleep v1.1.1
   Compiling simple_moving_average v0.1.2
   Compiling xdg v2.5.2
   Compiling skia-safe v0.68.0
    Finished release [optimized] target(s) in 1m 38s
     Running `target\release\neovide.exe --wsl`
error: process didn't exit successfully: `target\release\neovide.exe --wsl` (exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)
```

I am also curious about what to do when encountering a crash problem where the error location is not visible? A curiosity from a rookie.

**Comment by SuzumiyaAsahi** [comment]
This is really hard to understand. I tested Neotide on my Ubantu, but surprisingly there were no issues.

**Comment by SuzumiyaAsahi** [comment]
This is really hard to understand. I tested Neovide on my Ubantu, but there was no problem.

**Comment by fredizzimo** [comment]
You can first check if you have a neovide_backtraces.log file and attach it here
Otherwise set the environment variable
`RUST_BACKTRACE=1` and run the debug buidl with `—no-fork` , `cargo run  — —no-fork`. If that does not work you need a debugger. I usually use Visual Studio code for that, but I think the Neovide DAP protocol could be used.

For Visual Studio code, you can use the following launch configuation `.vscode/launch.json` and this https://marketplace.visualstudio.com/items?itemName=vadimcn.vscode-lldb

```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "lldb",
            "request": "launch",
            "args": [”—wsl”],
            "cargo": {
                "args": ["build"]
            }
        },
    ]
}
```

**Comment by SuzumiyaAsahi** [comment]
What I later adopted was to run Neovide directly under wsl2. This time it was fine and there were no problems. Let’s leave it like this for now (laughs).

**Comment by SuzumiyaAsahi** [comment]
Thank you for spending your precious personal time answering my questions. Thank you. I hope you will also give me advice in the future.

**Comment by fredizzimo** [comment]
@SuzumiyaAsahi, thanks, would it be possible for you to test with `RUST_BACKTRACE=1` and debug mode to see if you get a backtrace, or if you already have a `neovide_backtraces.log` file created. It would be great to know the cause so that it can be fixed. Many other people probably also have the same problem.

**Comment by fredizzimo** [comment]
I think this should be fixed by the D3D support, which was added in Neovide 0.13.0
