### ISSUE TITLE
Error in init.lua freezes Neovide

### ISSUE THREAD

**Issue by comiluv** [neovide/neovide#2233]
**Describe the bug**
Any lua error in init.lua freezes Neovide window, that is the Neovide window becomes unresponsive for keyboard and mouse inputs and has to be terminated by Windows task manager.

**To Reproduce**
1. insert `asset(false)` in top of init.lua
2. run Neovide
3. See error

**Expected behavior**
Neovide prints error messages and then continue without freezing

**Screenshots**
<img width="765" alt="화면 캡처 2024-01-03 061027" src="https://github.com/neovide/neovide/assets/19642705/c907ae52-3d3d-4666-85ca-30b7d3ded996">

**Desktop (please complete the following information):**
 - OS: Windows 11 (10.0.22631)
 - Neovide Version 0.12.0
 - Neovim Version 0.9.5

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/13813959/neovide_rCURRENT.log)

**Additional context**
Initially I noticed this when changing settings for some plugins, and found out freezing can be reproduced consistently with minimal setup `assert(false)`
Running nvim in Windows terminal with identical setup doesn't crash or freeze Neovim

**Comment by fredizzimo** [comment]
I think both of these are caused by the same issue
* https://github.com/neovide/neovide/issues/2231
* https://github.com/neovide/neovide/issues/2225

 But I'm leaving all open for now, since there's a small chance that they are not.

The cause seems to be this line
https://github.com/neovide/neovide/blob/af9869bd6d8d3434b187e29f85032ee74e40b536/src/bridge/ui_commands.rs#L59

From
* https://github.com/neovide/neovide/pull/2161

Which hangs when an error message is displaying, changing that to an api call might fix the issue. If not we need to move it to somewhere where it can't fail, before the init is processed.

**Comment by genzj** [comment]
Confirmed @fredizzimo 's theory -- after removing the mentioned command call, my problem with missing font (#2225) disappeared.

**Comment by genzj** [comment]
Created a PR which solved the problem on my side, but not sure if it's of the right mental model to fix this issue. Any comments will be appreciated.
