### ISSUE TITLE
config.toml setting for specifying fallback fonts

### ISSUE THREAD

**Issue by comiluv** [neovide/neovide#2240]
**Is your feature request related to a problem? Please describe.**
Neovide previously enabled users to set up fallback fonts for CJK characters, emojis, etc. within the `init.lua` file under `vim.o.guifont`. This was achieved by specifying fallback fonts after the default fonts. For instance, an example setup would be `vim.o.guifont = "consolas, Noto_Color_Emoji:h11"`, indicating a fallback to the Noto Color Emoji font for character sets not available in Consolas.
However, with the release of Neovide 0.12.1, users now have the ability to configure fonts and font features in the `config.toml` file. While this enhancement is a great addition to Neovide, it currently lacks the capability for users to establish fallback fonts to accommodate diverse requirements.

**Describe the solution you'd like**
Add an option to specify a fallback font in config.toml file

**Describe alternatives you've considered**
I think support for fallback fonts in config.toml would be best for symmetry

**Comment by TwIStOy** [comment]
You can also specify fallback fonts in `config.toml`. Like,

```toml
[font]
normal = [ "Symbols Nerd Font Mono", "FiraCode" ]
```

Sorry for the document of this feature is not clear.

**Comment by TwIStOy** [comment]
Ah, It's an issue about parsing these configurations. Please try #2244. It seems work now!

**Comment by BatmanAoD** [comment]
It seems that even in `config.toml`, fallback is "noisy" as described in this issue: https://github.com/neovide/neovide/issues/2533

Is that intentional? I use the same vim/neovide config across all my machines, and don't necessarily have my preferred fonts set up on all of them, and my preferred pre-installed font depends on the OS. So the "silent fallback" behavior was very convenient for me.
