### ISSUE TITLE
Neovide not forking since 0.12.0 on Windows

### ISSUE THREAD

**Issue by SpacewaIker** [neovide/neovide#2270]
**Describe the bug**
Neovide doesn't seem to fork, no matter if I use the `--fork` argument or set `NEOVIDE_FORK=1`. So when I open a file from the terminal, the shell doesn't "return" and I cannot execute other commands.

**To Reproduce**
1. Open a file on the command line, e.g. `neovide myfile.txt`
2. Return to the terminal emulator

**Expected behavior**
The terminal should "return" such that I can execute other commands in the same shell window.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Neovide Version 0.12.1
 - Neovim Version 0.9.4

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/13929208/neovide_rCURRENT.log)

**Additional context**
I also tried version 0.12.0 and it behaves in the same way. Version 0.11.2 however behaves as expected.

**Comment by fredizzimo** [comment]
If you are using scoop, this is a duplicate of 
* https://github.com/neovide/neovide/issues/2250

But there is a behaviour change in 0.12, which explains the difference
Neovide on Windows has always been a gui application that never really attach to a console, but we launched a new process when `--fork` was specified anyway, the same way as on other platforms. Neovide 0.12 longer does that, since it's totally unecessary with the regular executable.

But scoop has a wrapper that somehow forces Neovide to act like a console application. It should autodetect, but it does not seem to do that, so it's a scoop bug.

**Comment by SpacewaIker** [comment]
I am using scoop so that must be the issue!
