### ISSUE TITLE
Direnv Support

### ISSUE THREAD

**Issue by xyven1** [neovide/neovide#2281]
**Is your feature request related to a problem? Please describe.**
When opening a directory with neovide, or `cd`ing from inside neovim, direnv is not working.

**Describe the solution you'd like**
Direnv should function when opening neovide or changing directories.

**Describe alternatives you've considered**
Current work around is to open the directory in the terminal first, loading the direnv, and then running `neovide .`

**Additional context**

**Comment by fredizzimo** [comment]
This feature request should be asked in the Neovim, or perhaps even Vim repositories, since there's nothing Neovide can do to control this behaviour, we just send the input to Neovim and renders what it tells us to. 

But they will probably refuse to implement it as well, since it can be implemented through a plugin like this:
https://github.com/direnv/direnv.vim

**Comment by xyven1** [comment]
Ah, ok. Thanks
