### ISSUE TITLE
On MacOS, Neovide window moves up after each relaunch

### ISSUE THREAD

**Issue by carlmueller** [neovide/neovide#2303]
**Describe the bug**
On MacOS, the Neovide window opens at a slightly higher position after each relaunch.

**To Reproduce**
1. Launch Neovide, quit, relaunch
2. After each relaunch, the Neovide window is slightly above its previous position.

**Expected behavior**
The Neovide window should be at the same position after relaunch.

**Desktop (please complete the following information):**
 - macOS Sonoma 14.3
 - Neovide Version 0.12.1
 - Neovim Version 0.9.5

**Comment by claudiusraphael** [comment]
Confirmed. On one of two identical iMacs running MacOS Sonoma 14.3 I observed the same behavior. Checked on the other and it was not present.

Turns out when using NeoVim 0.9.4 with Neovide 0.12.1 on macOS Sonoma 14.3 the "moving up" of the window doesn't happen. To be sure, I updated Neovim and the "moving up" happens there as well. Downgrade to Neovim 0.9.4 fixes it.

The "moving-up"-distance is equivalent to the height of the title-bar, btw and only the vertical/y-axis is affected.

**Comment by carlmueller** [comment]
One more thing:  this behavior occurs when you quit using ZZ.  If you quit using Command-Q then the next window is at the same position.

**Comment by falcucci** [comment]
thank you everyone! could you share some video/gif?

I am not able to reproduce on macOS Sonoma.

does it occurs with Stage Manager enabled/disabled?

**Comment by carlmueller** [comment]
I'm attaching shots, before and after relaunching

<img width="2240" alt="Before" src="https://github.com/neovide/neovide/assets/67909756/6c9c54a0-2047-4b66-851a-e8b78b78ba42">

<img width="2240" alt="After" src="https://github.com/neovide/neovide/assets/67909756/252c8e4f-3d63-4972-844c-a887c63617c5">

**Comment by carlmueller** [comment]
It happens regardless of whether Stage Manager is enabled or not.

**Comment by falcucci** [comment]
thanks for you support @carlmueller

**Comment by crupest** [comment]
@falcucci The reason you can't reproduce might be how you exit neovide.

> One more thing: this behavior occurs when you quit using ZZ. If you quit using Command-Q then the next window is at the same position.

According to what @carlmueller reported, this bug is only triggered on some specific situations. For me, `CTRL+C` in terminal (this is the common way for me to debug neovide) does not trigger this bug. But `:q` does.

Here is the screen record,

https://github.com/neovide/neovide/assets/15831781/f91ebbf5-bd70-481a-aa4e-34440a60c41a

**Comment by falcucci** [comment]
I indeed did as described, but if is fixed that's what matters.
