### ISSUE TITLE
Neovide throws error on startup if a font is missing as of 0.12

### ISSUE THREAD

**Issue by rawlingsr** [neovide/neovide#2328]
**Summary**
If you pass a list of fallback fonts to guifont, then all fonts you pass in have to be present on the system, defeating the purpose of supplying a list of fonts.

**Steps to reproduce**
1. Make a fresh neovim config, moving your existing one out of the way for a minute.
2. Populate a fresh init.vim file with the following contents, or replace Fira_Code with a font neovide finds without issue, and Monaco with a font you haven't installed
```
set guifont=Fira_Code,Monaco:h10
```
3. Launch Neovide.
4. Notice that An error appears regarding Monaco even though it wouldn't even be rendered, due to the first font being your first choice.

**Expected behavior**
as per the [neovim docs](https://neovim.io/doc/user/options.html#'guifont'):

- When one font is passed in, you can expect an error message when it's not found.
- When a list of fonts is passed in, the first valid option is used.

**System Information**
 - OS: Arch Linux and Windows 11
 - Neovide Version 0.12.0+
 - Neovim Version 0.9.5

**`neovide --log` output**
The output is too long for github, apparently. Provide a place for me to post it if it's needed.

**Additional information**
I originally submitted this bug report stating that there was a hard locking issue, but as far as I can tell, that issue has been already been resolved.

**Comment by fredizzimo** [comment]
Did you try Neovide 0.12.2? The issue should be fixed in that.

**Comment by rawlingsr** [comment]
I'm on the latest version as far as I know.
```
$ neovide --version
neovide 0.12.2
```
I retried the minimum config with init.vim replaced by init.lua, and got the same behavior. I now plan to slowly add stuff from my real config file until the hard locking behavior comes back.

**Comment by rawlingsr** [comment]
So, it looks like I had a newer version of neovide on linux than on windows, and the hardlocking issue is indeed fixed as of 12.2. I am sorry for failing to check the versions and other factors earlier.

I'll go back and edit the description to match the behavior as of 12.2.

**Comment by rawlingsr** [comment]
I've updated the description to reference the relevant part of the neovim docs.

**Comment by fredizzimo** [comment]
The error is expected, but the error message could be less technical.

Even if the primary font is loaded, the fallback font might get used when the font does not have all the glyphs. Typical use cases is a fallback font supporting for example asian language, or a fallback font with just the nerd fonts icons.

So, we want to show an error to the user if that fails to load as well, for example due to a typo. If we wait until it's actually tried, then you would get the error at some probably inconvenient tiem when scrolling down, or even typing.

Neovide does not quite use the standard definition of guifont https://neovim.io/doc/user/options.html#'guifont', instead we use this https://neovide.dev/configuration.html#font. But even then, I think it's up to debate if the error message should show for all fonts in the list or not, "the first valid font", could also mean the first valid font for the given character.

**Comment by rawlingsr** [comment]
Personally, I found the output to be fine. As of right now, it reflects exactly what the attempted settings were, which is what you want when writing your own config files, as the average neovide user would.

**Comment by BlueDrink9** [comment]
Personally, I'd like to see this reopened. I found this change incredibly annoying. I use a list of fonts because different systems I use have different fonts available, or different names for them. There is no way to know in config if a font is installed ahead of trying to load it, as far as I'm aware.

If neovide is going to deviate from standard vim behaviour by doing this, it should at least be skippable, e.g.

```vim
try
	set gfn=garbagemissingfont
catch
endtry
```

**Comment by fredizzimo** [comment]
> I have a similar situation to @BlueDrink9. I share the same set of configs across different machines, with different distro/OS. They can have quite different installed fonts (and sometimes different names for the same font).

That's one of the reasons why changed the preferred way of configuring the fonts is in the [config.toml](https://neovide.dev/config-file.html), which can be platform specific, and runs on the same machine as Neovide, so it works correctly even when you connect to remote instances.

**Comment by Snowflyt** [comment]
You can check whether fonts are installed from your Shell and keep only installed ones. For example:

```lua
---@type string[]
local fonts = {
  -- Nerd fonts
  "JetBrainsMono Nerd Font",
  "FiraCode Nerd Font",
  "CaskaydiaCove Nerd Font",
  "Hack Nerd Font",
  "Meslo Nerd Font",
  "DejaVuSansMono Nerd Font",
  "NotoSansMono Nerd Font",
  -- Fallback regular monospaced fonts
  "Maple Mono",
  "JetBrains Mono",
  "Fira Code",
  "Cascadia Code",
  "Hack",
  -- Fallback system-default monospaced fonts
  "Menlo",
  "Monaco",
  "DejaVu Sans Mono",
  "Noto Sans Mono",
  "Consolas",
}

-- Remove fonts that are not installed
---@type string[]
local installed_fonts
if vim.fn.has "unix" == 1 then
  installed_fonts = vim.split(
    vim.fn.system "fc-list | sed 's/.*:\\s*\\([^:]*\\):.*/\\1/' | tr ',' '\\n' | sed 's/^[ \\t]*//;s/[ \\t]*$//' | sort | uniq",
    "\n"
  )
elseif vim.fn.has "win32" == 1 then
  installed_fonts = vim.split(
    vim.fn.system [[powershell -c '
      [System.Reflection.Assembly]::LoadWithPartialName("System.Drawing") | Out-Null
(New-Object System.Drawing.Text.InstalledFontCollection).Families.Name
    ']],
    "\n"
  )
end
if installed_fonts then
  fonts = vim.tbl_filter(function(font)
    return vim.tbl_contains(installed_fonts, font)
  end, fonts)
end

vim.opt.guifont = table.concat(fonts, ",") .. ":h14"
```

**Comment by BlueDrink9** [comment]
Note for the above: the powershell didn't work with mine. It just printed the input command. I had to swap the quotes. Also, out-null wasn't recognised as a command.
```lua
installed_fonts = vim.split(
  vim.fn.system [[powershell -Command "[System.Reflection.Assembly]::LoadWithPartialName('System.Drawing'); (New-Object System.Drawing.Text.InstalledFontCollection).Families.Name"]],
  "\n"
)
```
