### ISSUE TITLE
Commandline flags (--x11-wm-class, --x11-wm-class-instance, and --wayland_app_id) doesn't work

### ISSUE THREAD

**Issue by Rid1FZ** [neovide/neovide#2329]
**Describe the bug**
I was trying to change the wayland app id and x11 class of neovide window by using the command `neovide --x11-wm-class nvim --x11-wm-class-instance nvim --wayland_app_id nvim` and found that it was not working. The wayland app id is still `neovide`.

**To Reproduce**
1. Open terminal
2. Run the command `neovide --x11-wm-class nvim --x11-wm-class-instance nvim --wayland_app_id nvim`
3. Check window class with any tool (like looking glass of gnome)

**Expected behavior**
The wayland app id and x11 window class should have changed to `nvim`

**Desktop (please complete the following information):**
 - OS: Fedora 39 (Workstation Edition)
 - Neovide Version: neovide 0.12.2
 - Neovim Version: NVIM v0.9.5

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/14107198/neovide_rCURRENT.log)

**Additional context**

**Comment by Hubro** [comment]
Damn, I spent way too long trying to figure out what I was doing wrong...

Still broken in `neovide 0.12.2`.

**Comment by fredizzimo** [comment]
Does it work on X11? On Wayland the arguments seem to be swapped here
https://github.com/neovide/neovide/blob/1db63d93b18cc1eb5ac5b3e67b3ca63505f10800/src/window/mod.rs#L193-L200

see
https://docs.rs/winit/0.29.15/winit/platform/wayland/trait.WindowBuilderExtWayland.html.

Could someone swap the order and see if that fixes the issue? I can`t do it myself for a while, because I don't have acess to a computer for a while.
