### ISSUE TITLE
Custom renderer for Tabs/Popups/Statusline

### ISSUE THREAD

**Issue by exoticus** [neovide/neovide#233]
I really like the neovide philosophy of not applying destructive editions over the vanilla vim experience, and to that i wish we should stick. However there're some aspects of vim that could use some love from the opengl renderer. For instance popups can use some customizations such as blur behind, drop-shadows, borders. The status line can use some of that too, like the ability to change its height. And for Tabs customizing their height would be nice too.

I'd like to know your opinion on these suggestions, and if some of them suits the project direction i'll start fiddling around implementing them, ofc with your help

**Comment by Kethku** [comment]
I'm closing this as the majority of the multigrid features outlined are now done. We will still likely want to do window specific font setting, but thats already tracked in issues elsewhere.

In general the current stance we have taken is that we want to enable as much as possible within the realm of things configurable from nvim. So wherever absolutely possible we use affordances from nvim plugins rather than implementing them ourselves as a custom one off.
