### ISSUE TITLE
Cascadia Mono PL font won't load with certain styles

### ISSUE THREAD

**Issue by brphilly** [neovide/neovide#2352]
**Describe the bug**
When starting neovide I get the following error:
`Following fonts couldn't be loaded: FontKey { font_desc: Some(FontDescription { family: "Cascadia Mono PL", style: Some("Bold Italic") }), hinting: Full, edging: AntiAlias }`

My config.toml is:
```toml
[font]
size = 15
normal = ["JetBrains Mono", "Symbols Nerd Font"]
italic = {family = "Cascadia Mono PL", style = "Italic"}
bold_italic = {family = "Cascadia Mono PL", style = "Bold Italic"}
```

Note that the Italic style works fine. I also tried using Bold but that didn't work either.

Running `fc-list | grep 'Cascadia Mono PL'` gives:
```
/usr/share/fonts/TTF/CascadiaMonoPLItalic.ttf: Cascadia Mono PL
/usr/share/fonts/TTF/CascadiaMonoPLItalic.ttf: Cascadia Mono PL:style=Light Italic
/usr/share/fonts/TTF/CascadiaMonoPL.ttf: Cascadia Mono PL:style=ExtraLight
/usr/share/fonts/TTF/CascadiaMonoPLItalic.ttf: Cascadia Mono PL:style=SemiLight Italic
/usr/share/fonts/TTF/CascadiaMonoPLItalic.ttf: Cascadia Mono PL:style=Bold Italic
/usr/share/fonts/TTF/CascadiaMonoPL.ttf: Cascadia Mono PL:style=SemiLight
/usr/share/fonts/TTF/CascadiaMonoPLItalic.ttf: Cascadia Mono PL:style=ExtraLight Italic
/usr/share/fonts/TTF/CascadiaMonoPLItalic.ttf: Cascadia Mono PL:style=Italic
/usr/share/fonts/TTF/CascadiaMonoPL.ttf: Cascadia Mono PL:style=Light
/usr/share/fonts/TTF/CascadiaMonoPL.ttf: Cascadia Mono PL:style=Bold
/usr/share/fonts/TTF/CascadiaMonoPL.ttf: Cascadia Mono PL:style=SemiBold
/usr/share/fonts/TTF/CascadiaMonoPLItalic.ttf: Cascadia Mono PL:style=SemiBold Italic
/usr/share/fonts/TTF/CascadiaMonoPL.ttf: Cascadia Mono PL:style=Regular
/usr/share/fonts/TTF/CascadiaMonoPL.ttf: Cascadia Mono PL
```

It seems that there are multiple styles inside one ttf file but there is a different file for Italic. Maybe this is why Italic works?
These ttf files come from the [ttf-cascadia-code arch linux package](https://archlinux.org/packages/extra/any/ttf-cascadia-code/).

My terminal emulator, kitty, is set to use this font for Bold Italic and it works fine with terminal neovim.

I'm not massively knowledgeable about how fonts work on Linux so feel free to let me know if I'm misunderstanding how this should be configured.

**To Reproduce**
1. Install Cascadia Mono PL from the arch linux package
2. Use `{family = "Cascadia Mono PL", style = "Bold Italic"}` as one of the fonts in the config.toml
3. Start neovide

**Expected behavior**
Neovide starts with no errors and the font works correctly.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Neovide Version: 0.12.2
 - Neovim Version: Latest Nightly

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/14222949/neovide_rCURRENT.log)

**Comment by fredizzimo** [comment]
I can repeat this, and it seems like it's bold that is the problem, not the italic. But I have no idea why, everything seem to be as it should. Specifying custom weights does also not work, well `W500` does but does not really do anything, but `W600` does not.

**Comment by fredizzimo** [comment]
Microsoft Copilot to the rescue! At least to allow debugging a bit further
> The FontConfig property FC_INDEX can indeed appear as a large number, such as 393216. Let’s delve into why this might seem counterintuitive:
>
> Understanding FC_INDEX:
As mentioned earlier, FontConfig uses patterns to represent fonts.
Each pattern contains various properties (such as family, style, and file location).
The FC_INDEX property indicates the index of a specific font within a font family.
Multiple Styles:
Font families often have multiple styles (e.g., regular, bold, italic).
Each style corresponds to a different index.
For instance:
Index 0 might represent the regular style.
Index 1 could be the bold style.
Index 2 might correspond to the italic style.
Why Large Numbers?:
The seemingly high number like 393216 arises due to the way FontConfig combines indices.
It uses a bitmask approach to represent multiple styles simultaneously.
Each bit in the number corresponds to a specific style.
For example:
If a font supports both bold and italic styles, the index would be a combination of those styles’ indices.
In binary, 393216 is 1100000000000000000, indicating that it supports the bold and italic styles (but not the regular style).
Bitwise Representation:
To understand the styles represented by a large index, convert it to binary.
In this case, 393216 in binary is 1100000000000000000.
The 1st and 2nd bits (from the right) correspond to bold and italic, respectively.
Practical Example:
Suppose a font family has three styles: regular, bold, and italic.
Their indices are 0, 1, and 2.
If a font supports both bold and italic, its combined index would be 1 + 2 = 3.
In binary, 3 is 11, which aligns with the 393216 representation.
Remember that while these large indices might seem unusual, they efficiently encode multiple style information within a single number. 📜🔤

It seems like Swash does not really deal with this properly.

**Comment by fredizzimo** [comment]
No, don't trust the AI, the explanation is nonsense. Indices bigger than 65536 are special, and we need to handle both of these variations as special cases in Neovide https://gitlab.freedesktop.org/fontconfig/fontconfig/-/blob/a76b95105ca26c600279b2daf4bd43b37a918823/src/fcfreetype.c#L1290-L1378

But, I still can't find any documentation about that

**Comment by fredizzimo** [comment]
It looks like it's the same as `FACE_INDEX` of freetype https://freetype.org/freetype2/docs/reference/ft2-face_creation.html#ft_facerec

I'm just writing the information here so I remember later in case I don't proceed to fox it yet, or if someone else want to attempt.

**Comment by fredizzimo** [comment]
This should fix the issue:
* https://github.com/neovide/neovide/pull/2354

Note: I found another bug during testing, the screen is not updated when the new font settings are loaded, you need to manually run `:redraw`.
