### ISSUE TITLE
Not read `PATH` on windows when lanuched from icon?

### ISSUE THREAD

**Issue by jinzhongjia** [neovide/neovide#2362]
**Describe the bug**
I tried setting up `pwsh` as my shell in neovide, and then `:echo executable("pwsh")` is 0

**Expected behavior**
When I lanuch neovide from windows terminal, it can find `pwsh`.

But when I lanuch neovide form icon, it can not find `pwsh`, this behavior is a bit weird. Neovide does not read the system's PATH and pass it to neovim?

**Desktop (please complete the following information):**
 - OS: `windows 11 22H2`
 - Neovide Version `0.12.2`
 - Neovim Version `NVIM v0.10.0-dev-2384+g848fc8ede`

**Comment by jinzhongjia** [comment]
But `vim-floaterm` and `toggleterm` can work normally with `pwsh` when lanuched from icon.

**Comment by fredizzimo** [comment]
I assume that you are not using `--wsl`, since you didn't mention it.

If you open a standard Windows `cmd` command prompt, can that find `pwsh`? What's the path there with if you type `set path` ? The reason why I'm asking to check this in a standard command prompt is that powershell has a profile that might add other variables, and that's not read when starting Neovide. It will only find paths defined in either the global or profile environment variables defined in the environment variables control panel settings.

**Comment by jinzhongjia** [comment]
Yes, I not use wsl
When I use `cmd` or `pwsh` to launch neovide, it can find pwsh, and `set path` will print environment variable, and my pwsh is installed by miscrosoft store
But pwsh's path is defined in the profile environment variables defined in the environment variables control panel settings

![image](https://github.com/neovide/neovide/assets/41784264/53c44c4e-73a3-4889-82be-56056ddd78cd)

**Comment by jinzhongjia** [comment]
This is a screenshot of PATH in the profile environment variable

**Comment by jinzhongjia** [comment]
This is `cmd` output:
```sh
$ C:\Users\jinzh>set path
Path=C:\ProgramData\scoop\shims;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\Docker\Docker\resources\bin;C:\Users\jinzh\scoop\apps\nodejs\current\bin;C:\Users\jinzh\scoop\apps\nodejs\current;C:\Users\jinzh\scoop\apps\python\current\Scripts;C:\Users\jinzh\scoop\apps\python\current;C:\Users\jinzh\go\bin;C:\Users\jinzh\scoop\apps\qemu\current;C:\Users\jinzh\.nimble\bin;C:\Users\jinzh\scoop\apps\gcc\current\bin;C:\Users\jinzh\scoop\apps\llvm\current\bin;C:\Users\jinzh\scoop\apps\pyenv\current\pyenv-win\bin;C:\Users\jinzh\scoop\apps\pyenv\current\pyenv-win\shims;C:\Users\jinzh\scoop\apps\rustup\current\.cargo\bin;C:\Users\jinzh\scoop\apps\yarn\current\global\node_modules\.bin;C:\Users\jinzh\scoop\apps\yarn\current\bin;C:\Users\jinzh\scoop\shims;C:\Users\jinzh\AppData\Local\Microsoft\WindowsApps;C:\Users\jinzh\AppData\Local\JetBrains\Toolbox\scripts;C:\Users\jinzh\AppData\Local\GitHubDesktop\bin;C:\Users\jinzh\AppData\Local\Microsoft\WinGet\Packages\Rufus.Rufus_Microsoft.Winget.Source_8wekyb3d8bbwe
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
```

the path `C:\Users\jinzh\AppData\Local\Microsoft\WinGet\Packages\Rufus.Rufus_Microsoft.Winget.Source_8wekyb3d8bbwe` is the location of `pwsh`

**Comment by fredizzimo** [comment]
The Windows store executables are a bit strange, they contain some kind of link to the actual application, and I suspect Neovim is not properly following that link. Or maybe it's not using `PATHEXT` correctly, and it has some other extension. It needs some more investigation to tell exactly what's wrong though.

But you have two options:
1 Uninstall the windows store version, and install it some other way https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.4
2. Find out the real path, the directory of the `$PSHOME`, and add that before `WindowsApps`, you could perhaps even do this from your Neovim init scripts, since you can modify and read environment variables there.

**Comment by jinzhongjia** [comment]
You are right. The size of all files under WindowsApps is 0 bytes. It seems that Windows has done something similar to a soft link.
Presumably neovim can't use it correctly
I decided to reinstall pwsh
OMG, why does the Microsoft Store have to use such weird content?
thx for your help

**Comment by jinzhongjia** [comment]
I use winget reinstall `pwsh`, now everything works well.

**Comment by fredizzimo** [comment]
More information here
* https://github.com/neovim/neovim/issues/27747

**Comment by jinzhongjia** [comment]
oh, thx
