### ISSUE TITLE
Keyboard layout is not used on Xorg

### ISSUE THREAD

**Issue by PatrickMassot** [neovide/neovide#2393]
**Describe the bug**

Neovide does not use the keyboard layout that all other application use.

**To Reproduce**

On a Linux machine usign Xorg with a non-american qwerty layout, open a file and try to type text in input mode. I don’t mean fancy text, simply text, maybe with some non-american accents.

**Expected behavior**

Text should appear in the same way they appear in terminal or web browser, the same physical key presses should produce the same letter.

**Screenshots**

In this gif below I’m pressing the same keys in both windows (one dead key and then a letter key). The terminal is printing the expected é letter, the one that also shows up in FireFox, in ThunderBird, in Gimp, everywhere. Neovide is printing a completely random ẅ.

![neovide_bug](https://github.com/neovide/neovide/assets/14060883/73f76dcd-6301-40e9-af80-32171240cb14)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Neovide Version 0.12.2
 - Neovim Version 0.9.5

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/14466436/neovide_rCURRENT.log)

Note the above log indeed suggests neovide is under the impression that it’s the responsibility of a text editor to interpret key presses. This looks weird to me, but I’m still grateful for all the work that went into this project. I hope I’ll be able to use it one day (but of course this bug currently makes it impossible).

**Comment by fredizzimo** [comment]
We are just reporting the keypresses further to Neovim as they are given to us by the Winit library. So, the bug is very likely there. 

I know that different keyboard layouts, both without and with IME has worked previously, and that includes dead keys, so there's either something strange going on with your machine, or it has been broken recently, I don't remember when I tested X11 the last time, so it's possible that the latest release doesn't work, although I think we would have other reports if that was the case.

But before we report a bug to Winit, there are two things to test:
1. First we should update to the latest version, do you think you can build from source and change the Winit version to `0.29.12` in Cargo.toml? Especially these changes seem like they could be releated:
   > On X11, don't require XIM to run.
On X11, fix xkb state not being updated correctly sometimes leading to wrong input.
3. Second it would be great if you could try the Alacritty terminal v0.13.1, which uses one version older winit than we do, but all the keyboard related changes should be the same.

**Comment by PatrickMassot** [comment]
Thanks a lot for you lightning fast answer! I can confirm both that 
* updating the winit version and compiling neovide fixes the bug
* alacritty v0.13.1 has the exact same bug.

**Comment by fredizzimo** [comment]
This will be fixed by:
* https://github.com/neovide/neovide/pull/2443
