### ISSUE TITLE
Font too thin in light background compared to chrome

### ISSUE THREAD

**Issue by xzbdmw** [neovide/neovide#2398]
**To Reproduce**
1. open a html file in chrome
[a.html.zip](https://github.com/neovide/neovide/files/14481618/a.html.zip)

2. set the same (jetbrains mono, font size 30) in neovide, and open the html file in neovide
3. see the font bold difference

**Expected behavior**
they should be the same

**Screenshots**
above is neovide, below is chrome, you can see neovide is thiner
<img width="765" alt="截屏2024-03-04 20 47 04" src="https://github.com/neovide/neovide/assets/97848247/971e4142-d955-476e-8741-93f3eff83df6">

I tested in intellij idea and vscode and found intellij render font silimlar to neovide(thiner) and vscode is similar to chrome(bolder), maybe not an issue just different rendering method
**Desktop (please complete the following information):**
 - OS: macos 14.2
 - Neovide Version 0.12.2
 - Neovim Version 0.10

**Comment by xzbdmw** [comment]
I want to know is it possible make font looks like chrome:)

**Comment by fredizzimo** [comment]
We usually get reports that the fonts are too bold, so in that sense this bug report is strange.

But I can repeat this on Linux as well, and the different alias options does not fix it. It's a bit puzzling, since we use Skia for font rendering, the same library as Chrome uses, so it should look the same. 

So, it's most likely a gamma issue, but I'm not sure what we need to do to fix, maybe switch to srgb rendering. This is most likely related:
https://skia.org/docs/dev/design/raster_tragedy/, and the document linked from it https://blog.johnnovak.net/2016/09/21/what-every-coder-should-know-about-gamma/

**Comment by xzbdmw** [comment]
I also found neovide font weight 500(jb mono) is almost identical to kitty font weight 400 in light background, they mention gamma in text-composition document too. And kitty can specify a number to adjust that gamma.

**Comment by xzbdmw** [comment]
What's the roles of skia_safe::Font and swash used as paird? Who decide the final looks?

**Comment by xzbdmw** [comment]
some information https://github.com/kovidgoyal/kitty/pull/5423#issuecomment-1322240023

**Comment by fredizzimo** [comment]
This should allow it to be configured the same:
* #2510

**Comment by fredizzimo** [comment]
The gamma and contrast options in Neovide 0.13.0 allows for all kinds of adjustments. https://neovide.dev/configuration.html#text-gamma-and-contrast
