### ISSUE TITLE
Neovide occupies a modified buffer on startup

### ISSUE THREAD

**Issue by wilhelmtell** [neovide/neovide#2404]
**Describe the bug**
On starstup, Neovide occupies an extra, modified, buffer. This diverges from Vim's and Neovim's behaviour and breaks scripts.

**To Reproduce**
1. Start Neovide
2. Type `:echo getbufinfo({'bufmodified': 1})`
3. See list with 1 element `[{'lnum': 0, 'bufnr': 2, ...`

**Expected behavior**
Step 3 above should show the empty list `[]`.

**Screenshots**
![neovide_bufmodified_startup](https://github.com/neovide/neovide/assets/1458/4cb9ee3b-3833-4a2c-9b1b-71c71be30f5a)

**Desktop (please complete the following information):**
 - OS: Latest EndeavourOS as of 2024-03-06
 - Neovide Version 0.12.2
 - Neovim Version 0.9.5

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/14514859/neovide_rCURRENT.log)

**Additional context**
The issue started in (bisects into) commit de64b8caaf3944fdc1b67014d04589cc2f5e2416. Can Neovide display the intro text without occupying a new buffer?

**Comment by fredizzimo** [comment]
The buffer is closed when you close the intro message, and you can disable it completely with `set shortmess+=I`, so it should not be a big problem.

It's not easy to draw the message without a buffer, since it needs highlight groups and other stuff, so it's drawn from lua using standard Neovim mechanisms. And that in turn is required because so far Neovim has not provided us with a better alternative.
* https://github.com/neovim/neovim/issues/24705

**Comment by fredizzimo** [comment]
This is now fixed in Neovide 0.13.0, since Neovim 0.10.0 now properly sends the intro message to UI implementation, so we don't need our own hacky workaround anymore.
