### ISSUE TITLE
nvim not found when using neovide --wsl

### ISSUE THREAD

**Issue by rizvi-ha** [neovide/neovide#2409]
nvim not found when using neovide --wsl

0. Be using Windows 11 unfortunately
1. Install neovide 0.12.2 on Windows
2. Install nvim 0.9.5 on your WSL 2 Ubuntu 22.04
3. Try running neovide --wsl from command prompt
4. It crashes.

I've tried everything from previous issue posts, editing my .bashrc, editing my .profile, etc. I don't want to do the TCP method as it is slower.

Here is my log in neovide_rCURRENT:

``
TRACE [neovide] Neovide version: 0.12.2
DEBUG [neovide::bridge::command] Running which command: "wsl" "$SHELL" "-lc" "which nvim"
ERROR [neovide::error_handling] Neovide just crashed :(
This is the error that caused the crash. In case you don't know what to do with this, please feel free to report this on https://github.com/neovide/neovide/issues!
ERROR: nvim not found!
``

I think the command "wsl $SHELL -lc which nvim" is not a valid powershell command? Running this command by itself in powershell gives:

``
Invalid command line argument: -lc
Please use 'wsl.exe --help' to get a list of supported arguments.
``

**Comment by fredizzimo** [comment]
The command it tries to run in powershell syntax is `wsl '$SHELL' -lc 'which nvim'`, note the single quotes. It should work, if the path to nvim is in `.bash_profile`  or `.profile`. Also note that if `.bash_profile` exists, then `.profile` won't be used, so you should use just one of them, I think Ubuntu by default uses only `.profile`

But before that you should make sure that `nvim` work normally inside WSL without neovide, if that does not work, then Neovide won't work either. If it works, then the problem is almost certainly that your path is set in `.bashrc` instead of `.profile`

**Comment by rizvi-ha** [comment]
Hi, thank you for your response.

1.  `wsl '$SHELL' -lc 'which nvim'` (with single quotes like you suggested) gives no error message in Powershell, but gives no output for me. 
2. I do not have a .bash_profile, only a .profile. My .profile is given below in case it helps:
``
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
#umask 022

# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
        . "$HOME/.bashrc"
    fi
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi
. "$HOME/.cargo/env"

PATH="/home/linuxbrew/.linuxbrew/bin/nvim:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:$PATH"
``
3. nvim works completely fine inside of WSL, the only issue is neovide not finding it. My .bashrc does not modify my $PATH variable whatsoever.

Conclusion:
I think this bug may be because I have multiple WSL2 distros on this laptop (Debian, Ubuntu, and one other one I forgot). nvim is only on my Ubuntu distro, and I think perhaps Neovide is searching through one of those other, unused, distros.

**Comment by rizvi-ha** [comment]
I did `wsl --set-default Ubuntu-22.04` and it fixed this error. I am now having a 
'your 131072x1 screen size is bogus. expect trouble' error. But seeing as this is a different
error I will go ahead and close this bug. Thanks for your help

**Comment by fredizzimo** [comment]
The git version of Neovide will ignore that message. So, unless you can track down what cause (it should be some procps tool called from `.profile` or `.bashrc`)

I wrote this before seeing your message:

Your `.profile` look correct, depending on where `nvim` is installed. Except maybe this first path `/home/linuxbrew/.linuxbrew/bin/nvim:`, which possibly points to the executable itself instead of the directory. But it should not really prevent it from working.

Currently Neovide always use the default WSL distro. So, make sure that the one you want to use is the default one. `wsl --set-default`

**Comment by alimulap** [comment]
i don't know if it will help other people, but i had the same issue because my default shell wasn't bash

changed to bash and it works fine

**Comment by fredizzimo** [comment]
It works in other shells as well, as long as the path is configured correctly so that it applies to non-interactive login shells.
