### ISSUE TITLE
Change font size by scrolling mouse middle wheel

### ISSUE THREAD

**Issue by xchray** [neovide/neovide#2410]
I have searched previous issue, I don't see this had been asked. 

Is that OK to ask a feature like Emacs or Web browser to change font size by scrolling middle wheel of mouse? I understood NVIM will not do that because it needs to fit all terminals, I guess as a GUI neovide might be OK. 

Thanks, let me close this if this does not make sense. 
Xin

**Comment by axelhj** [comment]
Hi!

Nvim-qt does this, it is very neat. You need to press ctrl while scrolling though. But unless the new fontsize as set by ctrl+scroll is persisted to config.toml it would not persist on restart (?). Anyway, I would like this feature too. I used it a lot in the QT GUI due to my monitors having different DPI (but due to Qt font rendering I got no benefit from higher DPI and thus prefer Neovide).

**Comment by fredizzimo** [comment]
You can create a keymapping that sets `g:neovide_scale_factor`  for that effect.

https://github.com/neovide/neovide/discussions/2301#discussioncomment-8223201

**Comment by axelhj** [comment]
I just realized I might've misremembered. I was using Nvy for the shortcut. I will try this mapping.
