### ISSUE TITLE
--remote-send for Neovide

### ISSUE THREAD

**Issue by egeesin** [neovide/neovide#2481]
I was looking for a way to summon Neovide instead of nvim to set Godot external editor following [this](https://mb-izzo.github.io/nvim-godot-solution/) guide. Couldn't find a way to replicate same exec options via Neovide's CLI options. (execution options: `--server 127.0.0.1:55432 --remote-send "<C-\><C-N>:n {file}<CR>:call cursor({line},{col})<CR>"`)

Is it possible to implement Neovim's [--remote-send](https://neovim.io/doc/user/remote.html#--remote-send) option or is there any workaround to make this work with existing options?

> Send {keys} to server and exit.  The {keys}
> are not mapped.  Special key names are
> recognized, e.g., "<CR>" results in a CR
> character.

**Comment by egeesin** [comment]
Nevermind, I should've used Neovide as listener client with --listen option, closing...

**Comment by redbeardymcgee** [comment]
I created a nice solution [here](https://www.reddit.com/r/neovim/comments/1c2bhcs/comment/l1q6kx8/). It creates a single instance of of `neovide` with the first file opened. Subsequent files will be opened inside the same instance as a new buffer. If every buffer is closed, or `neovide` is exited otherwise, the `nvim` server socket will be destroyed.

Full disclosure: I'm using the `Steam` version of `Godot`, and a `distrobox` running `fedora-toolbox:40` which contains `neovide` along with its dependencies (`nvim` etc). My `nvim` config is brand new, built with `LazyVim`. This setup appears to work without issues.

`Exec Path: /home/USERNAME/.local/bin/neovide-godot-bridge.sh`
`Exec Flags: {file} {line} {col}`

`/home/USERNAME/.local/bin/neovide-godot-bridge.sh`

```sh
#!/usr/bin/env bash

# CHANGE IF NEEDED:
server_path="$HOME/.cache/nvim/godot-server.pipe"
file=$1
line=$2
col=$3

[[ -e $server_path ]] || neovide "$file" -- --listen "$server_path"

nvim --server "$server_path" \
--remote-send "<C-\><C-N>:n $file<CR>:call cursor($line,$col)<CR>" "${@:4}"
```
**NOTE**: _This syntax is for [LazyVim](lazyvim.org/). It should be easily adaptable to your config, but I cannot help you with it._
`/home/USERNAME/.config/nvim/lua/plugins/godot.lua`

```lua
return {
  {
    "neovim/nvim-lspconfig",
    opts = {
      servers = {
        gdscript = {
          enabled = true,
        },
      },
    },
  },
  {
    "mfussenegger/nvim-dap",
    opts = function()
      local dap = require("dap")
      dap.adapters.godot = {
        type = "server",
        host = "127.0.0.1",
        port = 6006,
      }
      dap.configurations.gdscript = {
        {
          type = "godot",
          request = "launch",
          name = "Launch scene",
          project = "${workspaceFolder}",
          launch_scene = true,
        },
      }
    end,
  },
}
```
