### ISSUE TITLE
Font with fallback shows error when one font isn't found

### ISSUE THREAD

**Issue by yourboirusty** [neovide/neovide#2533]
**Describe the bug**
When Neovide doesn't find one of the fonts in `vim.opt.guifont` it will still print out an error on startup.

**To Reproduce**
1. Set `vim.opt.guifont` to two fonts, one non existent, eg. `"FiraCode Nerd Font Mono,FiraCode NFM:h12"`
2. Open neovide
5. Skip error, notice that at least font size is changing

**Expected behavior**
Neovide silently falls back to another font, without throwing an error.

**Screenshots**
![obraz](https://github.com/neovide/neovide/assets/22943083/dfe7b6ca-f974-4476-89b2-5610fbb1b3f4)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.4 LTS in WSL over Windows 11 Pro Version 10.0.22000 Build 22000 
 - Neovide Version 0.12.2
 - Neovim Version 0.9.5

[Neovide log output](https://github.com/neovide/neovide/files/15272548/neovide_rCURRENT.log)

**Comment by fredizzimo** [comment]
I don't think so, in the past we have got way too many issues where people have made typos in their font names and those are completely pointless, since the users could have figured it out themselves.

Additionally, I can't think of a single valid reason why you have configured a fallback font, and don't want to use it. For machine specific configuration, the config file is the preferred way.

**Comment by yourboirusty** [comment]
Noted, I'll switch to using the config file or work around it in Lua.

**Comment by BatmanAoD** [comment]
@fredizzimo I added a comment [here](https://github.com/neovide/neovide/issues/2240#issuecomment-2116295999) to this effect, but I do actually rely on silent fallback, and it seems like there's no way to get my preferred behavior without a more complex configuration. Would you consider a config option to let users opt-in to the silent-fallback behavior? This would make it easy to debug font selection by opting back out, but also enable the old behavior for people who use it.

**Comment by fredizzimo** [comment]
Your use case is one of the reasons why added the font settings to the `confg.toml` file. https://neovide.dev/config-file.html#runtime-settings

That file is machine specific, so you can have different fonts and font sizes on all your client machines, while using the same main neovim configuration. It's also always loaded from the same host as Neovide, so it's unaffected by any remote settings when you connect to remote Neovim instances.

**Comment by BatmanAoD** [comment]
@fredizzimo I'm not sure how that addresses my use case? What I want is to be able to download my config onto any machine, any OS, and have a reasonable choice of fonts auto-selected, without a warning message about invalid fonts, and without needing to manually tweak the downloaded files. Then, when I do get around to installing my preferred font, I'll automatically get that font instead of the fallback, again without modifying a config file. This is the behavior of `gvim` and of all `neovide` versions before 0.12.

I appreciate the concept of local files for machine-specific config, but that's essentially the opposite of what I want for this feature.

**Comment by BatmanAoD** [comment]
The config-guide describes fallback, but it still shows errors for all fonts in the `config.toml`, even if the first font is valid on the current machine! Is there any chance you'll reconsider and provide a way to do font fallback _without_ an error on startup?

![Image](https://github.com/user-attachments/assets/84bcab40-1232-436b-87a0-b17d099cdd58)
