### ISSUE TITLE
Feature request: Themable titlebar on linux

### ISSUE THREAD

**Issue by BoltsJ** [neovide/neovide#2577]
**Is your feature request related to a problem? Please describe.**
The title bar that shows up on GNOME doesn't respect desktop color scheme setting, and can't be recolored within the editor. 

**Describe the solution you'd like**
A way to specify a foreground and background color for the window decorations. Ideally, it would be something that could be customized to match you colorscheme.

**Describe alternatives you've considered**
Using nvim from the terminal

**Additional context**

![image](https://github.com/neovide/neovide/assets/182554/880f33b1-7e00-4b00-927b-9eb14e2f351a)

**Comment by agraven** [comment]
The titlebar as it exists is not implemented directly neovide, but in winit, the library neovide uses to create its window with. Since GNOME does not implement so called "server side decoration" (and does not seem to want to) applications are forced to draw titlebars themselves, and winit would have to specifically integrate with the gnome desktop to have matching titlebars. If you run neovide in e.g. KDE Plasma you can see that the titlebar matches that of other applications

See also #728 and https://github.com/rust-windowing/winit/issues/2000

**Comment by fredizzimo** [comment]
To further expand a bit on that, winit actually uses another library for that https://github.com/PolyMeilex/sctk-adwaita, so that's where feature requests for the Gnome title bar should go. 

The Neovide developers are not going to be Gnome's puppets and implement client-side decorations in the application itself. The server-side decorations protocol is a Wayland standard that they refuse to acknowledge, which causes a lot of fragmentation and extra work for every application.

**Comment by BoltsJ** [comment]
GNOME isn't required by the wayland spec to provide server side decorations. I don't really care about matching GNOME's xwayland titlebars.  I just want something that can be themed to match my colorscheme. Server side decorations actively prevents that. The kitty titlebar from my screenshot looks nice and can be themed. Neovide isn't a GNOME application, so trying to blend in on GNOME is kind of pointless since it will still look out of place.

**Comment by fredizzimo** [comment]
Kitty is also delegating everything to another library, see this https://github.com/kovidgoyal/kitty/issues/3284

So, again, any improvement requests should go to https://github.com/PolyMeilex/sctk-adwaita, or another library that can be used together with winit. Once that's supported then Neovide can use it.
