### ISSUE TITLE
`$PATH` is modified when launching Neovide from interactive shell

### ISSUE THREAD

**Issue by cpmsmith** [neovide/neovide#2584]
**Describe the bug**
Apologies in advance for an annoying situation 😅. I believe this is caused by the changes in #2405.

#2405 fills in environment variables when Neovide isn't run from a login shell, but when it _is_ run from a login shell in which env variables have been changed, e.g. a Python virtualenv has been activated, it re-runs the default initialization, which can e.g. prevent Pyright from correctly detecting the virtualenv.

**To Reproduce**
Very minimal repro on macOS:
1. In an interactive shell run `PATH="/foobar:$PATH" neovide`
2. In the Neovide process, run the ex command `:echo $PATH`
   - Note that default entries, e.g. `/usr/bin`, are before `/foobar` in the PATH

More real-world scenario:
1. Create a python venv in a given directory, e.g. `python -m venv ./.venv`
2. Activate the venv: `source .venv/bin/activate`
3. Run `neovide`
4. Run ex command `:checkhealth provider.python`
   - Observe in the _Python virtualenv_ section:

         Python virtualenv
         - WARNING $VIRTUAL_ENV is set to: /my-project-directory/.venv
           And its bin directory contains: python, python3, python3.11
           But $PATH yields this python3 executable: /opt/homebrew/opt/python@3.12/bin/python3.12
           And $PATH in subshells yields this python3 executable: /opt/homebrew/opt/python@3.12/bin/python3.12
           And $PATH yields this python3.11 executable: /opt/homebrew/opt/python@3.11/bin/python3.11
           And $PATH in subshells yields this python3.11 executable: /opt/homebrew/opt/python@3.11/bin/python3.11
           So invoking Python may lead to unexpected results.
           - ADVICE:
             - $PATH ambiguities arise if the virtualenv is not properly activated prior to launching Nvim. Close Nvim, activate the virtualenv, check that invoking Python from the command line launches the correct one, then relaunch Nvim.
             - $PATH ambiguities in subshells typically are caused by your shell config overriding the $PATH previously set by the virtualenv. Either prevent them from doing so, or use this workaround: https://vi.stackexchange.com/a/34996

**Expected behavior**
I _think_ that if Neovide is being run from an interactive/login shell, it makes sense not to do all the extra login shell setup, as it will already have been set up by the existing shell. However it's very possible I'm missing something and that would cause problems.

**Desktop:**
 - OS: macOS 14.4.1
 - Neovide Version: v0.13.0
 - Neovim Version: v0.10.0

**Additional context**
For the virtualenv/Pyright case specifically, this can be worked around by running `:PyrightSetPythonPath ./.venv/bin/python`

Strictly speaking I could change my shell configuration to, before modifying the `PATH`, check whether the entries it's going to add are already present, and that would fix this for some cases.

**Comment by fredizzimo** [comment]
Yes, see the discussion here:
https://github.com/neovide/neovide/discussions/2541

**Comment by fredizzimo** [comment]
BTW, I would really appreciate if you could help debug and fix the issue. I don't have a mac myself, so the best I can do is to comment what I think needs to be changed.

**Comment by cpmsmith** [comment]
> Yes, see the discussion here:
> #2541

Ah, I searched existing issues but not discussions. 


> BTW, I would really appreciate if you could help debug and fix the issue. I don't have a mac myself, so the best I can do is to comment what I think needs to be changed.

This did work in v0.12.0 when opening Neovide from a shell, which is why I think that simply inheriting the environment from the shell would work. The things I'm not sure of are:
- Was it actually doing something more complicated than inheriting the environment in v0.12?
- Is it straightforward to check whether Neovide is being run from an interactive/login shell?

**Comment by fredizzimo** [comment]
In 0.12 it checked the `$SHELL` environment variable to detect which shell to launch, then if `$TERM` was not defined it launched the shell with `-l` for a login shell, otherwise just inherited the environment. So in the terminal it just inherited it. This was done here https://github.com/neovide/neovide/blob/71e9fa49fcb393662ee03e42968724b91cde8e62/src/bridge/command.rs#L192-L194

Just launching a login shell is not not enough on macOS when launching from the GUI, so #2405 tries to solve that by running `/bin/login`. But as far as I can see that now happens unconditionally, and therefore you will see duplicate paths. It could do it conditionally based on the `$TERM`, but as I outlined in my message here https://github.com/neovide/neovide/discussions/2541#discussioncomment-9437594, I don't think it's necessary, if we correctly use `exec` to launch a clean environment, like alacritty does. But I don't think that solution has been properly tested yet.

But I realize now that we probably don't want to start a clean login environment when running from the terminal, as then you can't pass custom environment variables to neovim. So the final solution probably still bas to check for $TERM. Note a `is_tty` check is not good enough if you are redirecting th stdio or stdout.

**Comment by bmulholland** [comment]
FWIW this is a critical regression for me: it breaks all my development tooling, so I don't get any linting or formatting or anything. I'll downgrade to 0.12.2 for now.

If it's too complicated to automatically check for path, or if it would enable a faster fix, what about a command flag to toggle this behaviour?

**Comment by fredizzimo** [comment]
I agree that it's a very critical bug, and that's also why I asked for help fixing it. 

I think I have explained what's wrong, and some possible solutions, but we need someone who actually owns a mac to test and implement those fixes. I don't think a hack is needed; the actual fix shouldn't be too complicated.

**Comment by bmulholland** [comment]
Confirming this is fixed in 0.13.1 -- huge thank you to everyone involved.
