### ISSUE TITLE
Neovide will not Fullscreen in Windows

### ISSUE THREAD

**Issue by CoreyTrach** [neovide/neovide#2637]
Using LUA as my config file type.

Running the following in my init.lua file.  I tested some other settings to see if I have my logic correct and other settings are working without issue.

> if vim.g.neovide then
> 	vim.g.neovide_fullscreen = true
> end
> 

Please advise if this is possible to get fullscreen in Neovide for Windows.

**Comment by fredizzimo** [comment]
For now, you should be able to use `let g:neovide_fullscreen=1` inside Neovide.

The issue seems to be that the settings are not applied if the config is loaded before the Window is created. I will update this PR with the fix for the fullscreen, since the fix should be the same:
* https://github.com/neovide/neovide/pull/2619

**Comment by fredizzimo** [comment]
This will be fixed by:
* https://github.com/neovide/neovide/issues/2637

**Comment by myth0genesis** [comment]
> For now, you should be able to use `let g:neovide_fullscreen=1` inside Neovide.

This doesn't seem to be respected by Neovide; it does nothing.

**Comment by myth0genesis** [comment]
`lua vim.g.neovide_fullscreen = true` doesn't seem to do anything, either.

**Comment by myth0genesis** [comment]
Okay. I just got it to go fullscreen. Apparently you have to toggle `vim.g.neovide_fullscreen = false` then switch it back to `true`.

**Comment by myth0genesis** [comment]
Okay. So here's what I think is happening. If Neovide is configured to start up with `vim.g.neovide_fullscreen = true`, the variable gets changed, but it's changed before Neovide has the opportunity to read it and go fullscreen, which seems to be what you pointed out already. So when you later set `vim.g.neovide_fullscreen = true`, it's *already* set to true and for some reason doesn't trigger a fullscreen state change because of that, which is why you have to toggle `vim.g.neovide_fullscreen = false`, then set it to `true` again afterward. Doing this in the `init.lua` won't work, though, likely because it's all still happening before Neovide has a chance to read the variable.

So for now I set a keymap to be able to toggle the state in order to give Neovide enough time to be able to read the state of the variable:
```lua
if vim.g.neovide == true then
...
    vim.keymap.set({'n'}, '<F11>',
        function()
            if vim.g.neovide_fullscreen == false then
                vim.g.neovide_fullscreen = true
            else
                vim.g.neovide_fullscreen = false
            end
        end,
        { silent = true }
    )
end
```

At the very least, hopefully this helps you in that it seems to confirm what you suspected already.
