### ISSUE TITLE
Panic when attempting to use with `sudo`

### ISSUE THREAD

**Issue by greg-el** [neovide/neovide#2642]
**Describe the bug**
Panic when attempting to use with `sudo`.

**To Reproduce**
```sh
~/neovide-bug
❯ touch test.rs

~/neovide-bug
❯ sudo neovide test.rs
Authorization required, but no authorization protocol specified

Neovide panicked with the message 'Failed to create winit event loop: NotSupported(NotSupportedError)'. (File: src/window/mod.rs; Line: 126, Column: 38)
This is a bug and we would love for it to be reported to https://github.com/neovide/neovide/issues

Backtrace saved to neovide_backtraces.log!
``` 

**Expected behavior**
For neovide to open the file as superuser.

**Desktop (please complete the following information):**
 - OS: 6.9.1-arch1-2
 - Neovide Version:  0.13.1
 - Neovim Version: v0.10.0

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
[neovide_rCURRENT.log](https://github.com/user-attachments/files/15749072/neovide_rCURRENT.log)

**Comment by fredizzimo** [comment]
This is by design by the Wayland protocol. No GUI applications are allowed to be launched with sudo for security reasons.

But you shouldn't really run Neovide or even standard terminal Neovim with sudo. Instead, you can set the the`VISUAL` environment variable to `neovide`, and use `sudoedit`. Or launch directly `VISUAL=neovide sudoedit /file/to/edit`.

**Comment by greg-el** [comment]
Okay thanks! I thought that may be the case but the message made me err on the side of caution and report it as a bug 😄. I'll close this off.
