### ISSUE TITLE
neovide icon

### ISSUE THREAD

**Issue by Thirdwinter** [neovide/neovide#2651]
**Describe the bug**
In Neovide, the rendering of certain icons is different from the terminal.

**To Reproduce**
Even when using the same font (Maple Mono), the same icon displayed in Neovide and in the terminal (such as WezTerm) appears different.
**Expected behavior**
The same icon should appear the same when displayed in Neovide and in the terminal (such as WezTerm) using the same font (Maple Mono), but they are not.

**Screenshots**
>Using wezterm
>![image](https://github.com/neovide/neovide/assets/149876001/d43ba7f3-5541-4183-ba3f-0a9f92b50f14)

>Using neovide
>![image](https://github.com/neovide/neovide/assets/149876001/af7a2453-c6ac-4997-8589-0b99b84e20cc)

**Desktop (please complete the following information):**
 - OS: win10 22H2
 - Neovide: v0.13.1
 - Neovim: v0.10.0

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
nothing
**Additional context**
nothing

**Comment by fredizzimo** [comment]
Can you provide a log file from `neovide --log` and open something  that has that symbol visible on the screen?

It's not really possible to say anything without more information, I don't even know the unicode of the symbol.

**Comment by Thirdwinter** [comment]
I'm very sorry I didn't describe the clearing issue. First doing `neovide --log` doesn't show the output, but opens my nvim dashboard, and secondly about the wrong icons, which come from [lunarnVim icons](https://github.com/LunarVim/LunarVim/blob/master/lua/lvim/icons.lua)
like this：
>wezterm&&neovim
>![image](https://github.com/neovide/neovide/assets/149876001/d2678cec-0496-4f2a-9302-da46cd976469)

>neovide
>![image](https://github.com/neovide/neovide/assets/149876001/90026cf6-0074-4207-8aa8-33aa1949dcdf)

**Comment by fredizzimo** [comment]
The log file should be written to the same folder as you start `neovide -log` from it should be named `neovide_rCURRENT.log`. 

Is it possible that you have two versions of the font installed? Check the list of fonts with `set guifont=*` it looks like the missing icons are the onea that were removed in nerd fonts 3.0, so the font you are using is likely outdated.

**Comment by Thirdwinter** [comment]
Thanks, I found the log, it looks very long, the font is from the `nerdfonts.com`, it should be fine, and I tried two other fonts, only **Code New Roman Nerd Font Mono** can show the icons I listed earlier.
![image](https://github.com/neovide/neovide/assets/149876001/986ef8e1-a9e3-4e95-aa16-ba1ee83431b8)

**Comment by fredizzimo** [comment]
You can zip the logfile, and it should be small enough to attach here.

I don't think the font is downloaded from nerdfonts.com, because it's not one of the official fonts there. In fact there's no legal way to get it other than patching it yourself, because the base font is owned by Apple. But despite that it can be downloaded from the internet.

Also all the Nerd Fonts that work should have Nerd Font in the name.

**Comment by Thirdwinter** [comment]
Sorry, maybe my memory is a little confused, it's been a while. You are right, it can just be previewed there instead of downloaded. Also, the following is my log.
[neovide_rCURRENT.log](https://github.com/user-attachments/files/15818472/neovide_rCURRENT.log)

**Comment by fredizzimo** [comment]
I think what's going on here is that Neovide fails back to it's outdated embedded version of Fira code. We should probably update that, but for now you should be able to add a nerd font to your fallback font list. `Symbols Nerd Fonts` is enough.

But for the best experiennce your primary font should be a nerd font, otherwise the icons will have slightly the wrong size.

**Comment by Thirdwinter** [comment]
It does. I have changed the font, thanks for your help.😊
