### ISSUE TITLE
Stop blinking the cursor when the window is inactive

### ISSUE THREAD

**Issue by epheien** [neovide/neovide#2654]
iTerm, alacritty and macvim can stop blinking when windows is inactive.

But Neovid always blinks the cursor, and the biggest problem is that if inactive windows keep flashing the cursor, the laptop's power consumption will be faster than expected.

OS: macOS 12.7.5

**Comment by fredizzimo** [comment]
I'm not sure that this should be a Neovide feature it might be better dealt with as a companion plugin or a FAQ entry, because you can currently do this by handling [FocusLost/FocusGained](https://neovim.io/doc/user/autocmd.html#FocusLost), and then set the [guicursor](https://neovim.io/doc/user/options.html#'guicursor') you want.

This also allows for example dimming the cursor, or changing it to an outline or something when the focus is lost. Although I think adding an outline shape needs new support from Neovim.

**Comment by fredizzimo** [comment]
That support could also perhaps be integrated into something like this https://github.com/rasulomaroff/cursor.nvim.

**Comment by epheien** [comment]
> I'm not sure that this should be a Neovide feature it might be better dealt with as a companion plugin or a FAQ entry, because you can currently do this by handling [FocusLost/FocusGained](https://neovim.io/doc/user/autocmd.html#FocusLost), and then set the [guicursor](https://neovim.io/doc/user/options.html#'guicursor') you want.
> 
> This also allows for example dimming the cursor, or changing it to an outline or something when the focus is lost. Although 

What is the difference in power consumption (computational cost) between using NVIM implementation (usually by resetting the guicursor option) and Neoside implementation for laptops.

Because I can open quite a few Neovim instances, but only use one of them, the rest are usually minimized or inactive, so the power consumption in the inactive state is crucial for me.

**Comment by fredizzimo** [comment]
There would be no difference, if no animations or cursor blinking is enabled and nothing changes, then Neovide does nothing.

Note that the cursor blinking itself is quite expensive currently, since the whole screen is updated. It should be possible to redraw only what's covered by the cursor, but someone needs to implement it.
