### ISSUE TITLE
App crashes because of text printed by .zprofile when double clicking the app icon on macOS Sonoma

### ISSUE THREAD

**Issue by erynofwales** [neovide/neovide#2677]
**Describe the bug**
On macOS Sonoma 14.5, the Neovide app crashes on launch. The window that appears with details about the crash reports that it's trying to execute some text that my `.zprofile` prints as a command. See attached screenshot.

The version of Neovide I installed via Homebrew does not crash this way. Neither does the app crash if I run the binary directly from the command line, or if I double click the binary inside the app bundle. This crash only occurs if I double tap the app icon.

**To Reproduce**
1. With ZSH set as your default shell, add some commands to your `.zprofile` that print some text.
2. Double click the Neovide.app bundle
3. Observe crash

**Expected behavior**
The app shouldn't crash. :)

**Screenshots**
<img width="921" alt="Screenshot 2024-06-29 at 11 20 36" src="https://github.com/neovide/neovide/assets/699653/9702076e-7698-4482-884b-fcb0b9212650">

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 14.5
 - Neovide Version: 0.13.1, according to the short bundle version string in the Info.plist
 - Neovim Version: 0.10.0

**Comment by fredizzimo** [comment]
A login shell is not started automatically on macOS, like it is on Linux for example. This means that every terminal instance need to start it manually. Neovide is not quite a terminal, but assumes a shell environment. Without that, many things, for example paths to LSP servers and some environment variables need to be setup for Neovim to function properly.

So, the approach Neovide takes is to wrap the internal Neovim process inside a non-interactive login shell. Since the communication with Neovim, and also some of the helper commands like `which` happens through stdout/stdin, there's a hard requirement for the shell to not output anything extra when run in`non-interactive` mode. That is a reasonable assumption to make, since it's non-interactive, no one would see the output.

In your example when running both `neovim -v` and `which neovim` additional output is returned, and in the case of which has the side effect of trying to run the output (it should have returned a file path, not tmux status).

I don't think there's anything we can do on the Neovide side, unless someone has a better idea of how to ensure that Neovim runs in a login shell environment. So the fix has to be done on your side, and ensure that nothing is output when the shell starts in non interactive mode. The easiest way to do that is to move the output to `.zshrc`, or perhaps by testing with `if [[ -o interactive ]]`.

**Comment by fredizzimo** [comment]
Note, there are two minor Neovide  bugs here related to the error message displayed.

1. The `command not found: You` text  should not be part of our error message. 
2. The`Check your shell configuration` should tell you exactly what to check. It used to to that, but it seems like it has been refactored without understanding it's purpose.

**Comment by erynofwales** [comment]
Thank you for the detailed explanation. I wasn't aware of the requirement for non-interactive shells to not print anything. I fixed my she;l config and now Neovide works correctly. :)
