### ISSUE TITLE
Older MacOS support 

### ISSUE THREAD

**Issue by kuntau** [neovide/neovide#2679]
**Is your feature request related to a problem? Please describe.**
Neovide need new macOS version to install

**Describe the solution you'd like**
Due to technical problem, I'm stuck with Catalina & Big Sur on my 2 MacOS system

**Describe alternatives you've considered**
Currently running `v0.11.2` on Big Sur machine

**Additional context**
Granted I know nothing about macOS development, I don't if there's technical reason why higher version macOS is required, but I have many applications which still actively updated without requiring newer macOS version namely, browsers firefox, edge, chrome, affinity suites, whatsapp deskttop, alfred, dash, obsidian, mpv, iina, amethyst, sublime, zed, reeder and many more which still running fine on Catalina/Big Sur.

So I don't see why Neovide which a text editor need newer macOS version.

**Comment by fredizzimo** [comment]
You might be able to compile it from source https://neovide.dev/installation.html#mac-source. But we had to remove support for macOS 11 Big Sur, due to the CI failing.
* https://neovide.dev/installation.html#mac-source

Fixing that is no longer an option either, since Github will remove the support completely this month https://github.blog/changelog/2024-05-20-actions-upcoming-changes-to-github-hosted-macos-runners/#macos-11-deprecation-and-removal

Bigger software might have the resources to have custom build system and QA resources for supporting unsupported OS versions, but Neovide is a tiny project in comparison without those resources. We barely have macOS developers at all.

**Comment by kuntau** [comment]
Thank you for your comprehensive answer!
