### ISSUE TITLE
Problem running neovide under jetify devbox on wsl-2

### ISSUE THREAD

**Issue by mwoodpatrick** [neovide/neovide#2737]
**Describe the bug**

I'm running neovide under jetify devbox on wsl-2. 

**To Reproduce**

Steps to reproduce the behavior, I installed neovide using:

```

1. [devbox add neovide@latest](https://www.nixhub.io/packages/neovide)
2. devbox shell
3. neovide --help # or just neovide

Neovide panicked with the message 'Failed to create winit event loop: Os(OsError { line: 80, file: "/build/neovide-0.13.3-vendor.tar.gz/winit/src/platform_impl/linux/wayland/event_loop/mod.rs", error: WaylandError(Connection(NoCompositor)) })'. (File: src/window/mod.rs; Line: 126, Column: 38)
```

**Expected behavior**
neovide runs without error

**Desktop (please complete the following information):**
wsl.exe --version

> WSL version: 2.3.13.0
> Kernel version: 6.6.36.3-1
> WSLg version: 1.0.63
> MSRDC version: 1.2.5326
> Direct3D version: 1.611.1-81528511
> DXCore version: 10.0.26100.1-240331-1435.ge-release
> Windows version: 10.0.22631.3958

 - Neovide Version 0.13.3
 - Neovim Version v0.10.0
 
 nvim -V1 -v
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1713773202

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/pyq71ibs4rz892fhib8x9dyqm0lvr5c8-neovim-unwrapped-0.10.0/share/nvim

**Please run and paste the contents of the `.log` file created in the current directory here:**

 `[neovide_backtraces.log] (https://github.com/user-attachments/files/16404963/neovide_backtraces.log)` 

**Additional context**
I verified other X/Wayland apps ran e.g. xterm, konsole, firefox & google-chrome-stable ran without issue, nvim aslos runs fine in console mode.

**Comment by Kethku** [comment]
Wsl2 is extremely finnicky. I'm not surprised that under certain systems emulated using it, Winit fails in obscure ways. Luckily I don't recommend running neovide from inside wsl2 since you can connect to a neovim instance inside wsl instead of emulating the entire window system. You get better performance, more stability, while still running inside the instance.

Try using https://neovide.dev/command-line-reference.html#wsl. Closing as wont fix as I don't think we can handle all of the edge cases for wsl2 and we already have a better solution via the wsl commandline argument
