### ISSUE TITLE
Neovide crashes on systems that don't support Vulkan without elaborating

### ISSUE THREAD

**Issue by TadaHrd** [neovide/neovide#2746]
**Is your feature request related to a problem? Please describe.**
When I opened Neovide, I got nothing but a 101 error code.

**Describe the solution you'd like**
It should print a message explaining that it crashed and possibly why it crashed.
The book at https://neovide.dev/ should also include problems with OpenGL.

**Describe alternatives you've considered**
*No response.*

**Additional context**
*No response.*

**Comment by fredizzimo** [comment]
Neovide does not need Vulkan, so we can't tell you that. 

Secondly, I think you should get a `neovide_backtraces.log` log file, which should contain more information. We can't always print all errors, in case it crashes when it tries to show the error window. 

Neovide can crash in multiple different ways due to driver issues, so we can't really have an up-to-date FAQ about all the cases. It's easier for us to deal with the issues as they are reported.

**Comment by Kethku** [comment]
Closing for lack of response. Please reopen if you have more details such as the backtraces log file
