### ISSUE TITLE
Floating window transparency settings not respected

### ISSUE THREAD

**Issue by Kethku** [neovide/neovide#720]
Floating windows in neovide use buffer local options to configure how they are rendered with respect to transparency. Currently neovide just renders windows ignoring those settings using a consistent transparency for everything.

To fix this, we will have to integrate buffer local options into Neovide's settings system somehow. I'm not sure what the best way would be to do that as the settings are synced globally. I'm currently thinking we will need the following:

1. Add tracking on neovim side for both options and variables in all scopes. This will require some work 
2. Modify neovide settings system to have field level attributes which indicate what kind of setting the field represents. Currently I think this would be variables and options
3. Modify the sync logic to report what type and scope of setting was used
4. Modify settings acquisition function to take a scope which could be a buffer/window/tab id. Then the object returned would follow neovim scope logic to determine which setting value to resolve to

Once these are done, we should be able to make a small change to the window rendering logic to first fetch the transparency settings before rendering the background. This would also deprecate some of the neovide specific transparency settings in favor of using the built in ones.

**Comment by shaunsingh** [comment]
After this issue is fixed/merged, will the --multiGrid flag be enabled by default?

**Comment by Kethku** [comment]
I think it should be yes. Maybe even just remove the option to not have multiGrid

**Comment by Hubro** [comment]
As a stopgap, would it be possible to add a global variable to disable transparent windows? `nvim-lazygit` is currently unusable in Neovide:

![image](https://user-images.githubusercontent.com/597206/125114613-797aeb80-e0ea-11eb-9cde-5d334ad8130a.png)

If I disable blurring and set opacity of floating windows to 1, then sometimes the contents of the window disappears completely:

![image](https://user-images.githubusercontent.com/597206/125114753-a9c28a00-e0ea-11eb-9bab-657c8329b8f5.png)

Presumably because the border window is drawn on top of the content window.

Other times (seemingly randomly) the content window is drawn on top:

![image](https://user-images.githubusercontent.com/597206/125114823-c19a0e00-e0ea-11eb-97a6-8a26246eca33.png)

And even in this best-case scenario, the font is now weirdly broken. If you view the screenshot in full size, you'll see the symbols are oddly cropped and jagged in some places. This is much more pronounced on bold fonts (see the white diff line at the top of the window.)

While this issue is being worked on, it would be useful to be able to toggle this feature off completely.

**Comment by Hubro** [comment]
In the last couple of weeks, I have been replacing several of my plugins with Telescope. It has become an integral part of my workflow, as I use it to browse files, navigate documents, review pull requests and so on. Unfortunately this means that I'm no longer able to use Neovide as my daily driver, since Telescope is based on floating windows :disappointed:

**Comment by Kethku** [comment]
I'm actively working on this, but progress is slow as the settings system is partially implemented in a relatively opaque procedural macro. I'm very hopeful to fix this soon though, sorry for the delay

**Comment by hgup** [comment]
### Just like you have these two options:
`g:neovide_window_floating_opacity` = 0
`g:neovide_floating_blur` = 0

### Please add one more:
`g:neovide_window_floating_blur` = 0

I am facing performance issues when I run a fuzzy search like Telescope. But I would like to have the blur in the autocomplete menu and the console log at the bottom.

**Comment by Kethku** [comment]
I'm concerned that the blur is not the problem. Multigrid renders with a very different system where every window gets its own surface to draw to which is stored between frames. It then composits those surfaces onto the actual screen any time any of them change. Its possible that the way that compositing works is too expensive on some machines compared to just rendering a single window

**Comment by hgup** [comment]
What I did was I turned off blur using the `g:neovide_floating_blur = 0` setting and that too in the Multigrid mode.
After doing so, it doesn't lag at all.
It may be because as you said that the composting is too expensive (especially when you have blur on) for my machine.
However, single window renders don't have any problem at all.

The only three feasible solutions that I see are:
1. upgrade my machine 💀 
2. have a setting inside Telescope to render only a single window
3. have a setting inside neovide to turn off blur for only floating windows/buffers (and not all floating areas, to have that bling).

Or an even greater solution (which might be too much to ask 😅) would be to create buffer name specific blur settings. (or maybe one of you genius ones can create a vimscript for that).

**Comment by dineshKumar777** [comment]
#979 merged. Now telescope and floating windows working fine for when enabling multigrid.

**Comment by Kethku** [comment]
Note I think this is still broken. Transparency works but not on a per window basis which is really how it should be done. I'd like to be in a place where the transparency settings work the same as the built in fake transparency but includes extra features such as blurring if desired.

We aren't there yet unfortunately :(

**Comment by fredizzimo** [comment]
Also, currently the `g:neovide_floating_opacity` also makes the text transparent. I don't think that should be the case, or at least that's not what I want, at least not for foreground windows. 

I had to set mine to 1.0 from the default 0.7, because the font colors in Neovim floating windows became very washed out.

**Comment by LoipesMas** [comment]
Transparent text was fixed in #979, but Kethku reverted it and we didn't resolve it after that. It's [this line](https://github.com/neovide/neovide/pull/979/files#r767411188).

**Comment by Kethku** [comment]
Had to revert it due to antialiasing issues. I will try to do another pass soon

**Comment by LoipesMas** [comment]
I think antialiasing is a problem anyway (see #1102 ). Changing to non-subpixel antialias looks better (that's my opinion, but I think it's just more correct). We could just change it to non-subpixel, but *maybe* someone prefers that look so maybe we could add an option, but this has it's own problems (everything needs to be reinstantiated on change, or just check for the option at launch (something like #1119 :slightly_smiling_face: )). I'm using "patched" version with non-subpixel antialiasing and "reverted revert" of that line and everything looks fine, but it may differ from config to config and it's probably subjective.

**Comment by xbladesub** [comment]
any updates?

**Comment by fredizzimo** [comment]
I think the `g:neovide_floating_transparency` option should be removed, it doesn't really make sense to have a global configuration like that. 

The correct way to configure it is through the [winblend option](https://neovim.io/doc/user/options.html#'winblend'). I don't know if it works correctly in the mainline Neovim, but at least in my branch with the rendering performance improvements this now works correctly. In fact I already removed any usage of the `g:neovide_floating_transparency` in that branch, since as this issues suggests it didn't work before either.

The global `g:neovide_transparency` option for the background still works, But I think that too would be better configured with the theme through windblend.

**Comment by xbladesub** [comment]
> I think the `g:neovide_floating_transparency` option should be removed, it doesn't really make sense to have a global configuration like that.
> 
> The correct way to configure it is through the [winblend option](https://neovim.io/doc/user/options.html#'winblend'). I don't know if it works correctly in the mainline Neovim, but at least in my branch with the rendering performance improvements this now works correctly. In fact I already removed any usage of the `g:neovide_floating_transparency` in that branch, since as this issues suggests it didn't work before either.
> 
> The global `g:neovide_transparency` option for the background still works, But I think that too would be better configured with the theme through windblend.
<img width="1423" alt="Screen Shot 2022-10-04 at 7 15 19 PM" src="https://user-images.githubusercontent.com/45129790/193805278-8384e2c0-8132-497b-9ce5-bd451dc72d17.png"

Does you branch support custom fonts? I ran it with my existing lunarvim config and neovide settings for main repo

**Comment by fredizzimo** [comment]
Yes, there should be no difference between custom and default fonts. 

But if you actually mean a custom font per floating window, then that's out of scope for this issue. That could technically be added to Neovide, at least as long as the positioning is done through the normal grid. Full proper support would need changes to Nvim, but I do believe we could use `nvim_win_set_var` to pass the values, without any upstream changes.

**Comment by lost22git** [comment]
any update ？and how to make cmp and telescope transparent (aka. guibg=none) ?

**Comment by lost22git** [comment]
effect without `--multigrid` and how to get it with `--multigrid` ?

![动画](https://user-images.githubusercontent.com/65008815/209296253-c1e1d7f9-9b93-4cc1-a31c-8447f6b4ea5a.gif)

![动画2](https://user-images.githubusercontent.com/65008815/209296287-d0501f5c-f2c7-4848-af1e-a4a921e77060.gif)

**Comment by Ciel-MC** [comment]
I think I'm being stupid but I just can't get transparency to work on Telescope at all, I tried opening a telescope menu, go into normal mode and doing :se winblend=100 but I still see nothing past the telescope window, what did I do wrong? Or is this another macos bug?

**Comment by xbladesub** [comment]
> effect without `--multigrid` and how to get it with `--multigrid` ?
> 
> ![动画](https://user-images.githubusercontent.com/65008815/209296253-c1e1d7f9-9b93-4cc1-a31c-8447f6b4ea5a.gif) [ ](https://user-images.githubusercontent.com/65008815/209296253-c1e1d7f9-9b93-4cc1-a31c-8447f6b4ea5a.gif) ![动画](https://user-images.githubusercontent.com/65008815/209296253-c1e1d7f9-9b93-4cc1-a31c-8447f6b4ea5a.gif) [ ](https://user-images.githubusercontent.com/65008815/209296253-c1e1d7f9-9b93-4cc1-a31c-8447f6b4ea5a.gif)
> 
> ![动画2](https://user-images.githubusercontent.com/65008815/209296287-d0501f5c-f2c7-4848-af1e-a4a921e77060.gif) [ ](https://user-images.githubusercontent.com/65008815/209296287-d0501f5c-f2c7-4848-af1e-a4a921e77060.gif) ![动画2](https://user-images.githubusercontent.com/65008815/209296287-d0501f5c-f2c7-4848-af1e-a4a921e77060.gif) [ ](https://user-images.githubusercontent.com/65008815/209296287-d0501f5c-f2c7-4848-af1e-a4a921e77060.gif)

You need to open `Neovide` instance with arguments. 
terminal:
`which neovide` - it will show you the path to your `neovide` executable.
`path_to_neovide_executable --multigrid`. But keep in mind that `--multigrid` feature is currently broken - transparency on floating windows doesn't work properly, also some floating windows on open will freeze your entire system using `--mutligrid`

**Comment by cauliyang** [comment]
The float terminal window does not work well when neovide is set to transparent mode. 

![image](https://github.com/neovide/neovide/assets/38903141/f1b526ec-b3b3-4e19-8d65-5b8b1e2c3fc7)

here is my configuration. 

```bash
neovide --multigrid --frame none
```

```lua
  		vim.g.neovide_scale_factor = 1.9
        vim.g.neovide_hide_mouse_when_typing = true
        vim.g.neovide_input_macos_alt_is_meta = true
        vim.g.neovide_hide_mouse_when_typing = false
        vim.g.neovide_refresh_rate = 60
        vim.g.neovide_refresh_rate_idle = 5
        vim.g.neovide_no_idle = true
        vim.g.neovide_confirm_quit = true
        vim.g.neovide_input_use_logo = true

        vim.g.neovide_cursor_antialiasing = true
        vim.g.neovide_cursor_animate_in_insert_mode = true
        vim.g.neovide_cursor_vfx_mode = "pixiedust"
        vim.g.neovide_cursor_vfx_particle_speed = 20.0

        vim.g.neovide_padding_top = 0
        vim.g.neovide_padding_bottom = 0
        vim.g.neovide_padding_right = 0
        vim.g.neovide_padding_left = 0

        -- Helper function for transparency formatting
        local alpha = function()
            return string.format("%x", math.floor(255 * (vim.g.transparency or 0.8)))
        end
        vim.g.neovide_transparency = 0.0
        vim.g.transparency = 0.8
        vim.g.neovide_background_color = "#0f1117" .. alpha()


```

I have no idea what happens. Anybody can help here?  Many thanks!

**Comment by fredizzimo** [comment]
I think most of the transparency issues will be fixed by https://github.com/neovide/neovide/pull/1870. But note that there are several limitations to what we can do, see the discussions in https://github.com/neovide/neovide/pull/1790, which #1870 is based on.
