### ISSUE TITLE
Feature Request: context-zooming

### ISSUE THREAD

**Issue by JacobTravers** [neovide/neovide#860]
**Describe the solution you'd like**
This is a feature request for 'context-zooming' (what I'm dubbing it) as opposed to code-folding. The concept of context-zooming can be seen on [makepad.dev](https://makepad.dev/), by clicking inside the editor and then holding down `alt`

**Comment by Kethku** [comment]
Doing that properly would require extra details from neovim upstream. In particular we will likely need to add resizing of individual windows rather than resizing the entire window. This should be possible but will take some time and probably won't be ready until after we finish the bugs blocking the next release

**Comment by kiuKisas** [comment]
Wow ! Never see such a thing, really cool !

**Comment by Kethku** [comment]
Im actually going to close this as practically out of scope. It would require:
- access to or reimplementation of syntax highlighting for the entire document
- replication of the entire document text on the gui side rather than just the visible window
- WAY faster renderer. Its possible that skia could be coerced into doing this but im sorta doubtful
- a pretty significant rearchitecture of the cursor rendererer
- a bunch of other work

I totally agree that this is a cool feature, but I think there are a bunch of other features that are higher priority sooner. If somebody wants to own doing the necessary work to get something like this up and running though I'd be all ears!
